/** Maps common gym names to canonical catalog exercise names. */
export const EXERCISE_NAME_ALIASES: Record<string, string> = {
  "bench press": "barbell bench press",
  "incline bench press": "barbell incline bench press",
  "decline bench press": "barbell decline bench press",
  "dumbbell bench press": "dumbbell bench press",
  "push up": "push-up",
  "push ups": "push-up",
  pushup: "push-up",
  pushups: "push-up",
  "pull up": "pull-up",
  "pull ups": "pull-up",
  pullup: "pull-up",
  pullups: "pull-up",
  "chin up": "chin-up",
  "chin ups": "chin-up",
  chinup: "chin-up",
  squat: "barbell full squat",
  squats: "barbell full squat",
  "front squat": "barbell front squat",
  deadlift: "barbell deadlift",
  deadlifts: "barbell deadlift",
  "romanian deadlift": "barbell romanian deadlift",
  rdl: "barbell romanian deadlift",
  "stiff leg deadlift": "advanced dumbbell stiff leg deadlift",
  "sumo deadlift": "barbell sumo deadlift",
  "lat pulldown": "cable pulldown",
  "lat pull down": "cable pulldown",
  pulldown: "cable pulldown",
  "shoulder press": "barbell seated overhead press",
  "overhead press": "barbell seated overhead press",
  "military press": "barbell seated overhead press",
  "lateral raise": "dumbbell lateral raise",
  "front raise": "dumbbell front raise",
  "rear delt fly": "dumbbell rear delt raise",
  "bicep curl": "barbell curl",
  "biceps curl": "barbell curl",
  "hammer curl": "dumbbell hammer curl",
  "tricep extension": "cable pushdown",
  "triceps extension": "cable pushdown",
  "tricep pushdown": "cable pushdown",
  "triceps pushdown": "cable pushdown",
  "skull crusher": "barbell lying triceps extension",
  "leg press": "sled 45в° leg press",
  "hip thrust": "barbell glute bridge",
  "glute bridge": "barbell glute bridge",
  "chest fly": "dumbbell fly",
  "chest flye": "dumbbell fly",
  "leg curl": "lever lying leg curl",
  "leg extension": "lever leg extension",
  "calf raise": "barbell standing calf raise",
  "calf raises": "barbell standing calf raise",
  row: "barbell bent over row",
  "bent over row": "barbell bent over row",
  "barbell row": "barbell bent over row",
  "dumbbell row": "dumbbell bent over row",
  lunge: "barbell lunge",
  lunges: "barbell lunge",
  "hip abduction": "lever seated hip abduction",
  plank: "front plank with twist",
  burpee: "burpee",
  burpees: "burpee",
};
