/** Neutral platform UI copy (English). */

export const platformCopyEn = {
  nav: {
    home: "Home",
    programs: "Programs",
    aiCoach: "AI Coach",
    liveCoaching: "Live coaching",
    live: "Live",
    profile: "Profile",
    welcome: (name: string) => `Welcome, ${name}`,
    theme: "Theme",
  },
  trainTabs: {
    workout: "Workout",
    nutrition: "Nutrition",
  },
  profile: {
    title: "Profile",
    subtitle: "Account · subscription · health profile",
    healthProfile: "Health profile",
    complete: "Complete",
    inProgress: "In progress",
    incomplete: "Incomplete",
    account: "Account",
    plan: "Plan",
    manageAccount: "Manage your account and preferences",
    personalInfo: "Personal info",
    appearance: "Appearance",
    password: "Password",
  },
  subscription: {
    title: "Subscription & plans",
    active: "Active",
    accessUntil: (date: string) => `Access until ${date}, then back to free preview`,
    renewsExpires: (date: string) => `Renews / expires ${date}`,
  },
  settings: {
    fullName: "Full name",
    email: "Email",
    phone: "Phone number",
    fitnessGoal: "Fitness goal",
    language: "Language",
    units: "Units",
    metric: "EU / Metric (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    metricToggle: "kg / cm",
    imperialToggle: "lb / ft",
    theme: "Theme",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    accentColor: "Accent color",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated",
    updatePassword: "Update password",
    updating: "Updating...",
    passwordUpdated: "Password updated",
  },
  goals: {
    none: "No goal set",
    lose_weight: "Lose weight",
    build_muscle: "Build muscle",
    stay_fit: "Stay fit",
    improve_endurance: "Improve endurance",
    general_health: "General health",
  },
  dashboard: {
    nutrition: "Nutrition",
    todaysWorkout: "Today's Workout",
    tomorrowsWorkout: "Tomorrow's Workout",
    workoutOnDay: (day: string) => `${day}'s Workout`,
    todaysCardio: "Today's Cardio",
    tomorrowsCardio: "Tomorrow's Cardio",
    cardioOnDay: (day: string) => `${day}'s Cardio`,
    todaysMealPlan: "Today's meal plan",
    mealPlanOnDay: (date: string) => `Meal plan · ${date}`,
    toDoOnDay: (day: string) => `${day}'s To Do`,
    toDoToday: "Today's To Do",
    toDoTomorrow: "Tomorrow's To Do",
    myProgress: "My Progress",
    viewDetails: "View details",
  },
  common: {
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    edit: "Edit",
    add: "Add",
    done: "Done",
    close: "Close",
    next: "Next",
    update: "Update",
    choose: "Choose",
    saving: "Saving…",
    loading: "Loading…",
    current: "Current",
    scheduled: "scheduled",
    active: "active",
    completed: "Completed",
    incomplete: "Incomplete",
    inProgress: "In progress",
    skipped: (n: number) => `${n} skipped`,
    min: (n: number) => `${n} min`,
    sessions: (n: number) => `${n} session${n === 1 ? "" : "s"}`,
    folders: (n: number) => `${n} folder${n === 1 ? "" : "s"}`,
    programs: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    dayMenus: (n: number) => `${n} day menu${n === 1 ? "" : "s"}`,
    exercises: (n: number) => `${n} exercise${n === 1 ? "" : "s"}`,
    completedCount: (done: number, total: number) => `${done}/${total} completed`,
    doneForDate: (done: number, total: number, date: string) =>
      `${done}/${total} done for ${date}`,
    today: "today",
    surrendering: "Surrendering…",
  },
  aria: {
    completed: "Completed",
    close: "Close",
    collapseTasks: "Collapse tasks",
    expandTasks: "Expand tasks",
    collapseMeals: "Collapse logged meals",
    expandMeals: "Expand logged meals",
    collapseWorkoutResults: "Collapse workout results",
    expandWorkoutResults: "Expand workout results",
    viewMealPlan: "View meal plan",
    logMeal: "Log meal",
    logWeight: "Log weight",
    addHabit: "Add habit",
    dismissSuggestion: "Dismiss suggestion",
    editHabit: "Edit habit",
    removeHabit: "Remove habit",
    sendMessage: "Send message",
    attachFile: "Attach image",
    removeAttachment: "Remove attachment",
    webSources: (n: number) => `${n} web sources`,
    deleteItem: (name: string) => `Delete ${name}`,
    deleteMeal: "Delete meal",
    removePhoto: (pose: string) => `Remove ${pose} photo`,
    viewPhoto: (pose: string) => `View ${pose} photo`,
    earlierMonth: "Earlier month",
    laterMonth: "Later month",
    mealInsights: (name: string) => `View insights for ${name}`,
    removeMeal: (name: string) => `Remove ${name}`,
  },
  nutrition: {
    mealsLogged: "Meals logged",
    recentlyLogged: "Recently logged",
    recentlyUploaded: "Recently uploaded",
    caloriesLeft: "Calories left",
    caloriesUnit: "calories",
    proteinLeft: "Protein",
    carbsLeft: "Carbs",
    fatLeft: "Fat",
    logFirstMealHint: "Tap + to log your first meal",
    waterGoalReached: "Water goal reached",
    aiCoachPlan: "AI Coach plan",
    yourMealPlan: "Your meal plan",
    coachPdfPending: "Coach PDF plan · pending",
    coachNutritionPdf: "Coach nutrition plan · PDF",
    mealPlanEmpty:
      "No meal plan for this day yet. Build one in Programs → Nutrition or with AI Coach.",
    coachPdfEmpty:
      "Your coach PDF plan is still being prepared. Create or activate a personal or AI meal plan under Programs → Nutrition, or log meals with +.",
    drinkWater: (ml: number) => `Drink ${ml.toLocaleString()} ml`,
    fiber: "Fiber",
    sugar: "Sugar",
    sodium: "Sodium",
    healthScore: "Health score",
    healthScoreInnerBefore: "health",
    healthScoreInnerAfter: "score",
    macros: "Macros",
    microNutrients: "Micro nutrients",
    water: "Water",
    logMeal: "Log meal",
    viewDietPlan: "Diet plan",
    waterLogged: (logged: number, goal: number, deadline: string) =>
      `${logged.toLocaleString()} ml logged · goal by ${deadline}`,
    eatBetween: (window: string) => `Eat between ${window}`,
    options: (n: number) => `${n} option${n === 1 ? "" : "s"}`,
    moreOptions: (n: number) => `+${n} more`,
    ate: "Ate",
    windowClosed: "Window closed",
    title: "Nutrition",
    foldersMeta: (folders: number, menus: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${menus} day menu${menus === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowDayMenu: "Day menu",
    flowSchedule: "Schedule",
    mealsTile: "Meals",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    folderNamePlaceholder: "Folder name",
    newFolder: "New folder",
    dayMenu: "day menu",
    dayMenus: "day menus",
    scheduleOnCalendar: "Schedule on calendar",
    scheduleDescription:
      "Pick a start date and repeat days. Scheduled menus appear on your dashboard calendar.",
    start: "Start",
    repeatOn: "Repeat on",
    weeks: "Weeks",
    alsoAddDates: "Also add specific dates",
    currentlyScheduled: (n: number) =>
      `Currently scheduled: ${n} day${n === 1 ? "" : "s"}`,
    saveSchedule: "Save schedule",
    scheduleCleared: "Schedule cleared.",
    scheduleUpdated: (n: number) => `Scheduled ${n} day${n === 1 ? "" : "s"}.`,
    scheduleRemoved: "Upcoming days removed.",
  },
  meals: {
    title: "Meals",
    addMeal: "Add meal",
    addToFolder: "Add to folder",
    editMeal: "Edit meal",
    newMeal: "New meal",
    chooseFolder: "Choose folder",
    choosePlan: "Choose plan",
    chooseFolderPlaceholder: "Choose a folder…",
    addCopyHint: "Add a copy of this meal to a folder or plan.",
    loadingPlans: "Loading plans…",
    newMealPlanIn: (folder: string) => `+ New meal plan in ${folder}`,
    whichFolder: "Which folder should this meal go in?",
    backTo: (name: string) => `← Back to ${name}`,
    nameRequired: "Meal name is required",
    noMealsOfType: (type: string) => `No ${type} meals found.`,
  },
  workout: {
    title: "Workouts",
    fallbackTitle: "Workout",
    stillInGym: "Still in the gym",
    readyToStart: "Ready to start",
    startWorkout: "Start workout",
    stopWorkout: "Stop workout",
    stop: "Stop",
    hideVideo: "Hide video",
    preview: "Preview",
    setsTarget: (n: number) => `${n} sets target`,
    setsCount: (n: number) => `${n} set${n === 1 ? "" : "s"}`,
    repsTarget: (n: string | number) => `${n} reps target`,
    set: "Set",
    reps: "Reps",
    weightKg: "Weight (kg)",
    addSet: "Add set",
    addExercise: "Add exercise",
    elapsed: "Elapsed",
    estimatedTime: "Estimated time",
    estimatedTimeCompact: "est.",
    estTotal: (duration: string) => `Est. ~${duration}`,
    totalSetsLabel: "Total sets",
    totalSetsCompact: "sets total",
    moreExercises: (count: number) => `+${count} more exercise${count === 1 ? "" : "s"}`,
    difficultyForYou: "For you",
    difficultyExplainTitle: "Why this rating?",
    difficultyAnalyzing: "Analyzing your profile and recent results…",
    difficultyWorkoutLoad: "Workout load",
    difficultyYourCapacity: "Your capacity",
    difficultyHarderFactors: "What makes it harder",
    difficultyEasierFactors: "What's in your favor",
    difficultyBalancedProfile: "Your profile and this workout are well matched.",
    tapToSeeWhy: "Tap to see why",
    personalDifficulty: {
      easy: {
        label: "Easy",
        tagline: "You should finish comfortably.",
        summary: "This session is lighter than what your profile suggests you can handle today.",
      },
      intermediate: {
        label: "Intermediate",
        tagline: "A solid challenge.",
        summary: "This lines up with your training background and lifestyle — expect to work, not suffer.",
      },
      hard: {
        label: "Hard",
        tagline: "Respect the session.",
        summary: "Volume, recovery factors, or your profile make this a demanding day.",
      },
      impossible: {
        label: "Impossible",
        tagline: "Be smart — scale if needed.",
        summary: "On paper this outpaces what your health & lifestyle profile suggests is realistic right now.",
      },
    },
    personalDifficultyReasons: {
      beginnerExperience:
        "Beginner training level — higher volume hits harder while you're still building capacity.",
      intermediateExperience: "Intermediate training background helps you absorb this workload.",
      advancedExperience: "Advanced training history makes this volume more manageable for you.",
      lowTrainingFrequency: "You train infrequently right now, so each session feels heavier.",
      highTrainingFrequency: "You train often, so your body is used to handling more.",
      injuries: (params: { areas: string }) =>
        `Injury areas (${params.areas}) can make this session tougher or need modifications.`,
      injuryDetails: "Injury notes on your profile suggest extra caution today.",
      healthConditions: (params: { conditions: string }) =>
        `Health conditions (${params.conditions}) can raise how demanding this feels.`,
      healthDetails: "Additional health details on your profile increase the challenge.",
      medications: "Medications on your profile may affect energy and recovery.",
      medicationsConcerning: (params: { items: string }) =>
        `Prescription or clinical medications (${params.items}) may affect energy and recovery.`,
      medicationsUnknown: (params: { items: string }) =>
        `Unlisted items on your profile (${params.items}) — verify they aren't limiting recovery.`,
      performanceSupplements: (params: { items: string }) =>
        `${params.items} on your profile supports training — not a recovery limiter.`,
      benignSupplements: (params: { items: string }) =>
        `${params.items} on your profile are general supplements, not recovery concerns.`,
      consistentRecentTraining: (params: { count: string }) =>
        `${params.count} workouts in the last 7 days — your body is primed for this load.`,
      inconsistentRecentTraining: (params: { count: string }) =>
        `Only ${params.count} workout(s) in the last 7 days — less recent conditioning.`,
      consistentMealLogging: (params: { count: string }) =>
        `Meals logged ${params.count} of the last 7 days — nutrition tracking supports recovery.`,
      sparseMealLogging: "Few meals logged recently — fueling may be inconsistent.",
      strongDailyHabits: (params: { count: string }) =>
        `Daily habits completed ${params.count} of the last 7 days — strong routine.`,
      lowHydrationToday: "Water intake is low today — hydration may limit performance.",
      goodHydration: "Solid hydration recently supports this session.",
      veryYoungAge: (params: { age: string }) =>
        `Age ${params.age} — recovery and load tolerance are still developing.`,
      youngAge: (params: { age: string }) =>
        `Age ${params.age} — keep form tight and don't chase exhaustion.`,
      olderAge: (params: { age: string }) =>
        `Age ${params.age} — longer recovery may make this feel harder than the numbers suggest.`,
      seniorAge: (params: { age: string }) =>
        `Age ${params.age} — prioritize safety and consider scaling volume.`,
      lowEnergy: "Low energy in your lifestyle questionnaire makes this tougher.",
      highEnergy: "High energy levels give you more room to push today.",
      poorSleep: "Under 6h sleep raises fatigue and makes sets feel heavier.",
      goodSleep: "Solid sleep habits support recovery for this session.",
      highStress: "High stress from your profile can drain performance.",
      smoking: "Daily smoking can reduce stamina for training.",
      alcohol: "Frequent alcohol can blunt recovery and energy.",
      lowSteps: "Low daily movement outside the gym can make training feel harder.",
      activeLifestyle: (params: { activities: string }) =>
        `Active lifestyle (${params.activities}) supports your capacity.`,
      manyExercises: (params: { count: string }) =>
        `${params.count} exercises is a lot of volume in one session.`,
      manySets: (params: { count: string }) => `${params.count} total sets pushes intensity up.`,
      longDuration: (params: { minutes: string }) =>
        `~${params.minutes} min estimated — a long grind.`,
      shortSession: "Shorter session with fewer moving parts keeps this manageable.",
      incompleteProfile:
        "Complete your health & lifestyle questionnaire for a sharper personalized rating.",
    },
    difficulty: {
      easy: { label: "Easy", tagline: "Light work. Show up and move." },
      moderate: { label: "Moderate", tagline: "Real session. Stay locked in." },
      hard: { label: "Hard", tagline: "Heavy day. Earn your shower." },
      brutal: { label: "Brutal", tagline: "Beast mode. No excuses." },
      legend: { label: "Impossible", tagline: "Legend tier. Send help." },
    },
    timeRemaining: (duration: string) => `~${duration} left`,
    finishSummaryTitle: "Session summary",
    setsLogged: (done: number, total: number) => `${done}/${total} sets logged`,
    noExercisesTitle: "No exercises loaded",
    noExercisesHint:
      "This workout day has no exercises yet. Add one below or go back and edit the program.",
    exerciseName: "Exercise name",
    exercisePlaceholder: "e.g. Cable flyes",
    noteOptional: "Note (optional)",
    notePlaceholder: "e.g. Felt strong today, increased weight on bench press…",
    finishNote:
      "Add an optional note about how it went — or skip and save.",
    saveWithNote: "Save with note",
    finishWorkout: "Finish workout",
    finishWithoutNote: "Finish without note",
    lastSets: (parts: string) => `Last: ${parts}`,
    scheduledWorkout: "Scheduled workout",
    completedSuffix: "· completed",
    completeBy: (deadline: string) => `· complete by ${deadline}`,
    workoutPlan: "Workout plan",
    workoutResults: "Workout results",
    musclesTargetedToday: "Muscles targeted today",
    muscleMapFront: "Front",
    muscleMapBack: "Back",
    noResultsLogged: "No sets were logged for this workout.",
    foldersMeta: (folders: number, programs: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${programs} program${programs === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowProgram: "Program",
    flowSchedule: "Schedule",
    allTile: "All",
    exercisesTile: "Exercises",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    foldersNav: "Folders",
    programsCount: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    daysBadge: (n: number) => `${n}d`,
    exBadge: (n: number) => `${n} ex`,
    scheduledBadge: (n: number) => `${n} scheduled`,
    whenToStart: "When to start",
    workoutDay: "Workout day",
    repeatDays: "Repeat on these days",
    repeatWeeks: "Repeat for how many weeks?",
    startNow: "Start right now",
    startNextMonday: "Next week (Monday)",
    saveDaysFirst: "Save at least one workout day before scheduling.",
    upcomingSessions: (n: number) =>
      `${n} upcoming session${n === 1 ? "" : "s"} scheduled. Changes replace future sessions only.`,
    scheduleUpdated: "Schedule updated.",
    scheduleSaved: (n: number) => `Scheduled ${n} session${n === 1 ? "" : "s"}.`,
    sessionsRemoved: "Upcoming sessions removed.",
    saveSchedule: "Save schedule",
    workout: "workout",
    workouts: "workouts",
  },
  cardio: {
    title: "Cardio",
    addCardio: "Add cardio",
    emptyTitle: "No cardio saved yet",
    emptyHint:
      "Pick a cardio type below or add a custom session, then schedule it on your calendar.",
    openYoutube: "Open on YouTube",
    schedule: "Schedule",
    browseTitle: "Browse cardio types",
    mySessions: "My sessions",
    myCardio: "My cardio",
    addScheduleCardio: "Add & schedule cardio",
    locationGym: "Gym",
    locationOutdoor: "Outdoor",
    locationEverywhere: "Anywhere",
    types: {
      treadmill: "Treadmill",
      incline_walk: "Incline walk",
      elliptical: "Elliptical",
      stationary_bike: "Stationary bike",
      spin_bike: "Spin bike",
      rowing_machine: "Rowing machine",
      stair_climber: "Stair climber",
      assault_bike: "Assault bike",
      ski_erg: "Ski erg",
      arc_trainer: "Arc trainer",
      battle_ropes: "Battle ropes",
      sled_push: "Sled push",
      running: "Running",
      trail_running: "Trail running",
      outdoor_cycling: "Outdoor cycling",
      hiking: "Hiking",
      brisk_walking: "Brisk walking",
      swimming: "Swimming",
      open_water_swim: "Open water swim",
      rollerblading: "Rollerblading",
      kayaking: "Kayaking",
      rock_climbing: "Rock climbing",
      cross_country_ski: "Cross-country skiing",
      soccer: "Soccer",
      basketball: "Basketball",
      tennis: "Tennis",
      walking: "Walking",
      jump_rope: "Jump rope",
      hiit: "HIIT",
      dancing: "Dancing",
      jumping_jacks: "Jumping jacks",
      burpees: "Burpees",
      shadow_boxing: "Shadow boxing",
      stair_climbing: "Stair climbing",
      mountain_climbers: "Mountain climbers",
      high_knees: "High knees",
      bodyweight_circuit: "Bodyweight circuit",
      boxing: "Boxing",
      aerobics: "Aerobics",
      yoga_flow: "Yoga flow",
      pilates: "Pilates",
    },
  },
  habits: {
    title: "Daily habits",
    suggestedFromProfile: "Suggested from your health profile",
    inProgressSection: "In progress",
    completedSection: "Completed",
    done: "Done",
  },
  weight: {
    title: "Body weight",
    subtitle: "Track your weight over time",
    loggedForDate: (kg: string, date: string) => `${kg} logged for ${date}`,
    weightForDate: (date: string) => `Weight for ${date} (kg)`,
    placeholder: "e.g. 75.5",
    logWeight: "Log weight",
    invalidWeight: "Enter a valid weight",
  },
  photos: {
    title: "Progress photos",
    monthComplete: "This month complete",
    readMeButton: "Read me",
    readMeTitle: "Before you take progress photos",
    readMeBody: [
      "Take front, back & side photos each month with your camera. Gallery uploads aren't allowed — snap them live for honest progress.",
      "Only use photos of yourself — starting with your very first check-in. Alex remembers who's in your progress photos and checks it matches your profile gender.",
      "The wrong gender or a different person in later photos will be rejected.",
      "Used the wrong person on your first photo by mistake? Contact support and we can reset it.",
    ],
    readMeGotIt: "Got it",
    readMeAgreeLabel: "I have read this and agree",
    readMeRequiredHint: "Read and agree before taking photos",
    readMeSupportHint: "Wrong person on your first photo? Contact support.",
    uploading: "Uploading…",
    addPhoto: "Take photo",
    addPosePhoto: (pose: string) => `Add ${pose} photo`,
    takePosePhoto: (pose: string) => `Take ${pose} photo`,
    replace: "Replace",
    retake: "Retake",
    deletePhoto: "Delete",
    editPhoto: (pose: string) => `Edit ${pose} photo`,
    previousMonths: "Previous months",
    nextCheckIn: "Next check-in",
    noPhoto: "No photo",
    compressHint: "Photos are compressed before upload to save space.",
    removeFailed: "Could not remove photo",
    uploadFailed: "Upload failed",
    analyzing: "Alex is checking your photo…",
    alexWrongPhotoTitle: "Wrong photo",
    retakePhoto: "Retake photo",
    alexAcceptedTitle: "Photo accepted",
  },
  trainer: {
    customWorkout: "Custom workout plan",
    customNutrition: "Custom nutrition plan",
    byTrainer: (name: string) => `by ${name}`,
    oneTime: "one-time",
    ready: "Ready",
    pdfReady: "PDF ready",
    yourPreferences: "Your preferences",
    preferencesPlaceholder:
      "Your goals, experience level, schedule, injuries, food preferences…",
    close: "Close",
    done: "Done",
    continuePayment: "Let's build my plan",
    implementing: "Implementing…",
    implementIt: "Implement it",
    implemented: "Implemented",
    viewPlan: "View plan",
    implementedConfirmed: "Implemented & confirmed",
    onCalendar: "On your calendar",
    nutritionImplemented:
      "Your new nutrition plan is on your calendar. Previous meals were replaced with your coach schedule.",
    workoutImplemented:
      "Your new workout plan is active. It replaced your previous coach workout plan.",
    receivePdf: "Receive your plan as a PDF in the app",
    implementWhenReady: "Implement it on your calendar when ready",
    requestInProgress: "Request in progress.",
    proposalRejected:
      "Your proposal was not accepted. Your payment will be refunded.",
    awaitingApproval: "Awaiting trainer approval.",
    trainerBuilding: "Your trainer is building your plan.",
    planDelivered: "Your plan is ready to review.",
    planImplemented: "Plan is on your calendar.",
  },
  ai: {
    askAlex: "Ask Alex",
    aiCoach: "AI Coach",
    aiInsight: "AI Insight",
    upgrade: "Upgrade",
    proteinGap: (g: number) => `Protein gap today: ~${g}g remaining`,
    starterPrompts: [
      "How am I doing today?",
      "Show my weekly report",
      "What should I eat for dinner?",
      "Show my weight trend",
      "Build me a workout plan for this week",
    ],
    thinking: "Thinking…",
    searching: "Searching & thinking…",
    placeholder: "What you want?",
    imageOnlyPrompt: "What can you tell me about this image?",
    medicalDisclaimer:
      "I can't give medical advice. For that consult with a doctor, not me.",
    readMeButton: "Read me",
    readMeTitle: "Before you chat with me",
    readMeBody: [
      "I'm sarcastic and direct. I'll call out excuses, roast bad habits, and push you hard — that's the point.",
      "I may swear or use strong language when I'm fired up. It's coach energy, not a personal attack.",
      "I'm not a doctor. For injuries, pain, meds, or anything medical, I can only suggest general fitness and nutrition ideas — always confirm with your doctor.",
      "No diagnoses, prescriptions, or medical guarantees from me. When in doubt, talk to a professional, not this chat.",
    ],
    readMeGotIt: "I understand — let's talk",
    readMeAgreeLabel: "I have read this and agree",
    readMeRequiredPlaceholder: "Read and accept before chatting…",
    chatUnreachable: "Could not reach AI Coach",
    noStream: "No response stream",
    requestFailed: "AI request failed",
    sources: (n: number) => `${n} source${n === 1 ? "" : "s"}`,
    buildPlan: "Build your plan",
    flowProfile: "Profile",
    flowAiBuilds: "AI builds",
    flowApply: "Apply",
    startChatting: "Start chatting",
    today: "Today",
    weeklyScores: "Weekly scores",
    logMealsAi: "Log meals with AI",
    flowPhoto: "Photo / text",
    flowEstimate: "AI estimates",
    flowConfirm: "Confirm",
    goDashboard: "Go to dashboard",
    fullReport: "Full report →",
    logMealsForRings: "Log meals to see macro rings",
    workoutsThisWeek: "Workouts this week",
    daysTracked: "Days tracked",
    training: "Training",
    nutrition: "Nutrition",
    consistency: "Consistency",
    cal: "Cal",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    askCoach: "Ask coach",
    mealIdeas: "Meal ideas",
    tips: "Tips",
    progress: "Progress",
    logMealsGuidance: "Log meals to get personalized guidance.",
  },
  aiUpgrade: {
    unlockFeature: "Upgrade to AI Pro to unlock this feature",
    viewAiPlan: "View AI Pro plan",
    aiWorkoutPlan: "AI workout plan",
    aiNutritionPlan: "AI nutrition plan",
    photoLog: "Photo log",
    textLog: "Text log",
    aiChat: "AI fitness chat",
  },
  eliteUpgrade: {
    unlockFeature: "Upgrade to Elite for live classes, challenges, and community access",
    viewElitePlan: "View Elite plan",
    liveClasses: "Live classes",
    challenges: "Challenges",
    community: "Community",
    exclusive: "Exclusive content",
  },
  checkoutFlow: {
    title: "Let's go",
    back: "Not ready yet?",
    steps: ["Your plan", "Almost in", "Lock it in"],
    total: "Your commitment",
    summaryTitle: "What you're getting",
    summarySubtitle:
      "Alex pulled this together — take a quick look before you commit.",
    finalizeTitle: "Last step",
    finalizeSubtitle: "Secure your spot. Then we actually train.",
    planLabel: "Plan",
    priceLabel: "Investment",
    billingMonthly: "Monthly",
    billingAnnual: "Annual",
    includes: "You're unlocking",
    secureBadge: "Locked & secure",
    cardsBadge: "Card or wallet — your call",
    preparing: "Getting your spot ready…",
    primaryCta: "I'm in — let's start",
    pokPaySubmitLabel: "Starting Transformation",
    checkoutErrorTitle: "Hmm. That didn't work.",
    tryAgain: "Try again",
    processorNote: "Handled securely by PokPay.",
    completePurchase: "Ready to train for real?",
    orderLabel: "Your request",
    whatNextTitle: "What happens next",
    whatNext1: "Confirmation lands right after you lock in.",
    whatNext2: "Your request shows up on your dashboard.",
    customSuccessTitle: "Request locked in",
    customSuccessWait: (trainer: string) =>
      `Waiting on ${trainer} to green-light your proposal. If it doesn't fly, you're covered.`,
    backToWorkout: "Back to workout",
    backToNutrition: "Back to nutrition",
  },
  mealPlan: {
    noMealsScheduled: "No meals scheduled for this day.",
    noMealDetails: "No details added for this meal yet.",
    option: (n: number) => `Option ${n}`,
    ingredients: "Ingredients",
    howToCook: "How to cook",
  },
  calendar: {
    fullCalendar: "Full calendar",
  },
  pricing: {
    step: "Step 3 — Pick a package",
    choosePlan: "Choose your plan",
    onboardingBlurb: "Start with structured tracking or unlock AI coaching — subscribe now or explore first.",
    upgradeBlurb:
      "Three tiers built to grow with you — from structured tracking to AI coaching and elite community access.",
    monthly: "Monthly",
    annual: "Annual",
    perMonth: "mo",
    perYear: "yr",
    currentPlan: "Current plan",
    switchPlan: "Switch plan",
    subscribe: "Let's go",
    savePerYear: (amount: string) => `Save ${amount}/year`,
    includesFrom: (planName: string) => `Everything in ${planName}, plus:`,
  },
  checkout: {
    paymentFailed: "That didn't go through. Try again — Alex isn't going anywhere.",
    missingOrder: "Something's missing on our end. Contact support if you're stuck.",
    paymentUnconfirmed:
      "Couldn't confirm you're in yet. If something charged, contact support.",
    continueToPayment: "I'm in — let's start",
    confirming: "Setting up your account…",
    successTitle: "You're in. Now we work.",
    successBody:
      "Full access unlocked. Log workouts, meals, habits — Alex is watching.",
    errorTitle: "Almost there",
    goDashboard: "Hit the dashboard",
    backPricing: "Pick another plan",
  },
  bmi: {
    title: "BMI",
    whatIsBmi: "What is BMI?",
    bodyMassIndex: "Body Mass Index (BMI)",
    helpText:
      "A rough estimate of body fat from height and weight. It does not account for muscle mass or body composition.",
    addHeightWeight: "Add your height and weight to see your BMI.",
    addHeight: "Add your height in profile to calculate BMI.",
    logWeight: "Log your weight to calculate BMI.",
    updateProfile: "Update profile",
    underweight: "Underweight",
    normal: "Normal",
    overweight: "Overweight",
    obese: "Obese",
  },
  mealLog: {
    logMeal: "Log meal",
    logAMeal: "Log a meal",
    newMeal: "New meal",
    fromLibrary: "Recipe book",
    typeMeal: "Type meal",
    photoLog: "Photo log",
    typeIt: "Type it",
    typeItDesc: "Describe what you ate — AI estimates macros",
    photoDesc: "Snap a photo — AI fills in the details",
    fromLibraryDesc: "Browse 13k recipes or pick a saved meal",
    nameRequired: "Meal name is required",
    goBack: "Go back",
    chooseImage: "Please choose an image file",
    processFailed: "Could not process that photo. Try another image.",
    takePhotoFirst: "Take or choose a photo first",
    readFailed: "Could not read the photo",
    uploadTooLarge:
      "Upload failed — the photo may be too large. Try again or use a smaller image.",
    mealPreview: "Meal preview",
    takePhoto: "Take photo",
    addMealPhoto: "Add meal photo",
    changePhoto: "Change photo",
    mealName: "Meal name",
    doneAdjusting: "Done adjusting",
    adjustDetails: "Adjust meal details",
    retakePhoto: "Retake photo",
    descriptionNotes: "Description or notes",
    removeIngredient: "Remove ingredient",
    whatToEatToday: "What to eat today",
  },
  subscriptionPlans: {
    basic: {
      name: "RUTINA Basic",
      tagline:
        "Perfect for users who want structured workouts, nutrition plans, and progress tracking.",
      features: [
        "Personalized workout plans",
        "Nutrition plans",
        "Manual meal logging",
        "Weight tracking",
        "Body measurements",
        "Progress photos",
        "Workout history",
        "Progress statistics",
        "Daily streak tracking",
        "Basic achievements",
        "Exercise library",
        "Unlimited workout logging",
      ],
    },
    aiPro: {
      name: "RUTINA AI Pro",
      tagline:
        "Everything in Basic, plus your own AI fitness coach that adapts to your progress.",
      badge: "Most Popular",
      includesFrom: "RUTINA Basic",
      features: [
        "AI Fitness Coach",
        "AI Nutrition Coach",
        "AI Workout Generator",
        "AI Meal Suggestions",
        "AI Progress Reports",
        "AI Daily Motivation",
        "AI Fitness Chat",
        "Personalized recommendations",
        "Automatic workout adjustments",
        "Automatic calorie and macro recommendations",
        "AI recovery and performance insights",
      ],
    },
    elite: {
      name: "RUTINA Elite",
      tagline:
        "The complete fitness experience with coaching, community, and live events.",
      includesFrom: "RUTINA AI Pro",
      features: [
        "Live training classes",
        "Community challenges",
        "Monthly transformation challenges",
        "Cash prize competitions (prize pool depends on participation)",
        "Weekly group coaching calls",
        "Leaderboards",
        "Exclusive workouts",
        "Exclusive educational content",
        "Early access to new features",
        "Priority support",
        "Elite community access",
      ],
    },
  },
  classes: {
    comingSoon: "Coming Soon.",
    upgradeDescription:
      "Upgrade to Elite to join live training classes, community challenges, and group coaching.",
    upgradeDescriptionShort:
      "Upgrade to Elite for live classes, challenges, and community access.",
  },
  challenges: {
    rulesTitle: "Challenge rules",
    rulesButton: "Challenge rules",
    rulesAndInstructionsButton: "Rules and instructions",
    share: {
      button: "Share",
      copied: "Link copied!",
      message: "Join the {title} challenge on RUTINA!",
      fallbackPrompt: "Copy this challenge link:",
    },
    rulesAndInstructionsTitle: "Rules and instructions",
    rulesTab: "Rules",
    instructionsTab: "Instructions",
    backToChallenge: "Back to challenge",
    rulesClose: "Back to challenge",
    rulesIntro:
      "A {count}-month transformation tournament. Elite membership required. Registration is free — the prize pool is display-only and paid manually to the champion.",
    rules: [
      "Elite membership is required to register. Challenge entry is free on top of your subscription.",
      "The prize pool grows with each entrant (€X × participants). It is display-only — no in-app payment. The organizer pays the champion manually offline.",
      "Log workouts, meals, weight, and habits honestly throughout the tournament. Your data powers AI weekly reports.",
      "AI weekly reports help coaches prepare but do not decide winners alone — reports can be gamed.",
      "Do not cheat the platform (fake logs, rushed check-offs). Dishonest entries may be disqualified.",
      "Round 1 Zoom — groups of about {groupSize}, one call per hour. Eliminate 5, advance 5 per group.",
      "Round 2 Zoom — survivors regrouped into new groups of {groupSize}. One winner per group advances.",
      "Champion final — all group winners on one Zoom call. Live vote for best transformation.",
      "Zoom is the verification layer — on camera everyone sees real change, not just app numbers.",
      "The champion wins the full displayed prize pool, sent manually by the organizer (no in-app cashout).",
    ],
    instructionsIntro:
      "Step-by-step guide for the {count}-month tournament — what to do before, during, and after each elimination Zoom.",
    instructions: [
      "Register on the challenge page (Elite membership required). Entry is free — the prize pool is display-only.",
      "Throughout the tournament, log workouts, meals, weight, and habits in the app every day. Consistency matters for AI weekly reports.",
      "Check your AI weekly reports under AI Coach — they help you and the coach prepare, but Zoom is where results are verified.",
      "Before each elimination day, open the challenge page for your group number and scheduled Zoom hour (one group per hour).",
      "Round 1 Zoom: join on camera with your group of ~{groupSize}. Be ready to show your transformation. Five advance, five are eliminated.",
      "If you advance to Round 2, you will be placed in a new group of ~{groupSize}. One winner per group goes to the champion final.",
      "Champion final: all group winners meet on one Zoom call. Everyone votes live for the best overall transformation.",
      "The champion receives the full displayed prize pool, paid manually by the organizer — there is no in-app cashout.",
    ],
    tournamentTitle: "{count}-month elimination tournament",
    tournamentIntro:
      "Runs up to {count} months with three elimination Zoom days: Round 1 cuts 10→5 per group, Round 2 picks one winner per group, then a champion final.",
    tournamentDuration: "{count}-month tournament",
    tournamentMonthlyRound: "Three elimination Zoom days across the tournament",
    phase1Title: "Round 1 · Semi-elimination",
    phase1Body:
      "Groups of {groupSize} on hourly Zoom calls. Eliminate 5, advance 5 per group (~half the field).",
    phase2Title: "Round 2 · Group finals",
    phase2Body:
      "Survivors shuffled into fresh groups of {groupSize}. One winner per group goes to the final.",
    phase3Title: "Champion final",
    phase3Body:
      "All group winners on one Zoom call. Live vote — best overall transformation wins the prize pool.",
    selectionPlatformTitle: "Platform reports (prep only)",
    selectionPlatformBody:
      "AI weekly reports summarize training, nutrition, habits, and weight. Coaches use them to prepare — Zoom confirms the truth.",
    selectionZoomTitle: "Live Zoom (decisive)",
    selectionZoomBody:
      "Each elimination day, groups compare transformations on camera and vote. Admin records results after each call.",
    bracketTitle: "Tournament bracket",
    bracketEmpty: "No participants yet. Elite members register from the challenge page.",
    bracketGroupsPending:
      "Waiting for groups of {groupSize} to be drawn before the first elimination day.",
    bracketIntro:
      "Round 1: {groupSize} per group, 5 advance · Round 2: regroup, 1 winner per group · Final: one champion.",
    zoomRound1Intro:
      "Round 1 — up to {groupSize} people. Live on camera: eliminate 5, advance 5. Platform reports help prep; Zoom verifies.",
    zoomRound2Intro:
      "Round 2 — up to {groupSize} people. Pick one group winner to reach the champion final.",
    zoomFinalIntro:
      "Champion final — all group winners vote live for the best transformation. Winner takes the displayed prize pool.",
    zoomRegisterHint:
      "Register (Elite) to get your group Zoom link when brackets are drawn.",
    zoomPendingHint:
      "You are registered. Your group and hourly Zoom slot appear once brackets are set.",
    diagramFlowTitle: "How the {count}-month tournament works",
    diagramAdvanceCount: "{count} advance",
    diagramOneWinner: "1 winner",
    diagramPerGroup: "per group of {groupSize}",
    diagramChampionWins: "One champion · full prize pool",
    diagramFunnelTitle: "Field narrows each round",
    diagramFunnelSubtitle: "Example with 100 entrants",
    diagramFunnelStart: "{count} entrants",
    diagramFunnelR1: "{count} after Round 1",
    diagramFunnelR2: "{count} finalists",
    diagramFunnelChampion: "1 champion",
    diagramFunnelNote:
      "Each Round 1 group of {groupSize} eliminates half (~{half} advance). Round 2 picks one winner per group.",
    diagramPrepOnly: "Preparation only",
    diagramDecisive: "Decisive · on camera",
    diagramPlatformBullets: [
      "Workouts, meals, weight & habits",
      "AI weekly report scores",
      "Helps coaches prepare for Zoom",
    ],
    diagramZoomBullets: [
      "Groups of ~10, one call per hour",
      "Live transformation on camera",
      "Group vote + coach oversight",
    ],
    diagramRulesEliteTitle: "Elite + free entry",
    diagramRulesEliteBody: "Elite membership required. Challenge registration adds you to the prize pool display only.",
    diagramRulesPrizeTitle: "Prize pool",
    diagramRulesPrizeBody: "Grows with each entrant (display only). Champion paid manually offline — no in-app cashout.",
    diagramRulesZoomTitle: "Zoom verifies",
    diagramRulesZoomBody: "Three elimination days across {count} months. Platform logs help prep; Zoom confirms who advances.",
    detailStatStart: "Start date",
    detailStatDuration: "Duration",
    detailStatGroupSize: "Group size",
    detailStatRegistered: "Registered",
    detailPhaseTitle: "Tournament timeline",
    detailPhaseRegistration: "Registration & logging",
    detailPhaseRound1: "Round 1 · Semi-elimination",
    detailPhaseRound2: "Round 2 · Group finals",
    detailPhaseFinal: "Champion final",
    detailPhaseComplete: "Champion crowned",
    detailPhaseCurrent: "Current",
    detailPhaseDateTbd: "Date TBD",
    diagramFunnelSubtitleDynamic: "Based on {count} current entrants",
    detailFullRulesHint: "Full rules, step-by-step guide, and detailed diagrams",
    detailFieldTitle: "Field snapshot",
    detailFieldRegistered: "{count} registered",
    detailFieldGroups: "~{count} Round 1 groups of {groupSize}",
    detailFieldEmpty: "No entrants yet — be the first to register",
    detailFieldProjectionTitle: "Projected bracket sizes",
    detailFieldProjectionNote: "If brackets were drawn today",
    detailZoomScheduleTitle: "Elimination Zoom dates",
    detailZoomRound1Short: "Round 1",
    detailZoomRound2Short: "Round 2",
    detailZoomFinalShort: "Champion final",
    announcementsTitle: "Announcements",
    announcementsFromAdmin: "From {name} (admin)",
    announcementsLiveBadge: "Live update",
    announcementsEmpty: "No announcements yet — check back for updates from the organizer.",
    prizePool: {
      grandPrize: "Grand prize pool",
      winUpTo: "Win up to {pool}",
      maxPrizeLabel: "Win up to",
      compactWinUpTo: "Up to {pool}",
      championTakesAll: "Champion receives the full pool — paid manually by the organizer.",
      perEntry: "Per entrant",
      perParticipant: "+{amount} × {count} participants · month {month} of pool",
      participants: "{count} registered",
      growsWithSignups: "Grows with every signup",
      monthlyPoolGrowth: "+€10 per participant added to the pool each month",
      monthlyPoolGrowthActive:
        "Month {month} · +{amount} × {count} participants in the pool",
      doublesMonthly: "+€10 per participant added to the pool each month",
      doublesMonthlyActive:
        "Month {month} · +{amount} × {count} participants in the pool",
      flashPoolNote: "€5 per entrant to the pool",
      flashCatch: "Up to {pool}",
      flashCatchWindow: "in 24 hours",
      entryFee: "Entry fee",
      compactPool: "{pool} prize pool",
    },
    flash: {
      intro: "Quick head-to-head — finish within 24 hours, film your attempt, and the best score wins the pool.",
      steps: [
        "Pay the entry fee to the organizer (display-only in app — no in-app checkout).",
        "Record your attempt on video with the full movement visible.",
        "Submit before the 24-hour window closes — longest time or most reps wins.",
        "Winner receives the full prize pool, paid manually offline.",
      ],
      windowLabel: "Window",
      entryLabel: "Entry fee",
      poolLabel: "Prize pool",
      participantsLabel: "Participants",
      startsNotice: "This challenge starts on {datetime}.",
      zoomCallTitle: "Zoom call",
      zoomFromAnnouncement: "Schedule from the organizer announcement above.",
      zoomPending: "Zoom call details will be posted in the announcement above.",
      joinZoomButton: "Join Zoom call",
      zoomLinkPending: "Zoom link coming soon",
      zoomGroupsTitle: "Participant groups",
      zoomGroupsSection: "Zoom · {count} groups × ~{groupSize}",
      zoomGroupLabel: "Zoom",
      zoomGroupsEmpty: "No participants yet — register to join a Zoom group.",
      zoomGroupsPending:
        "Waiting for groups of {groupSize} to be drawn — one Zoom call per hour.",
      winnerLabel: "Winner",
    },
    catalog: {
      longTag: "Long",
      longTitle: "Long challenges",
      longSubtitle:
        "30 days to 12 months — 100 spots each, waitlist when full, +€10 per participant to the pool each month.",
      flashTag: "Flash",
      flashTitle: "Flash challenges",
      flashSubtitle:
        "Up to €250 in 24 hours — entry fee, 50 spots max.",
      viewChallenge: "View challenge",
    },
    join: {
      registerFree: "Register (Elite · free)",
      registerWithFee: "Join · {fee} entry",
      joinWaitlist: "Join waitlist (Elite · free)",
      switchToThis: "Switch to this challenge",
      joining: "Joining…",
      leaving: "Leaving…",
      leaveChallenge: "Leave challenge",
      leaveWaitlist: "Leave waitlist",
      leavingWaitlist: "Leaving waitlist…",
      registeredHere: "You are registered for this challenge.",
      waitlistJoined: "You are on the waitlist — we will add you when a spot opens.",
      successRegistered: "You are registered!",
      challengeFull: "All 100 spots are taken — join the waitlist to get in line.",
      flashChallengeFull: "All 50 spots are taken — join the waitlist to get in line.",
      spotsRemaining: "{remaining} of {max} spots left",
      waitlistPosition: "Waitlist position #{position} — first in line gets the next open spot.",
      switchNotice:
        "You are in {title}. Joining here will leave that challenge and move you here (or onto its waitlist if full).",
      viewCurrent: "View current challenge",
      registrationOpensAt: "Registration opens {date}.",
      registrationJoinWhenLive: "You can join when the challenge starts on {date}.",
      registrationClosedAt: "Registration is closed for this challenge.",
      registrationClosedRegistered: "You are registered. Leaving is no longer allowed.",
    },
  },
  aiPages: {
    goalProgress: "Goal progress",
    predictionsTitle: "AI progress predictions",
    mealSuggestionsTitle: "AI meal suggestions",
    reportsTitle: "AI weekly reports",
    trainMoreOften: "Train more often",
    trainMoreOftenBody: "You logged fewer workouts than usual. Aim for at least 3 this week.",
    solidTrainingWeek: "Solid training week",
    solidTrainingWeekBody: "Good volume — keep progressive overload in mind.",
    boostProtein: "Boost protein",
    boostProteinBody: "Your average protein is below target. Add a protein source to each meal.",
    trackMoreDays: "Track more days",
    trackMoreDaysBody: "Log meals and workouts more consistently for better insights.",
    dailyHabits: "Daily habits",
    dailyHabitsBody: "Small daily wins build long-term consistency.",
    greatWeek: "Great week!",
    greatWeekBody: "Keep protein steady and maintain your workout schedule.",
    workouts: "Workouts",
    mealsTracked: "Meals tracked",
    avgProtein: "Avg protein",
  },
} as const;
