/** Neutral platform UI copy (English). */

export const platformCopyEn = {
  nav: {
    home: "Home",
    programs: "Programs",
    aiCoach: "AI Coach",
    liveCoaching: "Live coaching",
    live: "Live",
    profile: "Profile",
    welcome: (name: string) => `Welcome, ${name}`,
    theme: "Theme",
  },
  trainTabs: {
    workout: "Workout",
    nutrition: "Nutrition",
  },
  profile: {
    title: "Profile",
    subtitle: "Account · subscription · health profile",
    healthProfile: "Health profile",
    complete: "Complete",
    inProgress: "In progress",
    incomplete: "Incomplete",
    account: "Account",
    plan: "Plan",
    manageAccount: "Manage your account and preferences",
    personalInfo: "Personal info",
    appearance: "Appearance",
    password: "Password",
    referrals: "Referrals",
  },
  referrals: {
    title: "Refer friends, earn Premium",
    subtitle: "Share your link — friends must buy the €19/mo AI plan to count",
    yourLink: "Your referral link",
    copyLink: "Copy link",
    copied: "Copied!",
    successfulReferrals: "Successful referrals",
    pendingReferrals: "Pending",
    founderBadge: "Founder",
    rewardsTitle: "Reward tiers",
    referralsColumn: "Successful referrals",
    rewardColumn: "Reward",
    howItWorksTitle: "How it works",
    howItWorks: [
      "Share your personal link with friends",
      "They sign up and purchase the €19/month AI plan",
      "You unlock Premium time and badges at each milestone",
    ],
    nextMilestone: (count: number, remaining: number) =>
      `${remaining} more to reach ${count} referrals`,
    allMilestonesUnlocked: "You've unlocked every milestone — legendary.",
    viewProgram: "View referral program",
    unlocked: "Unlocked",
    nextReward: "Next",
    locked: "Locked",
    atReferrals: (count: number) => `At ${count} successful referrals`,
    previousReward: "Previous reward",
    nextRewardNav: "Next reward",
    activatePackagesTitle: "Activate a package",
    activatePackagesHint:
      "Only the €19/month AI plan counts. Friends must sign up with your link, then purchase that plan.",
    activateAi: "Activate AI — €19/mo",
    upgradeAi: "Upgrade to AI — €19/mo",
    viewAllPlans: "Compare all plans",
    currentPlanLabel: "Current plan",
    yourPackages: "Your subscription",
    inviteFriends: "Invite friends",
    inviteFriendAi: "Invite friend — AI €19/mo",
    qualifyingPlanNote: "Annual billing does not count toward referrals.",
    back: "Back",
    milestoneRewards: [
      { count: 1, label: "1 month Premium" },
      { count: 3, label: "2 months Premium" },
      { count: 5, label: "3 months Premium" },
      { count: 10, label: "6 months Premium" },
      { count: 15, label: "1 year Premium" },
      { count: 25, label: "Lifetime Premium + Founder badge" },
    ],
  },
  subscription: {
    title: "Subscription & plans",
    active: "Active",
    accessUntil: (date: string) => `Access until ${date}, then back to free preview`,
    renewsExpires: (date: string) => `Renews / expires ${date}`,
  },
  settings: {
    fullName: "Full name",
    email: "Email",
    phone: "Phone number",
    fitnessGoal: "Fitness goal",
    language: "Language",
    units: "Units",
    metric: "EU / Metric (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    metricToggle: "kg / cm",
    imperialToggle: "lb / ft",
    theme: "Theme",
    accentColor: "Accent color",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated",
    updatePassword: "Update password",
    updating: "Updating...",
    passwordUpdated: "Password updated",
  },
  goals: {
    none: "No goal set",
    lose_weight: "Lose weight",
    build_muscle: "Build muscle",
    stay_fit: "Stay fit",
    improve_endurance: "Improve endurance",
    general_health: "General health",
  },
  dashboard: {
    nutrition: "Nutrition",
    todaysWorkout: "Today's Workout",
    tomorrowsWorkout: "Tomorrow's Workout",
    workoutOnDay: (day: string) => `${day}'s Workout`,
    todaysCardio: "Today's Cardio",
    tomorrowsCardio: "Tomorrow's Cardio",
    cardioOnDay: (day: string) => `${day}'s Cardio`,
    todaysMealPlan: "Today's meal plan",
    mealPlanOnDay: (date: string) => `Meal plan · ${date}`,
    toDoOnDay: (day: string) => `${day}'s To Do`,
    toDoToday: "Today's To Do",
    toDoTomorrow: "Tomorrow's To Do",
  },
  common: {
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    edit: "Edit",
    add: "Add",
    done: "Done",
    close: "Close",
    next: "Next",
    update: "Update",
    choose: "Choose",
    saving: "Saving…",
    loading: "Loading…",
    current: "Current",
    scheduled: "scheduled",
    active: "active",
    completed: "Completed",
    incomplete: "Incomplete",
    inProgress: "In progress",
    skipped: (n: number) => `${n} skipped`,
    min: (n: number) => `${n} min`,
    sessions: (n: number) => `${n} session${n === 1 ? "" : "s"}`,
    folders: (n: number) => `${n} folder${n === 1 ? "" : "s"}`,
    programs: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    dayMenus: (n: number) => `${n} day menu${n === 1 ? "" : "s"}`,
    exercises: (n: number) => `${n} exercise${n === 1 ? "" : "s"}`,
    completedCount: (done: number, total: number) => `${done}/${total} completed`,
    doneForDate: (done: number, total: number, date: string) =>
      `${done}/${total} done for ${date}`,
    today: "today",
    surrendering: "Surrendering…",
  },
  aria: {
    completed: "Completed",
    close: "Close",
    collapseTasks: "Collapse tasks",
    expandTasks: "Expand tasks",
    viewMealPlan: "View meal plan",
    logMeal: "Log meal",
    logWeight: "Log weight",
    addHabit: "Add habit",
    dismissSuggestion: "Dismiss suggestion",
    editHabit: "Edit habit",
    removeHabit: "Remove habit",
    sendMessage: "Send message",
    webSources: (n: number) => `${n} web sources`,
    deleteItem: (name: string) => `Delete ${name}`,
    deleteMeal: "Delete meal",
    removePhoto: (pose: string) => `Remove ${pose} photo`,
    earlierMonth: "Earlier month",
    laterMonth: "Later month",
    mealInsights: (name: string) => `View insights for ${name}`,
    removeMeal: (name: string) => `Remove ${name}`,
  },
  nutrition: {
    mealsLogged: "Meals logged",
    recentlyLogged: "Recently logged",
    logFirstMealHint: "Tap + to log your first meal",
    waterGoalReached: "Water goal reached",
    aiCoachPlan: "AI Coach plan",
    yourMealPlan: "Your meal plan",
    coachPdfPending: "Coach PDF plan · pending",
    coachNutritionPdf: "Coach nutrition plan · PDF",
    mealPlanEmpty:
      "No meal plan for this day yet. Build one in Programs → Nutrition or with AI Coach.",
    coachPdfEmpty:
      "Your coach PDF plan is still being prepared. Create or activate a personal or AI meal plan under Programs → Nutrition, or log meals with +.",
    drinkWater: (ml: number) => `Drink ${ml.toLocaleString()} ml`,
    waterLogged: (logged: number, goal: number, deadline: string) =>
      `${logged.toLocaleString()} ml logged · goal by ${deadline}`,
    eatBetween: (window: string) => `Eat between ${window}`,
    options: (n: number) => `${n} option${n === 1 ? "" : "s"}`,
    moreOptions: (n: number) => `+${n} more`,
    ate: "Ate",
    windowClosed: "Window closed",
    title: "Nutrition",
    foldersMeta: (folders: number, menus: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${menus} day menu${menus === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowDayMenu: "Day menu",
    flowSchedule: "Schedule",
    mealsTile: "Meals",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    folderNamePlaceholder: "Folder name",
    newFolder: "New folder",
    dayMenu: "day menu",
    dayMenus: "day menus",
    scheduleOnCalendar: "Schedule on calendar",
    scheduleDescription:
      "Pick a start date and repeat days. Scheduled menus appear on your dashboard calendar.",
    start: "Start",
    repeatOn: "Repeat on",
    weeks: "Weeks",
    alsoAddDates: "Also add specific dates",
    currentlyScheduled: (n: number) =>
      `Currently scheduled: ${n} day${n === 1 ? "" : "s"}`,
    saveSchedule: "Save schedule",
    scheduleCleared: "Schedule cleared.",
    scheduleUpdated: (n: number) => `Scheduled ${n} day${n === 1 ? "" : "s"}.`,
    scheduleRemoved: "Upcoming days removed.",
  },
  meals: {
    title: "Meals",
    addMeal: "Add meal",
    addToFolder: "Add to folder",
    editMeal: "Edit meal",
    newMeal: "New meal",
    chooseFolder: "Choose folder",
    choosePlan: "Choose plan",
    chooseFolderPlaceholder: "Choose a folder…",
    addCopyHint: "Add a copy of this meal to a folder or plan.",
    loadingPlans: "Loading plans…",
    newMealPlanIn: (folder: string) => `+ New meal plan in ${folder}`,
    whichFolder: "Which folder should this meal go in?",
    backTo: (name: string) => `← Back to ${name}`,
    nameRequired: "Meal name is required",
    noMealsOfType: (type: string) => `No ${type} meals found.`,
  },
  workout: {
    title: "Workouts",
    fallbackTitle: "Workout",
    stillInGym: "Still in the gym",
    hideVideo: "Hide video",
    preview: "Preview",
    setsTarget: (n: number) => `${n} sets target`,
    repsTarget: (n: string | number) => `${n} reps target`,
    set: "Set",
    reps: "Reps",
    weightKg: "Weight (kg)",
    addSet: "Add set",
    addExercise: "Add exercise",
    exerciseName: "Exercise name",
    exercisePlaceholder: "e.g. Cable flyes",
    noteOptional: "Note (optional)",
    notePlaceholder: "e.g. Felt strong today, increased weight on bench press…",
    finishNote:
      "Add an optional note about how it went — or skip and save.",
    saveWithNote: "Save with note",
    finishWorkout: "Finish workout",
    finishWithoutNote: "Finish without note",
    lastSets: (parts: string) => `Last: ${parts}`,
    scheduledWorkout: "Scheduled workout",
    completedSuffix: "· completed",
    completeBy: (deadline: string) => `· complete by ${deadline}`,
    foldersMeta: (folders: number, programs: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${programs} program${programs === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowProgram: "Program",
    flowSchedule: "Schedule",
    cardioTile: "Cardio",
    allTile: "All",
    exercisesTile: "Exercises",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    foldersNav: "Folders",
    programsCount: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    daysBadge: (n: number) => `${n}d`,
    exBadge: (n: number) => `${n} ex`,
    scheduledBadge: (n: number) => `${n} scheduled`,
    myCardio: "My cardio",
    addScheduleCardio: "Add & schedule cardio",
    whenToStart: "When to start",
    workoutDay: "Workout day",
    repeatDays: "Repeat on these days",
    repeatWeeks: "Repeat for how many weeks?",
    startNow: "Start right now",
    startNextMonday: "Next week (Monday)",
    saveDaysFirst: "Save at least one workout day before scheduling.",
    upcomingSessions: (n: number) =>
      `${n} upcoming session${n === 1 ? "" : "s"} scheduled. Changes replace future sessions only.`,
    scheduleUpdated: "Schedule updated.",
    scheduleSaved: (n: number) => `Scheduled ${n} session${n === 1 ? "" : "s"}.`,
    sessionsRemoved: "Upcoming sessions removed.",
    saveSchedule: "Save schedule",
    workout: "workout",
    workouts: "workouts",
  },
  cardio: {
    title: "Cardio",
    addCardio: "Add cardio",
    emptyTitle: "No cardio saved yet",
    emptyHint:
      "Add a session with a YouTube follow-along, then schedule it on your calendar.",
    openYoutube: "Open on YouTube",
    schedule: "Schedule",
  },
  habits: {
    title: "Daily habits",
    suggestedFromProfile: "Suggested from your health profile",
    inProgressSection: "In progress",
    completedSection: "Completed",
    done: "Done",
  },
  weight: {
    title: "Body weight",
    subtitle: "Track your weight over time",
    loggedForDate: (kg: string, date: string) => `${kg} logged for ${date}`,
    weightForDate: (date: string) => `Weight for ${date} (kg)`,
    placeholder: "e.g. 75.5",
    logWeight: "Log weight",
    invalidWeight: "Enter a valid weight",
  },
  photos: {
    title: "Progress photos",
    monthComplete: "This month complete",
    description:
      "Upload front, back & side each month. Compare over time in your history.",
    uploading: "Uploading…",
    addPhoto: "Add photo",
    addPosePhoto: (pose: string) => `Add ${pose} photo`,
    replace: "Replace",
    previousMonths: "Previous months",
    noPhoto: "No photo",
    compressHint: "Photos are compressed before upload to save space.",
    removeFailed: "Could not remove photo",
    uploadFailed: "Upload failed",
  },
  trainer: {
    customWorkout: "Custom workout plan",
    customNutrition: "Custom nutrition plan",
    byTrainer: (name: string) => `by ${name}`,
    oneTime: "one-time",
    ready: "Ready",
    pdfReady: "PDF ready",
    yourPreferences: "Your preferences",
    preferencesPlaceholder:
      "Your goals, experience level, schedule, injuries, food preferences…",
    close: "Close",
    done: "Done",
    continuePayment: "Continue to payment",
    implementing: "Implementing…",
    implementIt: "Implement it",
    implemented: "Implemented",
    viewPlan: "View plan",
    implementedConfirmed: "Implemented & confirmed",
    onCalendar: "On your calendar",
    nutritionImplemented:
      "Your new nutrition plan is on your calendar. Previous meals were replaced with your coach schedule.",
    workoutImplemented:
      "Your new workout plan is active. It replaced your previous coach workout plan.",
    receivePdf: "Receive your plan as a PDF in the app",
    implementWhenReady: "Implement it on your calendar when ready",
    requestInProgress: "Request in progress.",
    proposalRejected:
      "Your proposal was not accepted. Your payment will be refunded.",
    awaitingApproval: "Awaiting trainer approval.",
    trainerBuilding: "Your trainer is building your plan.",
    planDelivered: "Your plan is ready to review.",
    planImplemented: "Plan is on your calendar.",
  },
  ai: {
    askAlex: "Ask Alex",
    aiCoach: "AI Coach",
    aiInsight: "AI Insight",
    upgrade: "Upgrade",
    proteinGap: (g: number) => `Protein gap today: ~${g}g remaining`,
    starterPrompts: [
      "How should I structure my weekly workouts?",
      "What should I eat after training?",
      "How can I hit my protein goal?",
      "Tips for staying consistent?",
    ],
    thinking: "Thinking…",
    searching: "Searching & thinking…",
    placeholder: "Ask about workouts, nutrition, recovery…",
    medicalDisclaimer:
      "I can't give medical advice. For that consult with a doctor, not me.",
    chatUnreachable: "Could not reach AI Coach",
    noStream: "No response stream",
    requestFailed: "AI request failed",
    sources: (n: number) => `${n} source${n === 1 ? "" : "s"}`,
    buildPlan: "Build your plan",
    flowProfile: "Profile",
    flowAiBuilds: "AI builds",
    flowApply: "Apply",
    startChatting: "Start chatting",
    today: "Today",
    weeklyScores: "Weekly scores",
    logMealsAi: "Log meals with AI",
    flowPhoto: "Photo / text",
    flowEstimate: "AI estimates",
    flowConfirm: "Confirm",
    goDashboard: "Go to dashboard",
    fullReport: "Full report →",
    logMealsForRings: "Log meals to see macro rings",
    workoutsThisWeek: "Workouts this week",
    daysTracked: "Days tracked",
    training: "Training",
    nutrition: "Nutrition",
    consistency: "Consistency",
    cal: "Cal",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    askCoach: "Ask coach",
    mealIdeas: "Meal ideas",
    tips: "Tips",
    progress: "Progress",
    logMealsGuidance: "Log meals to get personalized guidance.",
  },
  aiUpgrade: {
    unlockFeature: "Upgrade to the AI plan to unlock this feature",
    viewAiPlan: "View AI plan",
    aiWorkoutPlan: "AI workout plan",
    aiNutritionPlan: "AI nutrition plan",
    photoLog: "Photo log",
    textLog: "Text log",
    liveSessions: "Live sessions",
  },
  checkoutFlow: {
    completePurchase: "Complete your purchase",
  },
  mealPlan: {
    noMealsScheduled: "No meals scheduled for this day.",
    noMealDetails: "No details added for this meal yet.",
    option: (n: number) => `Option ${n}`,
    ingredients: "Ingredients",
    howToCook: "How to cook",
  },
  calendar: {
    fullCalendar: "Full calendar",
  },
  pricing: {
    step: "Step 3 — Pick a package",
    choosePlan: "Subscribe",
    onboardingBlurb: "Subscribe now or skip and explore your dashboard first.",
    upgradeBlurb:
      "One plan — full tracking, AI coaching, plan builders, photo logging & live sessions.",
    monthly: "Monthly",
    annual: "Annual",
    perMonth: "mo",
    perYear: "yr",
    currentPlan: "Current plan",
    switchPlan: "Switch plan",
    subscribe: "Subscribe",
    savePerYear: (amount: string) => `Save ${amount}/year`,
    liveRateNote: (eurPrice: string, allPerEur: number) =>
      `Prices in ALL — equivalent to ${eurPrice}/mo at 1 EUR = ${allPerEur.toFixed(2)} ALL (live rate)`,
  },
  checkout: {
    paymentFailed: "Payment failed. Please try again.",
    missingOrder: "Missing order reference.",
    paymentUnconfirmed:
      "We could not confirm your payment yet. If you were charged, contact support.",
  },
  bmi: {
    title: "BMI",
    whatIsBmi: "What is BMI?",
    bodyMassIndex: "Body Mass Index (BMI)",
    helpText:
      "A rough estimate of body fat from height and weight. It does not account for muscle mass or body composition.",
    addHeightWeight: "Add your height and weight to see your BMI.",
    addHeight: "Add your height in profile to calculate BMI.",
    logWeight: "Log your weight to calculate BMI.",
    updateProfile: "Update profile",
    underweight: "Underweight",
    normal: "Normal",
    overweight: "Overweight",
    obese: "Obese",
  },
  mealLog: {
    logMeal: "Log meal",
    logAMeal: "Log a meal",
    newMeal: "New meal",
    fromLibrary: "Recipe book",
    typeMeal: "Type meal",
    photoLog: "Photo log",
    typeIt: "Type it",
    typeItDesc: "Describe what you ate — AI estimates macros",
    photoDesc: "Snap a photo — AI fills in the details",
    fromLibraryDesc: "Browse 13k recipes or pick a saved meal",
    nameRequired: "Meal name is required",
    goBack: "Go back",
    chooseImage: "Please choose an image file",
    processFailed: "Could not process that photo. Try another image.",
    takePhotoFirst: "Take or choose a photo first",
    readFailed: "Could not read the photo",
    uploadTooLarge:
      "Upload failed — the photo may be too large. Try again or use a smaller image.",
    mealPreview: "Meal preview",
    takePhoto: "Take photo",
    addMealPhoto: "Add meal photo",
    changePhoto: "Change photo",
    mealName: "Meal name",
    doneAdjusting: "Done adjusting",
    adjustDetails: "Adjust meal details",
    retakePhoto: "Retake photo",
    descriptionNotes: "Description or notes",
    removeIngredient: "Remove ingredient",
    whatToEatToday: "What to eat today",
  },
  subscriptionPlans: {
    aiTagline:
      "Full training & nutrition tracking, AI coaching, plan builders, and live sessions.",
    bestValue: "All-in-one",
    aiFeatures: [
      "Workout builder & sessions",
      "Nutrition plans & meal logging",
      "AI Coach Alex — motivation, help & answers",
      "AI workout & nutrition plan builders",
      "Photo & text AI meal logging",
      "Live coaching sessions + replays",
      "Water, habits, cardio & progress tracking",
    ],
  },
  classes: {
    upgradeDescription:
      "Upgrade to the AI plan to join live coaching sessions and watch replays anytime.",
    upgradeDescriptionShort:
      "Upgrade to the AI plan to join live coaching sessions and watch replays.",
  },
  aiPages: {
    goalProgress: "Goal progress",
    predictionsTitle: "AI progress predictions",
    mealSuggestionsTitle: "AI meal suggestions",
    reportsTitle: "AI weekly reports",
    trainMoreOften: "Train more often",
    trainMoreOftenBody: "You logged fewer workouts than usual. Aim for at least 3 this week.",
    solidTrainingWeek: "Solid training week",
    solidTrainingWeekBody: "Good volume — keep progressive overload in mind.",
    boostProtein: "Boost protein",
    boostProteinBody: "Your average protein is below target. Add a protein source to each meal.",
    trackMoreDays: "Track more days",
    trackMoreDaysBody: "Log meals and workouts more consistently for better insights.",
    dailyHabits: "Daily habits",
    dailyHabitsBody: "Small daily wins build long-term consistency.",
    greatWeek: "Great week!",
    greatWeekBody: "Keep protein steady and maintain your workout schedule.",
    workouts: "Workouts",
    mealsTracked: "Meals tracked",
    avgProtein: "Avg protein",
  },
} as const;
