/** Neutral platform UI copy (Albanian). */

export const platformCopyAl = {
  nav: {
    home: "Kryefaqja",
    programs: "Programet",
    aiCoach: "Coach AI",
    liveCoaching: "Trajnim live",
    live: "Live",
    profile: "Profili",
    welcome: (name: string) => `Mirë se vini, ${name}`,
    theme: "Tema",
  },
  trainTabs: {
    workout: "Stërvitje",
    nutrition: "Ushqimi",
  },
  profile: {
    title: "Profili",
    subtitle: "Llogaria · abonimi · profili shëndetësor",
    healthProfile: "Profili shëndetësor",
    complete: "I plotë",
    inProgress: "Në progres",
    incomplete: "I paplotë",
    account: "Llogaria",
    plan: "Plani",
    manageAccount: "Menaxhoni llogarinë dhe preferencat",
    personalInfo: "Të dhënat personale",
    appearance: "Pamja",
    password: "Fjalëkalimi",
    referrals: "Referimet",
  },
  referrals: {
    title: "Refero miqtë, fito Premium",
    subtitle: "Ndaj linkun → miku blen AI €20/muaj → fito shpërblime",
    yourLink: "Linku juaj",
    copyLink: "Kopjo",
    copied: "U kopjua!",
    successfulReferrals: "Kualifikuar",
    pendingReferrals: "Në pritje",
    founderBadge: "Themelues",
    rewardsTitle: "Progresi",
    referralsColumn: "Kualifikuar",
    rewardColumn: "Shpërblimi",
    howItWorksTitle: "Si funksionon",
    howItWorks: ["Ndaj linkun", "Miku blen AI", "Shkyç Premium"],
    nextMilestone: (count: number, remaining: number) =>
      `${remaining} të tjera → ${count}`,
    allMilestonesUnlocked: "Të gjitha milestone-t shkyçur",
    viewProgram: "Shiko programin",
    unlocked: "Komplet",
    nextReward: "Deri te tjetri",
    locked: "I kyçur",
    atReferrals: (count: number) => `${count} ref`,
    previousReward: "I mëparshmi",
    nextRewardNav: "Tjetri",
    activatePackagesTitle: "Plani juaj",
    activatePackagesHint: "Kërkohet plani AI €20/muaj",
    activateAi: "Aktivizo AI — €20/muaj",
    upgradeAi: "Përmirëso në AI",
    viewAllPlans: "Të gjitha planet",
    currentPlanLabel: "Aktiv",
    yourPackages: "Abonimi",
    inviteFriends: "Fto",
    inviteFriendAi: "Ndaj linkun e referimit",
    qualifyingPlanNote: "Faturimi vjetor përjashtohet",
    back: "Kthehu",
    milestoneRewards: [
      { count: 1, label: "1 muaj Premium" },
      { count: 3, label: "2 muaj Premium" },
      { count: 5, label: "3 muaj Premium" },
      { count: 10, label: "6 muaj Premium" },
      { count: 15, label: "1 vit Premium" },
      { count: 25, label: "Premium për jetë + badge Themelues" },
    ],
  },
  subscription: {
    title: "Abonimi dhe planet",
    active: "Aktiv",
    accessUntil: (date: string) =>
      `Akses deri më ${date}, pastaj kthehet në modalitetin falas`,
    renewsExpires: (date: string) => `Rinovohet / skadon ${date}`,
  },
  settings: {
    fullName: "Emri i plotë",
    email: "Email",
    phone: "Numri i telefonit",
    fitnessGoal: "Qëllimi i fitnesit",
    language: "Gjuha",
    units: "Njësitë",
    metric: "EU / Metrik (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    metricToggle: "kg / cm",
    imperialToggle: "lb / ft",
    theme: "Tema",
    accentColor: "Ngjyra e theksit",
    newPassword: "Fjalëkalimi i ri",
    confirmPassword: "Konfirmo fjalëkalimin",
    saveChanges: "Ruaj ndryshimet",
    saving: "Duke ruajtur...",
    profileUpdated: "Profili u përditësua",
    updatePassword: "Përditëso fjalëkalimin",
    updating: "Duke përditësuar...",
    passwordUpdated: "Fjalëkalimi u përditësua",
  },
  goals: {
    none: "Pa qëllim të caktuar",
    lose_weight: "Humb peshe",
    build_muscle: "Ndërto muskuj",
    stay_fit: "Qëndro në formë",
    improve_endurance: "Përmirëso qëndrueshmërinë",
    general_health: "Shëndet i përgjithshëm",
  },
  dashboard: {
    nutrition: "Ushqimi",
    todaysWorkout: "Stërvitja e sotme",
    tomorrowsWorkout: "Stërvitja e nesërme",
    workoutOnDay: (day: string) => `Stërvitja · ${day}`,
    todaysCardio: "Kardio e sotme",
    tomorrowsCardio: "Kardio e nesërme",
    cardioOnDay: (day: string) => `Kardio · ${day}`,
    todaysMealPlan: "Menuja e sotme",
    mealPlanOnDay: (date: string) => `Menu · ${date}`,
    toDoOnDay: (day: string) => `Detyrat · ${day}`,
    toDoToday: "Detyrat e sotme",
    toDoTomorrow: "Detyrat e nesërme",
  },
  common: {
    back: "Kthehu",
    cancel: "Anulo",
    save: "Ruaj",
    create: "Krijo",
    edit: "Ndrysho",
    add: "Shto",
    done: "Kryer",
    close: "Mbyll",
    next: "Vazhdo",
    update: "Përditëso",
    choose: "Zgjidh",
    saving: "Duke ruajtur…",
    loading: "Duke ngarkuar…",
    current: "Aktual",
    scheduled: "e planifikuar",
    active: "aktive",
    completed: "E përfunduar",
    incomplete: "E papërfunduar",
    inProgress: "Në progres",
    skipped: (n: number) => `${n} të anashkaluara`,
    min: (n: number) => `${n} min`,
    sessions: (n: number) => `${n} seancë${n === 1 ? "" : " seanca"}`,
    folders: (n: number) => `${n} dosje`,
    programs: (n: number) => `${n} program${n === 1 ? "" : "e"}`,
    dayMenus: (n: number) => `${n} menu ditore`,
    exercises: (n: number) => `${n} ushtrim${n === 1 ? "" : "e"}`,
    completedCount: (done: number, total: number) => `${done}/${total} të përfunduara`,
    doneForDate: (done: number, total: number, date: string) =>
      `${done}/${total} për ${date}`,
    today: "sot",
    surrendering: "Duke u dorëzuar…",
  },
  aria: {
    completed: "E përfunduar",
    close: "Mbyll",
    collapseTasks: "Mbyll detyrat",
    expandTasks: "Shfaq detyrat",
    viewMealPlan: "Shiko menunë",
    logMeal: "Regjistro vaktin",
    logWeight: "Regjistro peshën",
    addHabit: "Shto zakon",
    dismissSuggestion: "Hiq sugjerimin",
    editHabit: "Ndrysho zakonin",
    removeHabit: "Hiq zakonin",
    sendMessage: "Dërgo mesazhin",
    attachFile: "Bashkëngjit foto",
    removeAttachment: "Hiq bashkëngjitjen",
    webSources: (n: number) => `${n} burime në internet`,
    deleteItem: (name: string) => `Fshi ${name}`,
    deleteMeal: "Fshi vaktin",
    removePhoto: (pose: string) => `Hiq foton ${pose}`,
    earlierMonth: "Muaji i mëparshëm",
    laterMonth: "Muaji tjetër",
    mealInsights: (name: string) => `Shiko analizën për ${name}`,
    removeMeal: (name: string) => `Hiq ${name}`,
  },
  nutrition: {
    mealsLogged: "Vaktet e regjistruara",
    recentlyLogged: "Regjistruar së fundmi",
    logFirstMealHint: "Prek + për të regjistruar vaktin e parë",
    waterGoalReached: "Objektivi i ujit u arrit",
    aiCoachPlan: "Plani i Coach AI",
    yourMealPlan: "Menuja juaj",
    coachPdfPending: "Plani PDF i trajnerit · në pritje",
    coachNutritionPdf: "Plani i ushqimit nga trajneri · PDF",
    mealPlanEmpty:
      "Ende nuk ka menu për këtë ditë. Krijoni një te Programet → Ushqimi ose me Coach AI.",
    coachPdfEmpty:
      "Plani PDF i trajnerit po përgatitet. Krijoni ose aktivizoni një plan personal ose me AI te Programet → Ushqimi, ose regjistroni vakte me +.",
    drinkWater: (ml: number) => `Pini ${ml.toLocaleString()} ml ujë`,
    waterLogged: (logged: number, goal: number, deadline: string) =>
      `${logged.toLocaleString()} ml të regjistruara · objektivi deri në ${deadline}`,
    eatBetween: (window: string) => `Hani ndërmjet ${window}`,
    options: (n: number) => `${n} opsion${n === 1 ? "" : "e"}`,
    moreOptions: (n: number) => `+${n} të tjera`,
    ate: "Hëngra",
    windowClosed: "Koha mbaroi",
    title: "Ushqimi",
    foldersMeta: (folders: number, menus: number) =>
      `${folders} dosje · ${menus} menu ditore`,
    flowFolder: "Dosja",
    flowDayMenu: "Menu ditore",
    flowSchedule: "Orari",
    mealsTile: "Vaktet",
    aiPlanTile: "Plani AI",
    folderTile: "Dosje",
    folderNamePlaceholder: "Emri i dosjes",
    newFolder: "Dosje e re",
    dayMenu: "menu ditore",
    dayMenus: "menu ditore",
    scheduleOnCalendar: "Planifiko në kalendar",
    scheduleDescription:
      "Zgjidhni datën e fillimit dhe ditët e përsëritjes. Menutë e planifikuara shfaqen në kalendarin tuaj.",
    start: "Fillimi",
    repeatOn: "Përsërit në",
    weeks: "Javë",
    alsoAddDates: "Shto edhe data specifike",
    currentlyScheduled: (n: number) =>
      `Aktualisht të planifikuara: ${n} ditë`,
    saveSchedule: "Ruaj orarin",
    scheduleCleared: "Orari u pastrua.",
    scheduleUpdated: (n: number) => `U planifikuan ${n} ditë.`,
    scheduleRemoved: "Ditët e ardhshme u hoqën.",
  },
  meals: {
    title: "Vaktet",
    addMeal: "Shto vakt",
    addToFolder: "Shto në dosje",
    editMeal: "Ndrysho vaktin",
    newMeal: "Vakt i ri",
    chooseFolder: "Zgjidh dosjen",
    choosePlan: "Zgjidh planin",
    chooseFolderPlaceholder: "Zgjidh një dosje…",
    addCopyHint: "Shto një kopje të këtij vakti në një dosje ose plan.",
    loadingPlans: "Duke ngarkuar planet…",
    newMealPlanIn: (folder: string) => `+ Plan i ri vaktesh në ${folder}`,
    whichFolder: "Në cilin dosje duhet të shkojë ky vakt?",
    backTo: (name: string) => `← Kthehu te ${name}`,
    nameRequired: "Emri i vaktit është i detyrueshëm",
    noMealsOfType: (type: string) => `Nuk u gjetën vakte ${type}.`,
  },
  workout: {
    title: "Stërvitjet",
    fallbackTitle: "Stërvitje",
    stillInGym: "Ende në palestër",
    hideVideo: "Fshih videon",
    preview: "Parapamje",
    setsTarget: (n: number) => `${n} seri synim`,
    repsTarget: (n: string | number) => `${n} përsëritje synim`,
    set: "Seria",
    reps: "Përsëritje",
    weightKg: "Pesha (kg)",
    addSet: "Shto seri",
    addExercise: "Shto ushtrim",
    elapsed: "Kohë e kaluar",
    estimatedTime: "Koha e vlerësuar",
    estTotal: (duration: string) => `Përaf. ~${duration}`,
    timeRemaining: (duration: string) => `~${duration} mbeten`,
    finishSummaryTitle: "Përmbledhje seance",
    setsLogged: (done: number, total: number) => `${done}/${total} seri të regjistruara`,
    noExercisesTitle: "Nuk u ngarkuan ushtrime",
    noExercisesHint:
      "Kjo ditë stërvitjeje nuk ka ende ushtrime. Shtoni një më poshtë ose kthehuni dhe redaktoni programin.",
    exerciseName: "Emri i ushtrimit",
    exercisePlaceholder: "p.sh. Fluturime me kavo",
    noteOptional: "Shënim (opsional)",
    notePlaceholder:
      "p.sh. Ndihesha i fortë sot, rrita peshën në bench press…",
    finishNote:
      "Shtoni një shënim opsional për seancën — ose kaloni dhe ruani.",
    saveWithNote: "Ruaj me shënim",
    finishWorkout: "Përfundo stërvitjen",
    finishWithoutNote: "Përfundo pa shënim",
    lastSets: (parts: string) => `Herën e fundit: ${parts}`,
    scheduledWorkout: "Stërvitje e planifikuar",
    completedSuffix: "· e përfunduar",
    completeBy: (deadline: string) => `· përfundo deri në ${deadline}`,
    foldersMeta: (folders: number, programs: number) =>
      `${folders} dosje · ${programs} program${programs === 1 ? "" : "e"}`,
    flowFolder: "Dosja",
    flowProgram: "Programi",
    flowSchedule: "Orari",
    cardioTile: "Kardio",
    allTile: "Të gjitha",
    exercisesTile: "Ushtrimet",
    aiPlanTile: "Plani AI",
    folderTile: "Dosje",
    foldersNav: "Dosjet",
    programsCount: (n: number) => `${n} program${n === 1 ? "" : "e"}`,
    daysBadge: (n: number) => `${n} ditë`,
    exBadge: (n: number) => `${n} ushtr.`,
    scheduledBadge: (n: number) => `${n} të planifikuara`,
    myCardio: "Kardioja ime",
    addScheduleCardio: "Shto dhe planifiko kardion",
    whenToStart: "Kur të fillojë",
    workoutDay: "Dita e stërvitjes",
    repeatDays: "Përsërit në këto ditë",
    repeatWeeks: "Përsërit për sa javë?",
    startNow: "Fillo tani",
    startNextMonday: "Javën tjetër (e hëna)",
    saveDaysFirst: "Ruani të paktën një ditë stërvitjeje para planifikimit.",
    upcomingSessions: (n: number) =>
      `${n} seancë${n === 1 ? "" : " seanca"} të planifikuara. Ndryshimet zëvendësojnë vetëm seancat e ardhshme.`,
    scheduleUpdated: "Orari u përditësua.",
    scheduleSaved: (n: number) => `U planifikuan ${n} seancë${n === 1 ? "" : " seanca"}.`,
    sessionsRemoved: "Seancat e ardhshme u hoqën.",
    saveSchedule: "Ruaj orarin",
    workout: "stërvitje",
    workouts: "stërvitje",
  },
  cardio: {
    title: "Kardio",
    addCardio: "Shto kardio",
    emptyTitle: "Ende nuk keni kardio të ruajtur",
    emptyHint:
      "Shtoni një seancë me video YouTube, pastaj planifikojeni në kalendar.",
    openYoutube: "Hape në YouTube",
    schedule: "Planifiko",
  },
  habits: {
    title: "Zakonet ditore",
    suggestedFromProfile: "Sugjeruar nga profili juaj shëndetësor",
    inProgressSection: "Në progres",
    completedSection: "Të përfunduara",
    done: "Kryer",
  },
  weight: {
    title: "Pesha trupore",
    subtitle: "Ndiqni peshën tuaj me kalimin e kohës",
    loggedForDate: (kg: string, date: string) => `${kg} të regjistruara për ${date}`,
    weightForDate: (date: string) => `Pesha për ${date} (kg)`,
    placeholder: "p.sh. 75.5",
    logWeight: "Regjistro peshën",
    invalidWeight: "Vendosni një peshë të vlefshme",
  },
  photos: {
    title: "Fotot e progresit",
    monthComplete: "Muaji i plotësuar",
    description:
      "Ngarkoni foto përpara, prapa dhe anash çdo muaj. Krahasoni progresin në historik.",
    uploading: "Duke ngarkuar…",
    addPhoto: "Shto foto",
    addPosePhoto: (pose: string) => `Shto foto ${pose}`,
    replace: "Zëvendëso",
    previousMonths: "Muajt e mëparshëm",
    noPhoto: "Pa foto",
    compressHint: "Fotot kompresohen para ngarkimit për të kursyer hapësirë.",
    removeFailed: "Fotoja nuk u hoq",
    uploadFailed: "Ngarkimi dështoi",
  },
  trainer: {
    customWorkout: "Plan stërvitjeje personal",
    customNutrition: "Plan ushqimi personal",
    byTrainer: (name: string) => `nga ${name}`,
    oneTime: "një herë",
    ready: "Gati",
    pdfReady: "PDF gati",
    yourPreferences: "Preferencat tuaja",
    preferencesPlaceholder:
      "Qëllimet, niveli i përvojës, orari, lëndimet, preferencat ushqimore…",
    close: "Mbyll",
    done: "Kryer",
    continuePayment: "Vazhdo te pagesa",
    implementing: "Duke zbatuar…",
    implementIt: "Zbato planin",
    implemented: "I zbatuar",
    viewPlan: "Shiko planin",
    implementedConfirmed: "I zbatuar dhe konfirmuar",
    onCalendar: "Në kalendarin tuaj",
    nutritionImplemented:
      "Plani i ri i ushqimit është në kalendar. Vaktet e mëparshme u zëvendësuan me orarin e trajnerit.",
    workoutImplemented:
      "Plani i ri i stërvitjes është aktiv. Zëvendësoi planin e mëparshëm të trajnerit.",
    receivePdf: "Merrni planin si PDF në aplikacion",
    implementWhenReady: "Zbatojeni në kalendar kur të jeni gati",
    requestInProgress: "Kërkesa në proces.",
    proposalRejected:
      "Propozimi juaj nuk u pranua. Pagesa do të rimbursohet.",
    awaitingApproval: "Në pritje të miratimit nga trajneri.",
    trainerBuilding: "Trajneri po përgatit planin tuaj.",
    planDelivered: "Plani juaj është gati për shqyrtim.",
    planImplemented: "Plani është në kalendarin tuaj.",
  },
  ai: {
    askAlex: "Pyet Alex-in",
    aiCoach: "Coach AI",
    aiInsight: "Vëzhgim AI",
    upgrade: "Përmirëso planin",
    proteinGap: (g: number) => `Mungesë proteine sot: ~${g}g të mbetura`,
    starterPrompts: [
      "Si ta strukturoj stërvitjen javore?",
      "Çfarë të ha pas stërvitjes?",
      "Si ta arrij objektivin e proteinave?",
      "Këshilla për të qëndruar konsekuent?",
    ],
    thinking: "Duke menduar…",
    searching: "Duke kërkuar dhe menduar…",
    placeholder: "Pyet për stërvitje, ushqim, rikuperim…",
    medicalDisclaimer:
      "Nuk jap këshilla mjekësore. Për ato, konsultohu me mjekun, jo me mua.",
    readMeButton: "Lexomë",
    readMeTitle: "Para se të bisedosh me mua",
    readMeBody: [
      "Jam sarkastik dhe i drejtpërdrejtë. Do t'i godas shpëtimin, zakonet e dobëta dhe do të të shtyj fort — kjo është ideja.",
      "Mund të përdor gjuhë të fortë ose betejera kur jam i nxitur. Është energjia ime si coach, jo sulm personal.",
      "Nuk jam mjek. Për lëndime, dhimbje, medikamente ose çdo gjë mjekësore, jap vetëm sugjerime të përgjithshme për stërvitje dhe ushqim — gjithmonë konfirmo me mjekun.",
      "Pa diagnoza, pa receta, pa garanci mjekësore nga unë. Kur ke dyshime, flit me një profesionist, jo me këtë chat.",
    ],
    readMeGotIt: "E kuptova — le të bisedojmë",
    readMeAgreeLabel: "E kam lexuar dhe pajtohem",
    readMeRequiredPlaceholder: "Lexo dhe prano para se të bisedosh…",
    chatUnreachable: "Nuk u arrit Coach AI",
    noStream: "Nuk ka përgjigje nga serveri",
    requestFailed: "Kërkesa AI dështoi",
    sources: (n: number) => `${n} burim${n === 1 ? "" : "e"}`,
    buildPlan: "Ndërto planin tënd",
    flowProfile: "Profili",
    flowAiBuilds: "AI ndërton",
    flowApply: "Zbato",
    startChatting: "Fillo bisedën",
    today: "Sot",
    weeklyScores: "Rezultatet javore",
    logMealsAi: "Regjistro vakte me AI",
    flowPhoto: "Foto / tekst",
    flowEstimate: "AI vlerëson",
    flowConfirm: "Konfirmo",
    goDashboard: "Shko te paneli",
    fullReport: "Raporti i plotë →",
    logMealsForRings: "Regjistro vakte për të parë unazhat e makronutrientëve",
    workoutsThisWeek: "Stërvitje këtë javë",
    daysTracked: "Ditë të ndjekura",
    training: "Stërvitje",
    nutrition: "Ushqim",
    consistency: "Konsistencë",
    cal: "Kal",
    protein: "Proteinë",
    carbs: "Karboh.",
    fat: "Yndyrë",
    askCoach: "Pyet coach-in",
    mealIdeas: "Ide vaktesh",
    tips: "Këshilla",
    progress: "Progres",
    logMealsGuidance: "Regjistro vakte për udhëzime të personalizuara.",
  },
  aiUpgrade: {
    unlockFeature: "Përmirëso planin në AI për të hapur këtë funksion",
    viewAiPlan: "Shiko planin AI",
    aiWorkoutPlan: "Plan stërvitjeje me AI",
    aiNutritionPlan: "Plan ushqimi me AI",
    photoLog: "Regjistrim me foto",
    textLog: "Regjistrim me tekst",
    liveSessions: "Seanca live",
  },
  checkoutFlow: {
    completePurchase: "Përfundo blerjen",
  },
  mealPlan: {
    noMealsScheduled: "Nuk ka vakte të planifikuara për këtë ditë.",
    noMealDetails: "Ende nuk janë shtuar detaje për këtë vakt.",
    option: (n: number) => `Opsioni ${n}`,
    ingredients: "Përbërësit",
    howToCook: "Si të përgatitet",
  },
  calendar: {
    fullCalendar: "Kalendari i plotë",
  },
  pricing: {
    step: "Hapi 3 — Zgjidh paketën",
    choosePlan: "Abonohu",
    onboardingBlurb:
      "Abonohu tani ose kaloje dhe eksploro panelin fillimisht.",
    upgradeBlurb:
      "Një plan — ndjekje e plotë, coach AI, ndërtues planet, regjistrim me foto dhe seanca live.",
    monthly: "Mujore",
    annual: "Vjetore",
    perMonth: "muaj",
    perYear: "vit",
    currentPlan: "Plani aktual",
    switchPlan: "Ndrysho planin",
    subscribe: "Abonohu",
    savePerYear: (amount: string) => `Kurseni ${amount}/vit`,
  },
  checkout: {
    paymentFailed: "Pagesa dështoi. Provoni përsëri.",
    missingOrder: "Mungon referenca e porosisë.",
    paymentUnconfirmed:
      "Nuk mundëm të konfirmojmë pagesën. Nëse u debituat, kontaktoni mbështetjen.",
  },
  bmi: {
    title: "BMI",
    whatIsBmi: "Çfarë është BMI?",
    bodyMassIndex: "Indeksi i masës trupore (BMI)",
    helpText:
      "Një vlerësim i përafërt i yndyrës nga lartësia dhe pesha. Nuk merr parasysh masën muskulore ose përbërjen e trupit.",
    addHeightWeight: "Shtoni lartësinë dhe peshën për të parë BMI-në.",
    addHeight: "Shtoni lartësinë në profil për të llogaritur BMI-në.",
    logWeight: "Regjistroni peshën për të llogaritur BMI-në.",
    updateProfile: "Përditëso profilin",
    underweight: "Nën peshë",
    normal: "Normal",
    overweight: "Mbipeshë",
    obese: "Obezitet",
  },
  mealLog: {
    logMeal: "Regjistro vaktin",
    logAMeal: "Regjistro një vakt",
    newMeal: "Vakt i ri",
    fromLibrary: "Libri i recetave",
    typeMeal: "Shkruaj vaktin",
    photoLog: "Regjistro me foto",
    typeIt: "Shkruaje",
    typeItDesc: "Përshkruani çfarë keni ngrënë — AI vlerëson makrot",
    photoDesc: "Bëni një foto — AI plotëson detajet",
    fromLibraryDesc: "Shfletoni 13k receta ose zgjidhni një vakt të ruajtur",
    nameRequired: "Emri i vaktit është i detyrueshëm",
    goBack: "Kthehu",
    chooseImage: "Zgjidhni një skedar fotoje",
    processFailed: "Fotoja nuk u përpunua. Provoni një tjetër.",
    takePhotoFirst: "Bëni ose zgjidhni një foto fillimisht",
    readFailed: "Fotoja nuk u lexua",
    uploadTooLarge:
      "Ngarkimi dështoi — fotoja mund të jetë shumë e madhe. Provoni përsëri ose përdorni një më të vogël.",
    mealPreview: "Parapamje e vaktit",
    takePhoto: "Bëj foto",
    addMealPhoto: "Shto foto vakti",
    changePhoto: "Ndrysho foton",
    mealName: "Emri i vaktit",
    doneAdjusting: "Përshtatja u krye",
    adjustDetails: "Përshtat detajet e vaktit",
    retakePhoto: "Ribëj foton",
    descriptionNotes: "Përshkrim ose shënime",
    removeIngredient: "Hiq përbërësin",
    whatToEatToday: "Çfarë të hash sot",
  },
  subscriptionPlans: {
    aiTagline:
      "Ndjekje e plotë stërvitjeje dhe ushqimi, coach AI, ndërtues planet dhe seanca live.",
    bestValue: "Gjithçka në një",
    aiFeatures: [
      "Ndërtues stërvitjesh dhe seanca të ndjekura",
      "Bibliotekë ushtrimesh dhe dosje stërvitjeje",
      "Planet ushqimore dhe vakte të planifikuara",
      "Coach Alex me AI — motivim, ndihmë dhe përgjigje",
      "Ndërtues plani stërvitjeje me AI",
      "Ndërtues plani ushqimor me AI",
      "Regjistrim vaktesh me foto dhe tekst me AI",
      "Seanca trajnimi live + regjistrime",
      "Ndjekje uji, zakonesh dhe kardio",
      "Foto progresi, peshë dhe tendenca makronutrientesh",
      "Raporte javore me AI dhe analiza vaktesh",
    ],
  },
  classes: {
    upgradeDescription:
      "Përmirëso planin në AI për të marrë pjesë në seanca live dhe për të parë regjistrimet.",
    upgradeDescriptionShort:
      "Përmirëso planin në AI për seanca live dhe regjistrime.",
  },
  aiPages: {
    goalProgress: "Progresi i qëllimit",
    predictionsTitle: "Parashikime progresi me AI",
    mealSuggestionsTitle: "Sugjerime vaktesh me AI",
    reportsTitle: "Raporte javore me AI",
    trainMoreOften: "Stërvitu më shpesh",
    trainMoreOftenBody:
      "Keni regjistruar më pak stërvitje se zakonisht. Synoni të paktën 3 këtë javë.",
    solidTrainingWeek: "Javë e mirë stërvitjeje",
    solidTrainingWeekBody:
      "Volum i mirë — mbajeni ngarkesën progresive në mend.",
    boostProtein: "Rrit proteinat",
    boostProteinBody:
      "Mesatarja e proteinave është nën objektiv. Shtoni burim proteine në çdo vakt.",
    trackMoreDays: "Ndiq më shumë ditë",
    trackMoreDaysBody:
      "Regjistroni vakte dhe stërvitje më rregullisht për analiza më të mira.",
    dailyHabits: "Zakone ditore",
    dailyHabitsBody: "Fitoret e vogla ditore ndërtojnë konsistencë afatgjatë.",
    greatWeek: "Javë e shkëlqyer!",
    greatWeekBody: "Mbajeni proteinën të qëndrueshme dhe orarin e stërvitjes.",
    workouts: "Stërvitje",
    mealsTracked: "Vakte të ndjekura",
    avgProtein: "Proteinë mes.",
  },
} as const;
