/** Neutral platform UI copy (English). */

export const platformCopyEn = {
  nav: {
    home: "Home",
    programs: "Programs",
    aiCoach: "AI Coach",
    liveCoaching: "Live coaching",
    live: "Live",
    profile: "Profile",
    welcome: (name: string) => `Welcome, ${name}`,
    theme: "Theme",
  },
  trainTabs: {
    workout: "Workout",
    nutrition: "Nutrition",
  },
  profile: {
    title: "Profile",
    subtitle: "Account · subscription · health profile",
    healthProfile: "Health profile",
    complete: "Complete",
    inProgress: "In progress",
    incomplete: "Incomplete",
    account: "Account",
    plan: "Plan",
    manageAccount: "Manage your account and preferences",
    personalInfo: "Personal info",
    appearance: "Appearance",
    password: "Password",
  },
  referral: {
    title: "Invite friends",
    subtitle: "Share your code, earn credits, unlock flash entries",
    navAria: "Referrals",
    profileCardTitle: "Referrals",
    profileCardHint: "Invite friends and store €10 credits",
    open: "Open referrals",
    yourCode: "Your code",
    copyCode: "Copy code",
    copied: "Copied",
    shareLink: "Share link",
    balance: "Credit balance",
    earned: "Earned",
    saved: "Saved with credits",
    invites: "Successful invites",
    pendingInvites: "Pending invites",
    howItWorks: "How it works",
    flowShareTitle: "Share your code",
    flowShareDesc: "Friend signs up or checks out with it",
    flowFriendTitle: "They get €5 off",
    flowFriendDesc: "Discount on their first paid plan",
    flowYouTitle: "You get €10",
    flowYouDesc: "Credit banks when they pay",
    flowSpendTitle: "Spend credits",
    flowSpendDesc: "On your plan or a flash entry",
    ruleInvitee: "Friends who use your code get €5 off their first subscription.",
    ruleInviter: "You earn €10 credit when they pay — store it for later.",
    ruleSpend:
      "Use credits on your next subscription or to enter paid flash challenges.",
    ruleTwo: "Two invites (€20) cover a full AI Pro monthly plan.",
    enterCode: "Have a code?",
    codePlaceholder: "Enter referral code",
    applyCode: "Apply code",
    codeApplied: "Referral code applied",
    alreadyReferred: "A referral is already linked to your account.",
    invalidCode: "That referral code is not valid.",
    cannotSelfRefer: "You can’t use your own code.",
    tooLate: "Referral codes can only be added before your first paid subscription.",
    inviteeDiscount: "Friend discount",
    useCredits: "Use referral credits",
    creditsAvailable: (amount: string) => `${amount} available`,
    creditsApplied: (amount: string) => `${amount} credits applied`,
    payWithCredits: "Pay with credits",
    payRemainder: (amount: string) => `Pay ${amount}`,
    history: "Activity",
    emptyHistory: "No referral activity yet.",
    earnTx: "Referral reward — friend subscribed",
    spendTx: "Credits used on checkout",
    flashSpendTx: "Credits used for flash challenge entry",
  },
  subscription: {
    title: "Subscription & plans",
    active: "Active",
    freeTrial: "Free trial",
    freeTrialDaysLeft: (days: number) =>
      days === 1 ? "1 day left on free trial" : `${days} days left on free trial`,
    freeTrialBlurb:
      "You're on a 7-day free trial of AI Pro — workouts, nutrition, and full AI Coach. Live classes and challenges need Elite. Your card is charged when the trial ends unless you cancel.",
    trialCancelHint: "Cancel anytime from here to avoid being charged.",
    accessUntil: (date: string) => `Access until ${date}, then back to free preview`,
    renewsExpires: (date: string) => `Renews / expires ${date}`,
    trialEnds: (date: string) => `Trial ends ${date}`,
  },
  settings: {
    fullName: "Full name",
    email: "Email",
    phone: "Phone number",
    fitnessGoal: "Fitness goal",
    language: "Language",
    units: "Units",
    metric: "EU / Metric (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    metricToggle: "kg / cm",
    imperialToggle: "lb / ft",
    theme: "Theme",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    switchToDark: "Switch to dark mode",
    switchToLight: "Switch to light mode",
    accentColor: "Accent color",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated",
    updatePassword: "Update password",
    updating: "Updating...",
    passwordUpdated: "Password updated",
  },
  goals: {
    none: "No goal set",
    lose_weight: "Lose weight",
    build_muscle: "Build muscle",
    stay_fit: "Stay fit",
    improve_endurance: "Improve endurance",
    general_health: "General health",
  },
  dashboard: {
    nutrition: "Nutrition",
    todaysWorkout: "Today's Workout",
    tomorrowsWorkout: "Tomorrow's Workout",
    workoutOnDay: (day: string) => `${day}'s Workout`,
    todaysCardio: "Today's Cardio",
    tomorrowsCardio: "Tomorrow's Cardio",
    cardioOnDay: (day: string) => `${day}'s Cardio`,
    todaysMealPlan: "Today's meal plan",
    mealPlanOnDay: (date: string) => `Meal plan · ${date}`,
    toDoOnDay: (day: string) => `${day}'s To Do`,
    toDoToday: "Today's To Do",
    toDoTomorrow: "Tomorrow's To Do",
    myProgress: "My Progress",
    viewDetails: "View details",
  },
  common: {
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    edit: "Edit",
    add: "Add",
    done: "Done",
    close: "Close",
    next: "Next",
    update: "Update",
    choose: "Choose",
    saving: "Saving…",
    loading: "Loading…",
    current: "Current",
    scheduled: "scheduled",
    active: "active",
    completed: "Completed",
    incomplete: "Incomplete",
    inProgress: "In progress",
    skipped: (n: number) => `${n} skipped`,
    min: (n: number) => `${n} min`,
    sessions: (n: number) => `${n} session${n === 1 ? "" : "s"}`,
    folders: (n: number) => `${n} folder${n === 1 ? "" : "s"}`,
    programs: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    dayMenus: (n: number) => `${n} day menu${n === 1 ? "" : "s"}`,
    exercises: (n: number) => `${n} exercise${n === 1 ? "" : "s"}`,
    completedCount: (done: number, total: number) => `${done}/${total} completed`,
    doneForDate: (done: number, total: number, date: string) =>
      `${done}/${total} done for ${date}`,
    today: "today",
    surrendering: "Surrendering…",
    refreshing: "Refreshing",
    pullToRefresh: "Pull to refresh",
    loadingDay: "Loading day",
  },
  aria: {
    completed: "Completed",
    close: "Close",
    collapseTasks: "Collapse tasks",
    expandTasks: "Expand tasks",
    collapseMeals: "Collapse logged meals",
    expandMeals: "Expand logged meals",
    collapseWorkoutResults: "Collapse workout results",
    expandWorkoutResults: "Expand workout results",
    viewMealPlan: "View meal plan",
    logMeal: "Log meal",
    logWeight: "Log weight",
    addHabit: "Add habit",
    dismissSuggestion: "Dismiss suggestion",
    editHabit: "Edit habit",
    removeHabit: "Remove habit",
    sendMessage: "Send message",
    attachFile: "Attach image",
    removeAttachment: "Remove attachment",
    webSources: (n: number) => `${n} web sources`,
    deleteItem: (name: string) => `Delete ${name}`,
    deleteMeal: "Delete meal",
    removePhoto: (pose: string) => `Remove ${pose} photo`,
    viewPhoto: (pose: string) => `View ${pose} photo`,
    earlierMonth: "Earlier month",
    laterMonth: "Later month",
    mealInsights: (name: string) => `View insights for ${name}`,
    removeMeal: (name: string) => `Remove ${name}`,
  },
  nutrition: {
    mealsLogged: "Meals logged",
    recentlyLogged: "Recently logged",
    recentlyUploaded: "Recently uploaded",
    caloriesLeft: "Calories left",
    caloriesUnit: "calories",
    proteinLeft: "Protein",
    carbsLeft: "Carbs",
    fatLeft: "Fat",
    logFirstMealHint: "Tap + to log your first meal",
    waterGoalReached: "Water goal reached",
    aiCoachPlan: "AI Coach plan",
    yourMealPlan: "Your meal plan",
    coachPdfPending: "Coach PDF plan · pending",
    coachNutritionPdf: "Coach nutrition plan · PDF",
    mealPlanEmpty:
      "No meal plan for this day yet. Build one in Programs → Nutrition or with AI Coach.",
    coachPdfEmpty:
      "Your coach PDF plan is still being prepared. Create or activate a personal or AI meal plan under Programs → Nutrition, or log meals with +.",
    drinkWater: (ml: number) => `Drink ${ml.toLocaleString()} ml`,
    fiber: "Fiber",
    sugar: "Sugar",
    sodium: "Sodium",
    healthScore: "Health score",
    healthScoreInnerBefore: "health",
    healthScoreInnerAfter: "score",
    macros: "Macros",
    microNutrients: "Micro nutrients",
    water: "Water",
    logMeal: "Log meal",
    viewDietPlan: "Diet plan",
    seeWhatWentWrong: "What went wrong",
    whatWentWrongTitle: "What pushed you over",
    whatWentWrongSubtitle: "Alex checked today's logged meals",
    analyzingMeals: "Checking your logged meals…",
    problemMeal: "Problem meal",
    problemFoods: "Foods to watch",
    fromThisMeal: "from this meal",
    nextTimeLabel: "Next time",
    extraNutrient: (nutrient: string) => `Too much ${nutrient}`,
    waterLogged: (logged: number, goal: number) =>
      `${logged.toLocaleString()} / ${goal.toLocaleString()} ml`,
    eatBetween: (window: string) => `Eat between ${window}`,
    options: (n: number) => `${n} option${n === 1 ? "" : "s"}`,
    moreOptions: (n: number) => `+${n} more`,
    ate: "Ate",
    windowClosed: "Window closed",
    title: "Nutrition",
    foldersMeta: (folders: number, menus: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${menus} day menu${menus === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowDayMenu: "Day menu",
    flowSchedule: "Schedule",
    mealsTile: "Meals",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    folderNamePlaceholder: "Folder name",
    newFolder: "New folder",
    dayMenu: "day menu",
    dayMenus: "day menus",
    scheduleOnCalendar: "Schedule on calendar",
    scheduleDescription:
      "Pick a start date and repeat days. Scheduled menus appear on your dashboard calendar.",
    start: "Start",
    repeatOn: "Repeat on",
    weeks: "Weeks",
    alsoAddDates: "Also add specific dates",
    currentlyScheduled: (n: number) =>
      `Currently scheduled: ${n} day${n === 1 ? "" : "s"}`,
    saveSchedule: "Save schedule",
    scheduleCleared: "Schedule cleared.",
    scheduleUpdated: (n: number) => `Scheduled ${n} day${n === 1 ? "" : "s"}.`,
    scheduleRemoved: "Upcoming days removed.",
  },
  meals: {
    title: "Meals",
    addMeal: "Add meal",
    addToFolder: "Add to folder",
    editMeal: "Edit meal",
    newMeal: "New meal",
    chooseFolder: "Choose folder",
    choosePlan: "Choose plan",
    chooseFolderPlaceholder: "Choose a folder…",
    addCopyHint: "Add a copy of this meal to a folder or plan.",
    loadingPlans: "Loading plans…",
    newMealPlanIn: (folder: string) => `+ New meal plan in ${folder}`,
    whichFolder: "Which folder should this meal go in?",
    backTo: (name: string) => `← Back to ${name}`,
    nameRequired: "Meal name is required",
    noMealsOfType: (type: string) => `No ${type} meals found.`,
  },
  workout: {
    title: "Workouts",
    fallbackTitle: "Workout",
    stillInGym: "Still in the gym",
    readyToStart: "Ready to start",
    startWorkout: "Start workout",
    starting: "Starting…",
    stopWorkout: "Reset timer",
    stop: "Stop",
    discardWorkout: "Discard workout",
    hideVideo: "Hide video",
    preview: "Preview",
    setsTarget: (n: number) => `${n} sets target`,
    setsCount: (n: number) => `${n} set${n === 1 ? "" : "s"}`,
    repsTarget: (n: string | number) => `${n} reps target`,
    set: "Set",
    reps: "Reps",
    weightKg: "Weight (kg)",
    addSet: "Add set",
    addExercise: "Add exercise",
    elapsed: "Elapsed",
    estimatedTime: "Estimated time",
    estimatedTimeCompact: "est.",
    estTotal: (duration: string) => `Est. ~${duration}`,
    totalSetsLabel: "Total sets",
    totalSetsCompact: "sets total",
    moreExercises: (count: number) => `+${count} more exercise${count === 1 ? "" : "s"}`,
    difficultyForYou: "For you",
    difficultyExplainTitle: "Why this rating?",
    difficultyAnalyzing: "Analyzing your profile and recent results…",
    difficultyWorkoutLoad: "Workout load",
    difficultyYourCapacity: "Your capacity",
    difficultyHarderFactors: "What makes it harder",
    difficultyEasierFactors: "What's in your favor",
    difficultyBalancedProfile: "Your profile and this workout are well matched.",
    tapToSeeWhy: "Tap to see why",
    personalDifficulty: {
      easy: {
        label: "Easy",
        tagline: "You should finish comfortably.",
        summary: "This session is lighter than what your profile suggests you can handle today.",
      },
      intermediate: {
        label: "Intermediate",
        tagline: "A solid challenge.",
        summary: "This lines up with your training background and lifestyle — expect to work, not suffer.",
      },
      hard: {
        label: "Hard",
        tagline: "Respect the session.",
        summary: "Volume, recovery factors, or your profile make this a demanding day.",
      },
      impossible: {
        label: "Impossible",
        tagline: "Be smart — scale if needed.",
        summary: "On paper this outpaces what your health & lifestyle profile suggests is realistic right now.",
      },
    },
    personalDifficultyReasons: {
      beginnerExperience:
        "Beginner training level — higher volume hits harder while you're still building capacity.",
      intermediateExperience: "Intermediate training background helps you absorb this workload.",
      advancedExperience: "Advanced training history makes this volume more manageable for you.",
      lowTrainingFrequency: "You train infrequently right now, so each session feels heavier.",
      highTrainingFrequency: "You train often, so your body is used to handling more.",
      injuries: (params: { areas: string }) =>
        `Injury areas (${params.areas}) can make this session tougher or need modifications.`,
      injuryDetails: "Injury notes on your profile suggest extra caution today.",
      healthConditions: (params: { conditions: string }) =>
        `Health conditions (${params.conditions}) can raise how demanding this feels.`,
      healthDetails: "Additional health details on your profile increase the challenge.",
      medications: "Medications on your profile may affect energy and recovery.",
      medicationsConcerning: (params: { items: string }) =>
        `Prescription or clinical medications (${params.items}) may affect energy and recovery.`,
      medicationsUnknown: (params: { items: string }) =>
        `Unlisted items on your profile (${params.items}) — verify they aren't limiting recovery.`,
      performanceSupplements: (params: { items: string }) =>
        `${params.items} on your profile supports training — not a recovery limiter.`,
      benignSupplements: (params: { items: string }) =>
        `${params.items} on your profile are general supplements, not recovery concerns.`,
      consistentRecentTraining: (params: { count: string }) =>
        `${params.count} workouts in the last 7 days — your body is primed for this load.`,
      inconsistentRecentTraining: (params: { count: string }) =>
        `Only ${params.count} workout(s) in the last 7 days — less recent conditioning.`,
      consistentMealLogging: (params: { count: string }) =>
        `Meals logged ${params.count} of the last 7 days — nutrition tracking supports recovery.`,
      sparseMealLogging: "Few meals logged recently — fueling may be inconsistent.",
      strongDailyHabits: (params: { count: string }) =>
        `Daily habits completed ${params.count} of the last 7 days — strong routine.`,
      lowHydrationToday: "Water intake is low today — hydration may limit performance.",
      goodHydration: "Solid hydration recently supports this session.",
      veryYoungAge: (params: { age: string }) =>
        `Age ${params.age} — recovery and load tolerance are still developing.`,
      youngAge: (params: { age: string }) =>
        `Age ${params.age} — keep form tight and don't chase exhaustion.`,
      olderAge: (params: { age: string }) =>
        `Age ${params.age} — longer recovery may make this feel harder than the numbers suggest.`,
      seniorAge: (params: { age: string }) =>
        `Age ${params.age} — prioritize safety and consider scaling volume.`,
      lowEnergy: "Low energy in your lifestyle questionnaire makes this tougher.",
      highEnergy: "High energy levels give you more room to push today.",
      poorSleep: "Under 6h sleep raises fatigue and makes sets feel heavier.",
      goodSleep: "Solid sleep habits support recovery for this session.",
      highStress: "High stress from your profile can drain performance.",
      smoking: "Daily smoking can reduce stamina for training.",
      alcohol: "Frequent alcohol can blunt recovery and energy.",
      lowSteps: "Low daily movement outside the gym can make training feel harder.",
      activeLifestyle: (params: { activities: string }) =>
        `Active lifestyle (${params.activities}) supports your capacity.`,
      manyExercises: (params: { count: string }) =>
        `${params.count} exercises is a lot of volume in one session.`,
      manySets: (params: { count: string }) => `${params.count} total sets pushes intensity up.`,
      longDuration: (params: { minutes: string }) =>
        `~${params.minutes} min estimated — a long grind.`,
      shortSession: "Shorter session with fewer moving parts keeps this manageable.",
      incompleteProfile:
        "Complete your health & lifestyle questionnaire for a sharper personalized rating.",
    },
    difficulty: {
      easy: { label: "Easy", tagline: "Light work. Show up and move." },
      moderate: { label: "Moderate", tagline: "Real session. Stay locked in." },
      hard: { label: "Hard", tagline: "Heavy day. Earn your shower." },
      brutal: { label: "Brutal", tagline: "Beast mode. No excuses." },
      legend: { label: "Impossible", tagline: "Legend tier. Send help." },
    },
    timeRemaining: (duration: string) => `~${duration} left`,
    finishSummaryTitle: "Session summary",
    setsLogged: (done: number, total: number) => `${done}/${total} sets logged`,
    noExercisesTitle: "No exercises loaded",
    noExercisesHint:
      "This workout day has no exercises yet. Add one below or go back and edit the program.",
    exerciseName: "Exercise name",
    exercisePlaceholder: "e.g. Cable flyes",
    noteOptional: "Note (optional)",
    notePlaceholder: "e.g. Felt strong today, increased weight on bench press…",
    finishNote:
      "Add an optional note about how it went — or skip and save.",
    saveWithNote: "Save with note",
    finishWorkout: "Finish workout",
    finishWithoutNote: "Finish without note",
    lastSets: (parts: string) => `Last: ${parts}`,
    scheduledWorkout: "Scheduled workout",
    completedSuffix: "· completed",
    completeBy: (deadline: string) => `· complete by ${deadline}`,
    workoutPlan: "Workout plan",
    workoutResults: "Workout results",
    musclesTargetedToday: "Muscles targeted today",
    muscleMapFront: "Front",
    muscleMapBack: "Back",
    muscleMapMain: "Main",
    muscleMapSecond: "Second",
    muscleMapSupport: "Support",
    chooseWorkoutType: "Choose workout type",
    chooseWorkoutTypeDesc: "Fitness with sets & reps, or timed HIIT intervals.",
    fitnessWorkout: "Fitness workout",
    fitnessWorkoutDesc: "Classic training with sets, reps, and rest between sets.",
    hiitWorkout: "HIIT workout",
    hiitWorkoutDesc:
      "Timed intervals — work, rest, rounds, and cycles with a live timer.",
    addWorkout: "Add workout",
    addWorkoutToDayDesc: (day: string) =>
      `Add a session for ${day} only — it won't change your recurring schedule.`,
    addWorkoutToDayAria: "Add workout to day",
    fromLibrary: "From library",
    createNew: "Create new",
    libraryEmptyHint:
      "No workouts in your library yet — create one for this day instead.",
    removeWorkoutFromDay: "Remove workout from this day",
    removeWorkoutFromDayDesc:
      "This only removes it from today's schedule — your program stays saved.",
    removeWorkoutFromDayAria: "Remove workout from day",
    nothingScheduledToRemove: "Nothing scheduled to remove for this day.",
    changeWorkout: "Change workout",
    changeWorkoutDesc: "Pick a program, edit your schedule, or build a new one.",
    changeWorkoutAria: "Change workout",
    allWorkoutsBrowse: "All workouts",
    allWorkoutsBrowseDesc: "Browse programs and schedule a different day.",
    editSchedule: "Edit schedule",
    editScheduleDesc: "Change which days run on your calendar.",
    generateNewPlanAi: "Generate a new plan with AI.",
    buildWorkout: "Build workout",
    buildHiitWorkout: "Build HIIT workout",
    buildWorkoutDesc: "Create a fitness or HIIT program from scratch.",
    newWorkout: "New workout",
    forThisDayOnly: "For this day only",
    scheduleWorkout: "Schedule workout",
    addToDay: "Add to day",
    generateWorkout: "Generate workout",
    regenerateWorkout: "Regenerate workout",
    progressionTitle: "Progression",
    progressionVolume: "Volume",
    progressionReps: "Total reps",
    progressionWorkouts: "Workouts completed",
    progressionForm: "Training form",
    progressionTrained: "Trained",
    progressionRest: "Rest",
    progressionSkipped: "Missed",
    progressionAvgWeight: "Latest avg weight",
    progressionLastDays: "Last 2 weeks",
    progressionLoadTitle: "Workout load",
    progressionLoadVolumeHint: "Total weight × reps each session — up means harder work.",
    progressionLoadRepsHint: "Total reps each session — up means more work done.",
    progressionScoreTitle: "Progress score",
    progressionScoreHint:
      "Up when you lift heavier or do more — flat when you stay the same — fades if you stop for 5+ days.",
    progressionHeadlineNew: "Start training to see your progress",
    progressionDetailNew:
      "After a few workouts, you'll see how consistent you've been.",
    progressionHeadlineStronger: "You're getting stronger",
    progressionDetailStronger:
      "Your weights or training load have been going up. Keep it up.",
    progressionHeadlineSteady: "You're holding steady",
    progressionDetailSteady:
      "Similar weights and a solid routine — consistency counts.",
    progressionHeadlineMissed: "A few workouts were missed",
    progressionDetailMissed: (n: number) =>
      `You missed ${n} scheduled workout${n === 1 ? "" : "s"} recently. Getting back on track helps.`,
    progressionHeadlineOff: "Training dipped a bit",
    progressionDetailOff:
      "Load or consistency dropped recently. A couple solid sessions will help.",
    progressionEmpty:
      "Complete workouts to see how your training has been going.",
    progressionLatest: "Latest",
    progressionSince: (date: string) => `since ${date}`,
    progressionChartAria: "Progress score over time",
    noResultsLogged: "No sets were logged for this workout.",
    foldersMeta: (folders: number, programs: number) =>
      `${folders} folder${folders === 1 ? "" : "s"} · ${programs} program${programs === 1 ? "" : "s"}`,
    flowFolder: "Folder",
    flowProgram: "Program",
    flowSchedule: "Schedule",
    allTile: "All",
    exercisesTile: "Exercises",
    aiPlanTile: "AI plan",
    folderTile: "Folder",
    foldersNav: "Folders",
    programsCount: (n: number) => `${n} program${n === 1 ? "" : "s"}`,
    daysBadge: (n: number) => `${n}d`,
    exBadge: (n: number) => `${n} ex`,
    scheduledBadge: (n: number) => `${n} scheduled`,
    whenToStart: "When to start",
    workoutDay: "Workout day",
    repeatDays: "Repeat on these days",
    repeatWeeks: "Repeat for how many weeks?",
    startNow: "Start right now",
    startNextMonday: "Next week (Monday)",
    saveDaysFirst: "Save at least one workout day before scheduling.",
    upcomingSessions: (n: number) =>
      `${n} upcoming session${n === 1 ? "" : "s"} scheduled. Changes replace future sessions only.`,
    scheduleUpdated: "Schedule updated.",
    scheduleSaved: (n: number) => `Scheduled ${n} session${n === 1 ? "" : "s"}.`,
    sessionsRemoved: "Upcoming sessions removed.",
    saveSchedule: "Save schedule",
    workout: "workout",
    workouts: "workouts",
  },
  cardio: {
    title: "Cardio",
    addCardio: "Add cardio",
    emptyTitle: "No cardio saved yet",
    emptyHint:
      "Pick a cardio type below or add a custom session, then schedule it on your calendar.",
    openYoutube: "Open on YouTube",
    schedule: "Schedule",
    browseTitle: "Browse cardio types",
    mySessions: "My sessions",
    myCardio: "My cardio",
    addScheduleCardio: "Add & schedule cardio",
    locationGym: "Gym",
    locationOutdoor: "Outdoor",
    locationEverywhere: "Anywhere",
    startCardio: "Start",
    continueCardio: "Continue",
    startSession: "Start cardio",
    pause: "Pause",
    resume: "Resume",
    finish: "Finish",
    discardSession: "Discard session",
    stillGoing: "Cardio in progress",
    ongoing: "Ongoing",
    readyToStart: "Ready to start",
    planned: "Planned",
    elapsed: "Elapsed",
    youDid: "You did",
    finishing: "Finishing…",
    finishSummaryTitle: "Session summary",
    noCardioForDay: "No cardio scheduled for this day.",
    alreadyCompleted: "This cardio is already completed.",
    needMoreTime: (needed: string) =>
      `Keep going — need at least ${needed} more to complete (20% tolerance).`,
    tooShortToComplete: "Too short to mark complete yet.",
    types: {
      treadmill: "Treadmill",
      incline_walk: "Incline walk",
      elliptical: "Elliptical",
      stationary_bike: "Stationary bike",
      spin_bike: "Spin bike",
      rowing_machine: "Rowing machine",
      stair_climber: "Stair climber",
      assault_bike: "Assault bike",
      ski_erg: "Ski erg",
      arc_trainer: "Arc trainer",
      battle_ropes: "Battle ropes",
      sled_push: "Sled push",
      running: "Running",
      trail_running: "Trail running",
      outdoor_cycling: "Outdoor cycling",
      hiking: "Hiking",
      brisk_walking: "Brisk walking",
      swimming: "Swimming",
      open_water_swim: "Open water swim",
      rollerblading: "Rollerblading",
      kayaking: "Kayaking",
      rock_climbing: "Rock climbing",
      cross_country_ski: "Cross-country skiing",
      soccer: "Soccer",
      basketball: "Basketball",
      tennis: "Tennis",
      walking: "Walking",
      jump_rope: "Jump rope",
      hiit: "HIIT",
      dancing: "Dancing",
      jumping_jacks: "Jumping jacks",
      burpees: "Burpees",
      shadow_boxing: "Shadow boxing",
      stair_climbing: "Stair climbing",
      mountain_climbers: "Mountain climbers",
      high_knees: "High knees",
      bodyweight_circuit: "Bodyweight circuit",
      boxing: "Boxing",
      aerobics: "Aerobics",
      yoga_flow: "Yoga flow",
      pilates: "Pilates",
    },
  },
  habits: {
    title: "Daily habits",
    suggestedFromProfile: "Suggested from your health profile",
    inProgressSection: "In progress",
    completedSection: "Completed",
    done: "Done",
    addHabit: "Add habit",
    editHabit: "Edit habit",
    formHint:
      "Set name, repeat schedule, and an optional time window. Leave times empty for all-day habits.",
    habitName: "Habit name",
    habitNamePlaceholder: "e.g. Morning stretch",
    fromOptional: "From (optional)",
    untilOptional: "Until (optional)",
  },
  weight: {
    title: "Body weight",
    subtitle: "Track your weight over time",
    loggedForDate: (value: string, date: string) => `${value} logged for ${date}`,
    weightForDate: (date: string, unit: string) => `Weight for ${date} (${unit})`,
    placeholder: "e.g. 75.5",
    logWeight: "Log weight",
    invalidWeight: "Enter a valid weight",
  },
  photos: {
    title: "Progress photos",
    monthComplete: "This month complete",
    readMeButton: "Read me",
    readMeTitle: "Before you take progress photos",
    readMeBody: [
      "Take front, back & side photos each month with your camera. Gallery uploads aren't allowed — snap them live for honest progress.",
      "Only use photos of yourself — starting with your very first check-in. Alex remembers who's in your progress photos and checks it matches your profile gender.",
      "The wrong gender or a different person in later photos will be rejected.",
      "Used the wrong person on your first photo by mistake? Contact support and we can reset it.",
    ],
    readMeGotIt: "Got it",
    readMeAgreeLabel: "I have read this and agree",
    readMeRequiredHint: "Read and agree before taking photos",
    readMeSupportHint: "Wrong person on your first photo? Contact support.",
    uploading: "Uploading…",
    addPhoto: "Take photo",
    addPosePhoto: (pose: string) => `Add ${pose} photo`,
    takePosePhoto: (pose: string) => `Take ${pose} photo`,
    replace: "Replace",
    retake: "Retake",
    deletePhoto: "Delete",
    editPhoto: (pose: string) => `Edit ${pose} photo`,
    previousMonths: "Previous months",
    nextCheckIn: "Next check-in",
    noPhoto: "No photo",
    removeFailed: "Could not remove photo",
    uploadFailed: "Upload failed",
    analyzing: "Alex is checking your photo…",
    alexWrongPhotoTitle: "Wrong photo",
    retakePhoto: "Retake photo",
    alexAcceptedTitle: "Photo accepted",
    monthIncomplete: "This month incomplete",
    overdueFinish: "Overdue — finish your photos",
    dueTodayFinish: "Due today — finish your photos",
    oneDayLeft: "1 day left to finish your photos",
    daysLeft: (n: number) => `${n} days left to finish your photos`,
    nextOverdue: (due: string) => `Next photos overdue · due ${due}`,
    nextDueToday: (due: string) => `Next photos due today · ${due}`,
    nextInOneDay: (due: string) => `Next photos in 1 day · ${due}`,
    nextInDays: (n: number, due: string) => `Next photos in ${n} days · ${due}`,
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
  },
  trainer: {
    customWorkout: "Custom workout plan",
    customNutrition: "Custom nutrition plan",
    byTrainer: (name: string) => `by ${name}`,
    oneTime: "one-time",
    ready: "Ready",
    pdfReady: "PDF ready",
    yourPreferences: "Your preferences",
    preferencesPlaceholder:
      "Your goals, experience level, schedule, injuries, food preferences…",
    close: "Close",
    done: "Done",
    continuePayment: "Let's build my plan",
    submitRequest: "Submit request",
    submittingRequest: "Submitting…",
    implementing: "Implementing…",
    implementIt: "Implement it",
    implemented: "Implemented",
    viewPlan: "View plan",
    implementedConfirmed: "Implemented & confirmed",
    onCalendar: "On your calendar",
    nutritionImplemented:
      "Your new nutrition plan is on your calendar. Previous meals were replaced with your coach schedule.",
    workoutImplemented:
      "Your new workout plan is active. It replaced your previous coach workout plan.",
    receivePdf: "Receive your plan as a PDF in the app",
    implementWhenReady: "Implement it on your calendar when ready",
    requestInProgress: "Request in progress.",
    proposalRejected:
      "Your proposal was not accepted. Your payment will be refunded.",
    awaitingApproval: "Awaiting trainer approval.",
    trainerBuilding: "Your trainer is building your plan.",
    planDelivered: "Your plan is ready to review.",
    planImplemented: "Plan is on your calendar.",
  },
  ai: {
    askAlex: "Ask Alex",
    aiCoach: "AI Coach",
    aiInsight: "AI Insight",
    upgrade: "Upgrade",
    proteinGap: (g: number) => `Protein gap today: ~${g}g remaining`,
    starterPrompts: [
      "How am I doing today?",
      "Show my weekly report",
      "What should I eat for dinner?",
      "Show my weight trend",
      "Build me a workout plan for this week",
      "Analyze my progress photos",
    ],
    thinking: "Thinking…",
    searching: "Searching & thinking…",
    placeholder: "What you want?",
    imageOnlyPrompt: "What can you tell me about this image?",
    medicalDisclaimer:
      "I can't give medical advice. For that consult with a doctor, not me.",
    readMeButton: "Read me",
    readMeTitle: "Before you chat with me",
    readMeBody: [
      "I'm sarcastic and direct. I'll call out excuses, roast bad habits, and push you hard — that's the point.",
      "I may swear or use strong language when I'm fired up. It's coach energy, not a personal attack.",
      "I'm not a doctor. For injuries, pain, meds, or anything medical, I can only suggest general fitness and nutrition ideas — always confirm with your doctor.",
      "No diagnoses, prescriptions, or medical guarantees from me. When in doubt, talk to a professional, not this chat.",
    ],
    readMeGotIt: "I understand — let's talk",
    readMeAgreeLabel: "I have read this and agree",
    readMeRequiredPlaceholder: "Read and accept before chatting…",
    chatUnreachable: "Could not reach AI Coach",
    noStream: "No response stream",
    requestFailed: "AI request failed",
    sources: (n: number) => `${n} source${n === 1 ? "" : "s"}`,
    buildPlan: "Build your plan",
    buildWorkoutWithAi: "Build workout with AI",
    buildNutritionWithAi: "Build nutrition with AI",
    flowProfile: "Profile",
    flowAiBuilds: "AI builds",
    flowApply: "Apply",
    startChatting: "Start chatting",
    today: "Today",
    weeklyScores: "Weekly scores",
    logMealsAi: "Log meals with AI",
    flowPhoto: "Photo / text",
    flowEstimate: "AI estimates",
    flowConfirm: "Confirm",
    goDashboard: "Go to dashboard",
    fullReport: "Full report →",
    logMealsForRings: "Log meals to see macro rings",
    workoutsThisWeek: "Workouts this week",
    daysTracked: "Days tracked",
    training: "Training",
    nutrition: "Nutrition",
    consistency: "Consistency",
    cal: "Cal",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    askCoach: "Ask coach",
    mealIdeas: "Meal ideas",
    moreTools: "More",
    tips: "Tips",
    progress: "Progress",
    logMealsGuidance: "Log meals to get personalized guidance.",
  },
  aiUpgrade: {
    unlockFeature: "Upgrade to AI Pro to unlock this feature",
    viewAiPlan: "View AI Pro plan",
    aiWorkoutPlan: "AI workout plan",
    aiNutritionPlan: "AI nutrition plan",
    photoLog: "Photo log",
    textLog: "Text log",
    aiChat: "AI fitness chat",
  },
  eliteUpgrade: {
    unlockFeature: "Upgrade to Elite for live classes, challenges, and community access",
    viewElitePlan: "View Elite plan",
    liveClasses: "Live classes",
    challenges: "Challenges",
    community: "Community",
    exclusive: "Exclusive content",
  },
  checkoutFlow: {
    title: "Let's go",
    back: "Not ready yet?",
    steps: ["Your plan", "Almost in", "Lock it in"],
    total: "Your commitment",
    summaryTitle: "What you're getting",
    summarySubtitle:
      "Alex pulled this together — take a quick look before you commit.",
    finalizeTitle: "Last step",
    finalizeSubtitle: "Secure your spot. Then we actually train.",
    planLabel: "Plan",
    priceLabel: "Investment",
    billingMonthly: "Monthly",
    billingAnnual: "Annual",
    includes: "You're unlocking",
    secureBadge: "Locked & secure",
    cardsBadge: "Card or wallet — your call",
    preparing: "Getting your spot ready…",
    primaryCta: "I'm in — let's start",
    pokPaySubmitLabel: "Starting Transformation",
    checkoutErrorTitle: "Hmm. That didn't work.",
    tryAgain: "Try again",
    processorNote: "Handled securely by PokPay.",
    completePurchase: "Ready to train for real?",
    orderLabel: "Your request",
    whatNextTitle: "What happens next",
    whatNext1: "Confirmation lands right after you lock in.",
    whatNext2: "Your request shows up on your dashboard.",
    customSuccessTitle: "Request locked in",
    customSuccessWait: (trainer: string) =>
      `Waiting on ${trainer} to green-light your proposal. If it doesn't fly, you're covered.`,
    backToWorkout: "Back to workout",
    backToNutrition: "Back to nutrition",
  },
  mealPlan: {
    noMealsScheduled: "No meals scheduled for this day.",
    noMealDetails: "No details added for this meal yet.",
    option: (n: number) => `Option ${n}`,
    ingredients: "Ingredients",
    howToCook: "How to cook",
  },
  groceryList: {
    title: "Grocery list",
    subtitle: "One week of ingredients for your meal plan",
    empty: "Add ingredients to your meals to build a grocery list.",
    progress: (bought: number, total: number) => `${bought} of ${total} in your cart`,
    checkItem: (name: string) => `Mark ${name} as bought`,
    uncheckItem: (name: string) => `Mark ${name} as not bought`,
  },
  calendar: {
    fullCalendar: "Full calendar",
    fullCalendarTitle: "Full calendar",
    tapDayHint: "Tap a day to view its summary below",
    closeCalendar: "Close calendar",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    complete: "Complete",
    missed: "Missed",
    upcomingActive: "Upcoming / active",
    preAccount: "Pre-account",
    noActivityYet: "No activity yet (before account creation)",
    daySummary: (active: number, completed: number, missed: number) =>
      missed > 0
        ? `${active} active · ${completed} completed · ${missed} missed`
        : `${active} active · ${completed} completed`,
    dailyOverview: "Your daily overview",
    overviewFor: (date: string) => `Overview for ${date}`,
    today: "Today",
    tomorrow: "Tomorrow",
    tomorrowShort: "Tmrw",
    done: "done",
    tasksCount: (n: number) => `${n} task${n === 1 ? "" : "s"}`,
    noTasks: "No tasks",
    moreTasks: (n: number) => `+${n} more`,
    allTasksCompleted: "All tasks completed",
    tasksIncomplete: "Tasks incomplete",
    tasksCompletedAria: (done: number, total: number) =>
      `${done} of ${total} tasks completed`,
    tasksFor: (date: string) => `Tasks for ${date}`,
  },
  support: {
    needHelp: "Need help?",
    helpBlurb: "For any issue, call or message on WhatsApp.",
    call: "Call",
    whatsapp: "WhatsApp",
    contactSupport: "Contact support",
  },
  schedule: {
    startingToday: (date: string) => `Starting today (${date})`,
    startingNextWeek: (date: string) => `Starting next week (${date})`,
    selectDayAndWeek: "Select at least one day and one week.",
    selectAtLeastOneDay: "Select at least one day",
    sessionRange: (count: number, first: string, last: string) =>
      `${count} session${count === 1 ? "" : "s"} · ${first} – ${last}`,
  },
  pricing: {
    step: "Step 3 — Pick a package",
    choosePlan: "Choose your plan",
    onboardingBlurb:
      "Start a 7-day AI Pro free trial with your card (charged after the trial), subscribe now, or skip and explore first.",
    upgradeBlurb:
      "Three tiers built to grow with you — from structured tracking to AI coaching and elite community access.",
    skipForNow: "Skip for now",
    startFreeTrial: "Start 7-day free trial",
    trialCardRequired: "Add a card to start — €0 today. Cancel anytime before day 7.",
    monthly: "Monthly",
    annual: "Annual",
    perMonth: "mo",
    perYear: "yr",
    currentPlan: "Current plan",
    switchPlan: "Switch plan",
    subscribe: "Let's go",
    seeDetails: "See what's included",
    hideDetails: "Hide details",
    savePerYear: (amount: string) => `Save ${amount}/year`,
    includesFrom: (planName: string) => `Everything in ${planName}, plus:`,
  },
  checkout: {
    paymentFailed: "That didn't go through. Try again — Alex isn't going anywhere.",
    missingOrder: "Something's missing on our end. Contact support if you're stuck.",
    paymentUnconfirmed:
      "Couldn't confirm you're in yet. If something charged, contact support.",
    continueToPayment: "I'm in — let's start",
    confirming: "Setting up your account…",
    successTitle: "You're in. Now we work.",
    successBody:
      "Full access unlocked. Log workouts, meals, habits — Alex is watching.",
    errorTitle: "Almost there",
    goDashboard: "Hit the dashboard",
    backPricing: "Pick another plan",
  },
  trialCheckout: {
    title: "Start your AI Pro free trial",
    subtitle: (days: number) =>
      `Add a card to unlock ${days} days free. You won't be charged today.`,
    chargeLater: (price: string, per: string, days: number) =>
      `${price}/${per} starts after ${days} days if you don't cancel.`,
    cancelAnytime: "Cancel anytime during the trial — no charge.",
    secureBlurb: "Card details are secured by PokPay. We never store your full card number.",
    submitCard: "Start free trial",
    starting: "Starting your trial…",
    todayTotal: "€0 today",
  },
  bmi: {
    title: "BMI",
    whatIsBmi: "What is BMI?",
    bodyMassIndex: "Body Mass Index (BMI)",
    helpText:
      "A rough estimate of body fat from height and weight. It does not account for muscle mass or body composition.",
    colorMapTitle: "BMI categories",
    yourWeightIs: "Your weight is",
    basedOn: (weight: string, height: string | null) =>
      height
        ? `Based on ${weight} and ${height} height.`
        : `Based on ${weight}.`,
    lastLogged: (date: string) => `Last logged ${date}.`,
    usingIntakeWeight: "Using intake weight.",
    addHeightWeight: "Add your height and weight to see your BMI.",
    addHeight: "Add your height in profile to calculate BMI.",
    logWeight: "Log your weight to calculate BMI.",
    updateProfile: "Update profile",
    underweight: "Underweight",
    normal: "Normal",
    overweight: "Overweight",
    obese: "Obese",
  },
  mealLog: {
    logMeal: "Log meal",
    logAMeal: "Log a meal",
    newMeal: "New meal",
    fromLibrary: "Recipe book",
    typeMeal: "Type meal",
    photoLog: "Photo log",
    typeIt: "Type it",
    typeItDesc: "Describe what you ate — AI estimates macros",
    photoDesc: "Snap a photo — AI fills in the details",
    fromLibraryDesc: "Browse 13k recipes or pick a saved meal",
    nameRequired: "Meal name is required",
    goBack: "Go back",
    chooseImage: "Please choose an image file",
    processFailed: "Could not process that photo. Try another image.",
    takePhotoFirst: "Take or choose a photo first",
    readFailed: "Could not read the photo",
    uploadTooLarge:
      "Upload failed — the photo may be too large. Try again or use a smaller image.",
    mealPreview: "Meal preview",
    takePhoto: "Take photo",
    addMealPhoto: "Add meal photo",
    changePhoto: "Change photo",
    mealName: "Meal name",
    doneAdjusting: "Done adjusting",
    adjustDetails: "Adjust meal details",
    retakePhoto: "Retake photo",
    descriptionNotes: "Description or notes",
    removeIngredient: "Remove ingredient",
    whatToEatToday: "What to eat today",
    photoSavedHint: "Your photo is saved for 30 days with this meal.",
    specifyToAi: "Specify to AI",
    specifyHint:
      "Tell AI exactly what to fix: missing ingredients, different grams, updated calories, or replace the logged food.",
    specifyPlaceholder:
      "e.g. burger has onions too, change meat to 250g, set calories to 350, replace this with grilled chicken and rice…",
    refineWithAi: "Edit with AI",
    refiningMeal: "Adjusting analysis…",
    specifyTooShort: "Add a few details for AI to adjust the analysis",
  },
  mealPhotos: {
    title: "Meal photos",
    subtitle: "Photos from meals you logged with the camera.",
    retentionHint: (days: number) =>
      `Photos are kept for ${days} days, then removed. Meals stay in your log without the photo.`,
    emptyTitle: "No meal photos yet",
    emptyBody: "Log a meal with Photo log to save a snapshot here.",
    viewPhotos: "Photos",
  },
  subscriptionPlans: {
    basic: {
      name: "RUTINA Basic",
      tagline:
        "Perfect for users who want structured workouts, nutrition plans, and progress tracking.",
      features: [
        "Personalized workout plans",
        "Nutrition plans",
        "Manual meal logging",
        "Weight tracking",
        "Body measurements",
        "Progress photos",
        "Workout history",
        "Progress statistics",
        "Daily streak tracking",
        "Basic achievements",
        "Exercise library",
        "Unlimited workout logging",
      ],
    },
    aiPro: {
      name: "RUTINA AI Pro",
      tagline:
        "Everything in Basic, plus your own AI fitness coach. Start free for 7 days with a card — cancel anytime.",
      badge: "7-day free trial",
      includesFrom: "RUTINA Basic",
      features: [
        "AI Fitness Coach",
        "AI Nutrition Coach",
        "AI Workout Generator",
        "AI Meal Suggestions",
        "AI Progress Reports",
        "AI Daily Motivation",
        "AI Fitness Chat",
        "Personalized recommendations",
        "Automatic workout adjustments",
        "Automatic calorie and macro recommendations",
        "AI recovery and performance insights",
      ],
    },
    elite: {
      name: "RUTINA Elite",
      tagline:
        "The complete fitness experience with coaching, community, and live events.",
      includesFrom: "RUTINA AI Pro",
      features: [
        "Live training classes",
        "Community challenges",
        "Monthly transformation challenges",
        "Cash prize competitions (prize pool depends on participation)",
        "Weekly group coaching calls",
        "Leaderboards",
        "Exclusive workouts",
        "Exclusive educational content",
        "Early access to new features",
        "Priority support",
        "Elite community access",
      ],
    },
  },
  classes: {
    comingSoon: "Coming Soon.",
    upgradeDescription:
      "Upgrade to Elite to join live training classes, community challenges, and group coaching.",
    upgradeDescriptionShort:
      "Upgrade to Elite for live classes, challenges, and community access.",
  },
  challenges: {
    leagueTagMen: "Men's League",
    leagueTagWomen: "Women's League",
    rulesTitle: "Challenge rules",
    rulesButton: "Challenge rules",
    rulesAndInstructionsButton: "Rules and instructions",
    share: {
      button: "Share",
      copied: "Link copied!",
      message: "Join the {title} challenge on RUTINA!",
      fallbackPrompt: "Copy this challenge link:",
    },
    rulesAndInstructionsTitle: "Rules and instructions",
    rulesTab: "Rules",
    instructionsTab: "Instructions",
    backToChallenge: "Back to challenge",
    rulesClose: "Back to challenge",
    rulesIntro:
      "A {count}-month elimination tournament. Elite only. Free to register — prize pool is display-only and paid manually to the champion. Coach Alex runs a tight ship.",
    rules: [
      "Elite membership required. Challenge entry is free — you're paying with effort, not another subscription line item.",
      "Prize pool grows with each entrant (€X × participants). Display only — Alex pays the champion manually. No in-app cashout, no excuses.",
      "Log workouts, meals, weight, and habits honestly. Your platform score is 30% of every elimination. Fake logs get you booted.",
      "Winner formula at every Zoom: 30% platform score, 30% participant vote, 40% organizer vote. Cry about it on camera or train harder.",
      "Round 1 Zoom — groups of ~{groupSize}, hourly calls. Cut 5, advance 5 per group. Don't be in the bottom half.",
      "Round 2 Zoom — survivors reshuffled. One winner per group. Same formula. Fewer people, higher stakes.",
      "Champion final — all group winners, one call. Same 30/30/40 split picks who takes the pool.",
      "Zoom is the truth layer — everyone sees real change, not fantasy app numbers.",
      "Champion wins the full displayed pool. Paid offline by the organizer. Spend it wisely.",
    ],
    instructionsIntro:
      "Step-by-step for the {count}-month tournament — what to do before, during, and after each elimination Zoom. Read it or learn the hard way.",
    instructions: [
      "Register on the challenge page (Elite required). Entry is free — the prize pool is display-only.",
      "Log workouts, meals, weight, and habits daily. Platform score = 30% of every winner decision.",
      "Before each Zoom, check your platform score on the challenge page. It's a third of your fate.",
      "Before elimination day, open the challenge page for your group number and Zoom hour.",
      "Round 1: join on camera with ~{groupSize}. Show your transformation. Five advance, five go home via 30/30/40.",
      "Round 2: new groups of ~{groupSize}. One winner per group to the final. Same formula.",
      "Champion final: all group winners on one Zoom. Participants vote (30%), platform scores (30%), organizer decides (40%).",
      "Champion gets the full displayed pool — paid manually. No in-app payout.",
    ],
    tournamentTitle: "{count}-month elimination tournament",
    tournamentIntro:
      "Up to {count} months, three elimination Zoom days: Round 1 cuts 10→5 per group, Round 2 picks one per group, then a champion final. Simple. Brutal.",
    tournamentDuration: "{count}-month tournament",
    tournamentMonthlyRound: "Three elimination Zoom days across the tournament",
    phase1Title: "Round 1 · Semi-elimination",
    phase1Body:
      "Groups of {groupSize} on hourly Zoom calls. Eliminate 5, advance 5 per group (~half the field).",
    phase2Title: "Round 2 · Group finals",
    phase2Body:
      "Survivors shuffled into fresh groups of {groupSize}. One winner per group goes to the final.",
    phase3Title: "Champion final",
    phase3Body:
      "All group winners on one Zoom call. Champion chosen by 30% platform score, 30% participant vote, 40% organizer vote.",
    judgingFormulaTitle: "Winner voting formula",
    judgingFormulaIntro:
      "At every elimination Zoom and the champion final, the winner is chosen by combining three weighted inputs.",
    selectionPlatformTitle: "Overall platform score",
    selectionPlatformWeight: "30%",
    selectionPlatformBody:
      "Your overall platform score from workouts, meals, weight, habits, and AI weekly reports logged throughout the tournament.",
    selectionZoomTitle: "Participant vote on Zoom",
    selectionZoomWeight: "30%",
    selectionZoomBody:
      "Everyone on the Zoom call votes for who showed the best transformation on camera that round.",
    selectionAdminTitle: "Organizer vote",
    selectionAdminWeight: "40%",
    selectionAdminBody:
      "The challenge organizer casts the final weighted vote based on overall performance and live presentation.",
    bracketTitle: "Tournament bracket",
    leaderboardTitle: "Points leaderboard",
    leaderboardEmpty: "No participants yet. Elite members register from the challenge page.",
    leaderboardIntro:
      "Ranked by total daily points (50% nutrition · 30% workouts · 20% habits + water) — highest first.",
    leaderboardMaxPoints: "Max possible: {max} pts (100 per day logged).",
    leaderboardEndedNoChampion:
      "This challenge has ended. The champion will appear once judgment day is complete.",
    pointsUnit: "pts",
    championLabel: "Champion",
    championPrizeHint: "Prize paid manually by the organizer — no in-app cashout.",
    judgmentDayInviteLabel: "Invited to judgment day",
    judgmentZoomTitle: "Judgment day Zoom",
    judgmentZoomIntro:
      "You were invited based on your points. Join live on camera — the organizer picks the winner after the call.",
    judgmentZoomJoin: "Join Zoom",
    judgmentZoomLinkPending: "Zoom link coming soon",
    judgmentZoomPendingHint:
      "You are registered. Keep logging daily to climb the leaderboard — top scorers get invited to judgment-day Zoom.",
    bracketEmpty: "No participants yet. Elite members register from the challenge page.",
    bracketGroupsPending:
      "Waiting for groups of {groupSize} to be drawn before the first elimination day.",
    rankedByScore:
      "Ranked by platform score (50% nutrition · 30% workouts · 20% habits + water) — highest first.",
    bracketIntro:
      "Round 1: {groupSize} per group, 5 advance · Round 2: regroup, 1 winner per group · Final: one champion.",
    zoomRound1Intro:
      "Round 1 — up to {groupSize} people. Live on camera: eliminate 5, advance 5. Winner formula: 30% platform score, 30% participant vote, 40% organizer vote.",
    zoomRound2Intro:
      "Round 2 — up to {groupSize} people. Pick one group winner using the same 30/30/40 formula.",
    zoomFinalIntro:
      "Champion final — winner chosen by 30% platform score, 30% participant vote on Zoom, 40% organizer vote.",
    zoomRegisterHint:
      "Register (Elite) to get your group Zoom link when brackets are drawn.",
    zoomPendingHint:
      "You are registered. Your group and hourly Zoom slot appear once brackets are set.",
    diagramFlowTitle: "How the {count}-month tournament works",
    diagramAdvanceCount: "{count} advance",
    diagramOneWinner: "1 winner",
    diagramPerGroup: "per group of {groupSize}",
    diagramChampionWins: "One champion · full prize pool",
    diagramFunnelTitle: "Field narrows each round",
    diagramFunnelSubtitle: "Example with 100 entrants",
    diagramFunnelStart: "{count} entrants",
    diagramFunnelR1: "{count} after Round 1",
    diagramFunnelR2: "{count} finalists",
    diagramFunnelChampion: "1 champion",
    diagramFunnelNote:
      "Each Round 1 group of {groupSize} eliminates half (~{half} advance). Round 2 picks one winner per group.",
    diagramPrepOnly: "30% of winner decision",
    diagramDecisive: "30% of winner decision",
    diagramAdminWeight: "40% of winner decision",
    diagramPlatformBullets: [
      "Workouts, meals, weight & habits",
      "AI weekly report scores",
      "Ranked on the challenge bracket",
    ],
    diagramZoomBullets: [
      "Live transformation on camera",
      "Everyone on the call votes",
      "One vote per participant on Zoom",
    ],
    diagramAdminBullets: [
      "Organizer's final weighted vote",
      "Judges overall performance",
      "Largest share of the formula",
    ],
    diagramRulesEliteTitle: "Elite + free entry",
    diagramRulesEliteBody: "Elite membership required. Challenge registration adds you to the prize pool display only.",
    diagramRulesPrizeTitle: "Prize pool",
    diagramRulesPrizeBody: "Grows with each entrant (display only). Champion paid manually offline — no in-app cashout.",
    diagramRulesZoomTitle: "Zoom verifies",
    diagramRulesZoomBody: "Three elimination days across {count} months. Platform logs help prep; Zoom confirms who advances.",
    detailStatStart: "Start date",
    detailStatDuration: "Duration",
    detailStatGroupSize: "Group size",
    detailStatScoring: "Scoring",
    detailStatScoringValue: "Daily points",
    detailStatRegistered: "Registered",
    detailPhaseTitle: "Tournament timeline",
    detailPhaseRegistration: "Registration & logging",
    detailPhaseRound1: "Round 1 · Semi-elimination",
    detailPhaseRound2: "Round 2 · Group finals",
    detailPhaseFinal: "Champion final",
    detailPhaseComplete: "Champion crowned",
    detailPhaseCurrent: "Current",
    detailPhaseDateTbd: "Date TBD",
    diagramFunnelSubtitleDynamic: "Based on {count} current entrants",
    detailFullRulesHint: "Full rules, step-by-step guide, and detailed diagrams",
    detailFieldTitle: "Field snapshot",
    detailFieldRegistered: "{count} registered",
    detailFieldGroups: "~{count} Round 1 groups of {groupSize}",
    detailFieldEmpty: "No entrants yet — be the first to register",
    detailFieldProjectionTitle: "Projected bracket sizes",
    detailFieldProjectionNote: "If brackets were drawn today",
    detailZoomScheduleTitle: "Elimination Zoom dates",
    detailZoomRound1Short: "Round 1",
    detailZoomRound2Short: "Round 2",
    detailZoomFinalShort: "Champion final",
    announcementsTitle: "Announcements",
    announcementsFromAdmin: "From {name} (admin)",
    announcementsLiveBadge: "Live update",
    announcementsEmpty: "No announcements yet — check back for updates from the organizer.",
    prizePool: {
      grandPrize: "Grand prize pool",
      winUpTo: "Win up to {pool}",
      maxPrizeLabel: "Win up to",
      cardMaxPoolHint:
        "You can win up to {pool} if all {max} participants join the challenge.",
      catalogWinUpToLine: "{pool} if all {max} spots fill",
      compactWinUpTo: "Up to {pool}",
      compactMaxPoolHint: "Up to {pool} if {max} join",
      championTakesAll: "Champion receives the full pool — paid manually by the organizer.",
      perEntry: "Per entrant",
      perParticipant: "+{amount} × {count} participants · month {month} of pool",
      participants: "{count} registered",
      growsWithSignups: "Grows with every signup",
      monthlyPoolGrowth: "+€10 per participant added to the pool each month",
      monthlyPoolGrowthActive:
        "Month {month} · +{amount} × {count} participants in the pool",
      doublesMonthly: "+€10 per participant added to the pool each month",
      doublesMonthlyActive:
        "Month {month} · +{amount} × {count} participants in the pool",
      flashPoolNote: "€5 per entrant to the pool",
      flashCatch: "Up to {pool}",
      flashCatchWindow: "in 24 hours",
      entryFee: "Entry fee",
      compactPool: "{pool} prize pool",
    },
    flash: {
      intro:
        "Quick head-to-head — 24 hours once 10 people join. Film on Zoom, Alex records who actually showed up. Highest score wins the pool. No participation trophies.",
      steps: [
        "First 10 reserve a seat free. Organizer starts the 24-hour clock once at least 10 are in.",
        "Everyone in that first group pays €10 to confirm when the group fills. Skin in the game.",
        "After the first 10, new joiners pay €10 on the spot (up to 50 total).",
        "Split into Zoom groups of up to 10 when the challenge goes live.",
        "After each group Zoom, the organizer logs the winner's record — time, reps, whatever matters.",
        "Highest record among group winners takes the full prize pool. Everyone else gets a story.",
      ],
      windowLabel: "Window",
      entryLabel: "Entry fee",
      poolLabel: "Prize pool",
      participantsLabel: "Participants",
      startsNotice: "This challenge starts on {datetime}.",
      zoomCallTitle: "Zoom call",
      zoomFromAnnouncement: "Schedule from the organizer announcement above.",
      zoomPending: "Zoom call details will be posted in the announcement above.",
      joinZoomButton: "Join Zoom call",
      zoomLinkPending: "Zoom link coming soon",
      zoomGroupsTitle: "Participant groups",
      zoomGroupsSection: "Zoom · {count} groups × ~{groupSize}",
      zoomGroupLabel: "Zoom",
      zoomGroupsEmpty: "No participants yet — register to join a Zoom group.",
      zoomGroupsPending:
        "Waiting for groups of {groupSize} — drawn in join order when the organizer starts the challenge.",
      joinOrderHint: "Listed in join order — #1 signed up first.",
      fillingNotice: "{count} more sign-ups needed before the organizer can start.",
      waitingToStart: "10+ signed up — waiting for the organizer to start the 24-hour window.",
      fillingReady: "Challenge is live — 24-hour window running.",
      performanceLabel: "Record",
      winnerLabel: "Winner",
    },
    flashAlex: {
      intro:
        "Quick head-to-head — 24 hours once 10 people join. Film on Zoom, Alex records who actually showed up. Highest score wins the pool. No participation trophies.",
      steps: [
        "First 10 reserve a seat free. Organizer starts the 24-hour clock once at least 10 are in.",
        "Everyone in that first group pays €10 to confirm when the group fills. Skin in the game.",
        "After the first 10, new joiners pay €10 on the spot (up to 50 total).",
        "Split into Zoom groups of up to 10 when the challenge goes live.",
        "After each group Zoom, the organizer logs the winner's record — time, reps, whatever matters.",
        "Highest record among group winners takes the full prize pool. Everyone else gets a story.",
      ],
      windowLabel: "Window",
      entryLabel: "Entry fee",
      poolLabel: "Prize pool",
      participantsLabel: "Participants",
      startsNotice: "This challenge starts on {datetime}.",
      zoomCallTitle: "Zoom call",
      zoomFromAnnouncement: "Schedule from the organizer announcement above.",
      zoomPending: "Zoom call details will be posted in the announcement above.",
      joinZoomButton: "Join Zoom call",
      zoomLinkPending: "Zoom link coming soon",
      zoomGroupsTitle: "Participant groups",
      zoomGroupsSection: "Zoom · {count} groups × ~{groupSize}",
      zoomGroupLabel: "Zoom",
      zoomGroupsEmpty: "No participants yet — register to join a Zoom group.",
      zoomGroupsPending:
        "Waiting for groups of {groupSize} — drawn in join order when the organizer starts the challenge.",
      joinOrderHint: "Listed in join order — #1 signed up first.",
      fillingNotice: "{count} more sign-ups needed before the organizer can start.",
      waitingToStart: "10+ signed up — waiting for the organizer to start the 24-hour window.",
      fillingReady: "Challenge is live — 24-hour window running.",
      performanceLabel: "Record",
      winnerLabel: "Winner",
    },
    longMen: {},
    longWomen: {
      rulesIntro:
        "Your {count}-month transformation tournament. Elite members only — registration is free, and every signup grows the prize pool you're competing for.",
      rules: [
        "Elite membership required. Challenge entry is free on top of your subscription — you're investing in yourself.",
        "The prize pool grows with each entrant (€X × participants). Display only — the champion is paid manually by the organizer.",
        "Log workouts, meals, weight, and habits honestly. Your platform score counts for 30% of every elimination — consistency is your edge.",
        "Winner formula at every Zoom: 30% platform score, 30% participant vote, 40% organizer vote. Show up prepared and proud of your progress.",
        "Round 1 Zoom — groups of ~{groupSize}, one call per hour. Five advance, five are eliminated using the weighted formula.",
        "Round 2 Zoom — survivors meet in fresh groups of {groupSize}. One winner per group advances to the final.",
        "Champion final — all group winners on one Zoom call. The same 30/30/40 formula crowns the champion.",
        "Zoom is where your hard work becomes visible — everyone sees real change, not just numbers in the app.",
        "The champion wins the full displayed prize pool, sent manually by the organizer.",
      ],
      instructionsIntro:
        "Your step-by-step guide for the {count}-month tournament — what to do before, during, and after each elimination Zoom.",
      instructions: [
        "Register on the challenge page (Elite membership required). Entry is free — the prize pool is display-only.",
        "Throughout the tournament, log workouts, meals, weight, and habits daily. Your platform score is worth 30% of each winner decision.",
        "Before each Zoom, review your platform score on the challenge page — it's one third of how winners are chosen.",
        "Before elimination day, open the challenge page for your group number and scheduled Zoom hour.",
        "Round 1 Zoom: join on camera with your group of ~{groupSize}. Be ready to share your transformation. Five advance, five are eliminated via 30/30/40.",
        "If you advance to Round 2, you'll be placed in a new group of ~{groupSize}. One winner per group reaches the champion final.",
        "Champion final: all group winners on one Zoom call. Participants vote (30%), platform scores count (30%), organizer casts the decisive 40%.",
        "The champion receives the full displayed prize pool, paid manually by the organizer.",
      ],
      tournamentIntro:
        "Up to {count} months with three elimination Zoom days: Round 1 narrows the field, Round 2 picks group winners, then a champion final.",
      phase1Body:
        "Groups of {groupSize} on hourly Zoom calls. Five advance per group — your consistency and presence matter.",
      phase2Body:
        "Survivors reshuffled into fresh groups of {groupSize}. One winner per group earns a spot in the final.",
      phase3Body:
        "All group winners on one Zoom call. Champion chosen by 30% platform score, 30% participant vote, 40% organizer vote.",
      judgingFormulaIntro:
        "At every elimination Zoom and the champion final, the winner is chosen by combining three weighted inputs — your daily effort counts.",
      zoomRound1Intro:
        "Round 1 — up to {groupSize} people. Live on camera: five advance, five are eliminated. Formula: 30% platform score, 30% participant vote, 40% organizer vote.",
      zoomRound2Intro:
        "Round 2 — up to {groupSize} people. One group winner advances using the same 30/30/40 formula.",
      zoomFinalIntro:
        "Champion final — winner chosen by 30% platform score, 30% participant vote on Zoom, 40% organizer vote.",
      diagramRulesZoomBody:
        "Three elimination days across {count} months. Your daily logs build your score; Zoom is where you show your transformation.",
    },
    catalog: {
      longTag: "Long",
      longTitle: "Long challenges",
      longSubtitle:
        "30 days to 12 months — 100 spots each, waitlist when full, +€10 per participant to the pool each month.",
      longSubtitleMen:
        "30 days to 12 months — Men's League. 100 spots, waitlist when full, +€10 per head to the pool monthly. Don't sign up if you're not serious.",
      longSubtitleWomen:
        "30 days to 12 months — Women's League. 100 spots, waitlist when full, +€10 per participant grows the pool every month. Your transformation starts here.",
      flashTag: "Flash",
      flashTitle: "Flash challenges",
      flashSubtitle:
        "Up to €250 in 24 hours — entry fee, 50 spots max.",
      flashSubtitleAlex:
        "Up to €250 in 24 hours — show up on Zoom, beat the field, 50 spots max. Alex doesn't do second place.",
      allTag: "All",
      allSubtitle:
        "Every open challenge — long transformations and 24-hour flash events.",
      menTag: "Men",
      womenTag: "Women",
      viewChallenge: "View challenge",
    },
    join: {
      registerFree: "Register (Elite · free)",
      registerWithFee: "Join · {fee} entry",
      joinWaitlist: "Join waitlist (Elite · free)",
      switchToThis: "Switch to this challenge",
      joining: "Joining…",
      leaving: "Leaving…",
      leaveChallenge: "Leave challenge",
      leaveWaitlist: "Leave waitlist",
      leavingWaitlist: "Leaving waitlist…",
      registeredHere: "You are registered for this challenge.",
      waitlistJoined: "You are on the waitlist — we will add you when a spot opens.",
      successRegistered: "You're in. Now show up.",
      challengeFull: "All 100 spots gone — waitlist or watch from the sidelines.",
      flashChallengeFull: "All 50 spots taken — waitlist or try again next flash.",
      spotsRemaining: "{remaining} of {max} spots left",
      waitlistPosition: "Waitlist position #{position} — first in line gets the next open spot.",
      switchNotice:
        "You are in {title}. Joining here will leave that challenge and move you here (or onto its waitlist if full).",
      activeLongChallengeBlocksJoin:
        "You are in {title}. Leave that challenge or wait until it finishes before joining another long challenge.",
      reserveFreeSeat: "Reserve seat (first {count} free)",
      payEntryFee: "Pay {fee} entry fee",
      flashFirstGroupPayNotice:
        "The first group of {count} is full — pay {fee} to confirm your spot.",
      flashFillingNotice: "{count} more sign-ups needed before the organizer can start.",
      flashWaitingToStart: "10+ signed up — waiting for the organizer to start the 24-hour window.",
      flashSeatReserved:
        "Seat reserved. The first {count} join free — you will pay the entry fee once the group fills.",
      flashCheckoutTitle: "Flash challenge entry",
      flashCheckoutSummary: "Entry fee to join this flash challenge.",
      flashCheckoutNote: "Complete payment for {title} to secure your spot.",
      flashPaymentSuccessTitle: "Entry fee paid",
      flashPaymentSuccessBody: "Your spot in the flash challenge is confirmed.",
      flashPaymentSuccessCta: "Back to challenge",
      viewCurrent: "View current challenge",
      registrationOpensAt: "Registration opens {date}.",
      registrationJoinWhenLive: "You can join when the challenge starts on {date}.",
      registrationClosedAt: "Registration is closed for this challenge.",
      registrationClosedRegistered: "You are registered. Leaving is no longer allowed.",
      leaveLockedTournamentStarted:
        "The tournament has started — you can no longer leave this challenge.",
      successLeft: "You have left the challenge.",
    },
  },
  platformScore: {
    hoverTitle: "Platform score breakdown",
    hoverIntro: "Weighted from nutrition, workouts, and habits + water.",
    clickForDetails: "Click for full breakdown",
    dialogTitle: "Platform score",
    dialogDescription: "Overall {score}/100 based on how consistently they use the app.",
    dialogIntro:
      "Mostly nutrition, then workouts, then habits and water. Scores are 0–100 per area.",
    nutrition: "Nutrition",
    workout: "Workouts",
    lifestyle: "Habits + water",
    habits: "Habits",
    water: "Water",
    overall: "Overall score",
    lifestyleDetailTitle: "Lifestyle breakdown",
    openDetails: "Open platform score details ({score}/100)",
  },
  aiPages: {
    goalProgress: "Goal progress",
    predictionsTitle: "AI progress predictions",
    mealSuggestionsTitle: "AI meal suggestions",
    reportsTitle: "AI weekly reports",
    trainMoreOften: "Train more often",
    trainMoreOftenBody: "You logged fewer workouts than usual. Aim for at least 3 this week.",
    solidTrainingWeek: "Solid training week",
    solidTrainingWeekBody: "Good volume — keep progressive overload in mind.",
    boostProtein: "Boost protein",
    boostProteinBody: "Your average protein is below target. Add a protein source to each meal.",
    trackMoreDays: "Track more days",
    trackMoreDaysBody: "Log meals and workouts more consistently for better insights.",
    dailyHabits: "Daily habits",
    dailyHabitsBody: "Small daily wins build long-term consistency.",
    greatWeek: "Great week!",
    greatWeekBody: "Keep protein steady and maintain your workout schedule.",
    workouts: "Workouts",
    mealsTracked: "Meals tracked",
    avgProtein: "Avg protein",
  },
} as const;
