/** Neutral platform UI copy (Albanian). */

export const platformCopyAl = {
  nav: {
    home: "Kryefaqja",
    programs: "Programet",
    aiCoach: "Coach AI",
    liveCoaching: "Trajnim live",
    live: "Live",
    profile: "Profili",
    welcome: (name: string) => `Mirë se vini, ${name}`,
    theme: "Tema",
  },
  trainTabs: {
    workout: "Stërvitje",
    nutrition: "Ushqimi",
  },
  profile: {
    title: "Profili",
    subtitle: "Llogaria · abonimi · profili shëndetësor",
    healthProfile: "Profili shëndetësor",
    complete: "I plotë",
    inProgress: "Në progres",
    incomplete: "I paplotë",
    account: "Llogaria",
    plan: "Plani",
    manageAccount: "Menaxhoni llogarinë dhe preferencat",
    personalInfo: "Të dhënat personale",
    appearance: "Pamja",
    password: "Fjalëkalimi",
  },
  subscription: {
    title: "Abonimi dhe planet",
    active: "Aktiv",
    accessUntil: (date: string) =>
      `Akses deri më ${date}, pastaj kthehet në modalitetin falas`,
    renewsExpires: (date: string) => `Rinovohet / skadon ${date}`,
  },
  settings: {
    fullName: "Emri i plotë",
    email: "Email",
    phone: "Numri i telefonit",
    fitnessGoal: "Qëllimi i fitnesit",
    language: "Gjuha",
    units: "Njësitë",
    metric: "EU / Metrik (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    metricToggle: "kg / cm",
    imperialToggle: "lb / ft",
    theme: "Tema",
    lightMode: "Modaliteti i ndritshëm",
    darkMode: "Modaliteti i errët",
    accentColor: "Ngjyra e theksit",
    newPassword: "Fjalëkalimi i ri",
    confirmPassword: "Konfirmo fjalëkalimin",
    saveChanges: "Ruaj ndryshimet",
    saving: "Duke ruajtur...",
    profileUpdated: "Profili u përditësua",
    updatePassword: "Përditëso fjalëkalimin",
    updating: "Duke përditësuar...",
    passwordUpdated: "Fjalëkalimi u përditësua",
  },
  goals: {
    none: "Pa qëllim të caktuar",
    lose_weight: "Humb peshe",
    build_muscle: "Ndërto muskuj",
    stay_fit: "Qëndro në formë",
    improve_endurance: "Përmirëso qëndrueshmërinë",
    general_health: "Shëndet i përgjithshëm",
  },
  dashboard: {
    nutrition: "Ushqimi",
    todaysWorkout: "Stërvitja e sotme",
    tomorrowsWorkout: "Stërvitja e nesërme",
    workoutOnDay: (day: string) => `Stërvitja · ${day}`,
    todaysCardio: "Kardio e sotme",
    tomorrowsCardio: "Kardio e nesërme",
    cardioOnDay: (day: string) => `Kardio · ${day}`,
    todaysMealPlan: "Menuja e sotme",
    mealPlanOnDay: (date: string) => `Menu · ${date}`,
    toDoOnDay: (day: string) => `Detyrat · ${day}`,
    toDoToday: "Detyrat e sotme",
    toDoTomorrow: "Detyrat e nesërme",
    myProgress: "Progresi im",
    viewDetails: "Shiko detajet",
  },
  common: {
    back: "Kthehu",
    cancel: "Anulo",
    save: "Ruaj",
    create: "Krijo",
    edit: "Ndrysho",
    add: "Shto",
    done: "Kryer",
    close: "Mbyll",
    next: "Vazhdo",
    update: "Përditëso",
    choose: "Zgjidh",
    saving: "Duke ruajtur…",
    loading: "Duke ngarkuar…",
    current: "Aktual",
    scheduled: "e planifikuar",
    active: "aktive",
    completed: "E përfunduar",
    incomplete: "E papërfunduar",
    inProgress: "Në progres",
    skipped: (n: number) => `${n} të anashkaluara`,
    min: (n: number) => `${n} min`,
    sessions: (n: number) => `${n} seancë${n === 1 ? "" : " seanca"}`,
    folders: (n: number) => `${n} dosje`,
    programs: (n: number) => `${n} program${n === 1 ? "" : "e"}`,
    dayMenus: (n: number) => `${n} menu ditore`,
    exercises: (n: number) => `${n} ushtrim${n === 1 ? "" : "e"}`,
    completedCount: (done: number, total: number) => `${done}/${total} të përfunduara`,
    doneForDate: (done: number, total: number, date: string) =>
      `${done}/${total} për ${date}`,
    today: "sot",
    surrendering: "Duke u dorëzuar…",
  },
  aria: {
    completed: "E përfunduar",
    close: "Mbyll",
    collapseTasks: "Mbyll detyrat",
    expandTasks: "Shfaq detyrat",
    collapseMeals: "Mbyll vaktet e regjistruara",
    expandMeals: "Shfaq vaktet e regjistruara",
    collapseWorkoutResults: "Mbyll rezultatet e stërvitjes",
    expandWorkoutResults: "Shfaq rezultatet e stërvitjes",
    viewMealPlan: "Shiko menunë",
    logMeal: "Regjistro vaktin",
    logWeight: "Regjistro peshën",
    addHabit: "Shto zakon",
    dismissSuggestion: "Hiq sugjerimin",
    editHabit: "Ndrysho zakonin",
    removeHabit: "Hiq zakonin",
    sendMessage: "Dërgo mesazhin",
    attachFile: "Bashkëngjit foto",
    removeAttachment: "Hiq bashkëngjitjen",
    webSources: (n: number) => `${n} burime në internet`,
    deleteItem: (name: string) => `Fshi ${name}`,
    deleteMeal: "Fshi vaktin",
    removePhoto: (pose: string) => `Hiq foton ${pose}`,
    viewPhoto: (pose: string) => `Shiko foton ${pose}`,
    earlierMonth: "Muaji i mëparshëm",
    laterMonth: "Muaji tjetër",
    mealInsights: (name: string) => `Shiko analizën për ${name}`,
    removeMeal: (name: string) => `Hiq ${name}`,
  },
  nutrition: {
    mealsLogged: "Vaktet e regjistruara",
    recentlyLogged: "Regjistruar së fundmi",
    recentlyUploaded: "Ngarkuar së fundmi",
    caloriesLeft: "Kalori të mbetura",
    caloriesUnit: "kalori",
    proteinLeft: "Proteinë",
    carbsLeft: "Karbohidrate",
    fatLeft: "Yndyrë",
    logFirstMealHint: "Prek + për të regjistruar vaktin e parë",
    waterGoalReached: "Objektivi i ujit u arrit",
    aiCoachPlan: "Plani i Coach AI",
    yourMealPlan: "Menuja juaj",
    coachPdfPending: "Plani PDF i trajnerit · në pritje",
    coachNutritionPdf: "Plani i ushqimit nga trajneri · PDF",
    mealPlanEmpty:
      "Ende nuk ka menu për këtë ditë. Krijoni një te Programet → Ushqimi ose me Coach AI.",
    coachPdfEmpty:
      "Plani PDF i trajnerit po përgatitet. Krijoni ose aktivizoni një plan personal ose me AI te Programet → Ushqimi, ose regjistroni vakte me +.",
    drinkWater: (ml: number) => `Pini ${ml.toLocaleString()} ml ujë`,
    fiber: "Fibra",
    sugar: "Sheqer",
    sodium: "Natrium",
    healthScore: "Shëndeti i ditës",
    healthScoreInnerBefore: "shëndet",
    healthScoreInnerAfter: "pikë",
    macros: "Makro",
    microNutrients: "Mikro ushqyes",
    water: "Ujë",
    logMeal: "Regjistro vakt",
    viewDietPlan: "Plani ushqimor",
    waterLogged: (logged: number, goal: number, deadline: string) =>
      `${logged.toLocaleString()} ml të regjistruara · objektivi deri në ${deadline}`,
    eatBetween: (window: string) => `Hani ndërmjet ${window}`,
    options: (n: number) => `${n} opsion${n === 1 ? "" : "e"}`,
    moreOptions: (n: number) => `+${n} të tjera`,
    ate: "Hëngra",
    windowClosed: "Koha mbaroi",
    title: "Ushqimi",
    foldersMeta: (folders: number, menus: number) =>
      `${folders} dosje · ${menus} menu ditore`,
    flowFolder: "Dosja",
    flowDayMenu: "Menu ditore",
    flowSchedule: "Orari",
    mealsTile: "Vaktet",
    aiPlanTile: "Plani AI",
    folderTile: "Dosje",
    folderNamePlaceholder: "Emri i dosjes",
    newFolder: "Dosje e re",
    dayMenu: "menu ditore",
    dayMenus: "menu ditore",
    scheduleOnCalendar: "Planifiko në kalendar",
    scheduleDescription:
      "Zgjidhni datën e fillimit dhe ditët e përsëritjes. Menutë e planifikuara shfaqen në kalendarin tuaj.",
    start: "Fillimi",
    repeatOn: "Përsërit në",
    weeks: "Javë",
    alsoAddDates: "Shto edhe data specifike",
    currentlyScheduled: (n: number) =>
      `Aktualisht të planifikuara: ${n} ditë`,
    saveSchedule: "Ruaj orarin",
    scheduleCleared: "Orari u pastrua.",
    scheduleUpdated: (n: number) => `U planifikuan ${n} ditë.`,
    scheduleRemoved: "Ditët e ardhshme u hoqën.",
  },
  meals: {
    title: "Vaktet",
    addMeal: "Shto vakt",
    addToFolder: "Shto në dosje",
    editMeal: "Ndrysho vaktin",
    newMeal: "Vakt i ri",
    chooseFolder: "Zgjidh dosjen",
    choosePlan: "Zgjidh planin",
    chooseFolderPlaceholder: "Zgjidh një dosje…",
    addCopyHint: "Shto një kopje të këtij vakti në një dosje ose plan.",
    loadingPlans: "Duke ngarkuar planet…",
    newMealPlanIn: (folder: string) => `+ Plan i ri vaktesh në ${folder}`,
    whichFolder: "Në cilin dosje duhet të shkojë ky vakt?",
    backTo: (name: string) => `← Kthehu te ${name}`,
    nameRequired: "Emri i vaktit është i detyrueshëm",
    noMealsOfType: (type: string) => `Nuk u gjetën vakte ${type}.`,
  },
  workout: {
    title: "Stërvitjet",
    fallbackTitle: "Stërvitje",
    stillInGym: "Ende në palestër",
    readyToStart: "Gati për të filluar",
    startWorkout: "Fillo stërvitjen",
    starting: "Duke filluar…",
    stopWorkout: "Ndalo stërvitjen",
    stop: "Ndalo",
    hideVideo: "Fshih videon",
    preview: "Parapamje",
    setsTarget: (n: number) => `${n} seri synim`,
    setsCount: (n: number) => `${n} seri`,
    repsTarget: (n: string | number) => `${n} përsëritje synim`,
    set: "Seria",
    reps: "Përsëritje",
    weightKg: "Pesha (kg)",
    addSet: "Shto seri",
    addExercise: "Shto ushtrim",
    elapsed: "Kohë e kaluar",
    estimatedTime: "Koha e vlerësuar",
    estimatedTimeCompact: "vler.",
    estTotal: (duration: string) => `Përaf. ~${duration}`,
    totalSetsLabel: "Seri gjithsej",
    totalSetsCompact: "seri gjithsej",
    moreExercises: (count: number) =>
      `+${count} ushtrim${count === 1 ? "" : "e"} të tjera`,
    difficultyForYou: "Për ty",
    difficultyExplainTitle: "Pse ky vlerësim?",
    difficultyAnalyzing: "Duke analizuar profilin dhe rezultatet e fundit…",
    difficultyWorkoutLoad: "Ngarkesa e stërvitjes",
    difficultyYourCapacity: "Kapaciteti yt",
    difficultyHarderFactors: "Çfarë e rrit vështirësinë",
    difficultyEasierFactors: "Çfarë të favorizon",
    difficultyBalancedProfile: "Profili yt dhe kjo stërvitje përputhen mirë.",
    tapToSeeWhy: "Prek për të parë pse",
    personalDifficulty: {
      easy: {
        label: "E lehtë",
        tagline: "Duhet ta përfundosh rehat.",
        summary:
          "Kjo seancë është më e lehtë se sa sugjeron profili yt që mund ta përballosh sot.",
      },
      intermediate: {
        label: "Mesatare",
        tagline: "Sfide e mirë.",
        summary:
          "Përputhet me përvojën dhe stilin tënd të jetës — prit punë, jo vuajtje.",
      },
      hard: {
        label: "E vështirë",
        tagline: "Respekto seancën.",
        summary: "Volumi, faktoret e rikuperimit ose profili yt e bëjnë këtë ditë të rëndë.",
      },
      impossible: {
        label: "E pamundur",
        tagline: "Ji i zgjuar — ul volumin nëse duhet.",
        summary:
          "Sipas profilit tënd shëndetësor dhe të stilit të jetës, kjo tejkalon kapacitetin realistik për momentin.",
      },
    },
    personalDifficultyReasons: {
      beginnerExperience:
        "Nivel fillestar — volumi i lartë ndihet më i rëndë ndërsa po ndërton kapacitetin.",
      intermediateExperience: "Përvoja mesatare ndihmon ta përballosh këtë ngarkesë.",
      advancedExperience: "Përvoja e avancuar e bën këtë volum më të menaxhueshëm.",
      lowTrainingFrequency: "Stërvitesh rrallë, prandaj çdo seancë ndihet më e rëndë.",
      highTrainingFrequency: "Stërvitesh shpesh, trupi yt është më i mësuar me volum.",
      injuries: (params: { areas: string }) =>
        `Zonat e lëndimit (${params.areas}) mund ta rrisin vështirësinë ose kërkojnë modifikime.`,
      injuryDetails: "Shënimet e lëndimit në profil sugjerojnë kujdes shtesë sot.",
      healthConditions: (params: { conditions: string }) =>
        `Kushtet shëndetësore (${params.conditions}) mund ta rrisin ngarkesën e ndjerë.`,
      healthDetails: "Detajet shtesë shëndetësore e rrisin sfidën.",
      medications: "Medikamentet në profil mund të ndikojnë energjinë dhe rikuperimin.",
      medicationsConcerning: (params: { items: string }) =>
        `Medikamentet klinike (${params.items}) mund të ndikojnë energjinë dhe rikuperimin.`,
      medicationsUnknown: (params: { items: string }) =>
        `Artikuj të paidentifikuar (${params.items}) — verifiko nëse kufizojnë rikuperimin.`,
      performanceSupplements: (params: { items: string }) =>
        `${params.items} në profil mbështet stërvitjen — nuk është kufizues rikuperimi.`,
      benignSupplements: (params: { items: string }) =>
        `${params.items} janë suplemente të përgjithshme, jo shqetësim rikuperimi.`,
      consistentRecentTraining: (params: { count: string }) =>
        `${params.count} stërvitje në 7 ditët e fundit — trupi yt është i përgatitur për këtë ngarkesë.`,
      inconsistentRecentTraining: (params: { count: string }) =>
        `Vetëm ${params.count} stërvitje në 7 ditët e fundit — më pak kondicion i fundit.`,
      consistentMealLogging: (params: { count: string }) =>
        `Ushqimet u regjistruan ${params.count} nga 7 ditët e fundit — ndjekja e ushqimit mbështet rikuperimin.`,
      sparseMealLogging: "Pak ushqime të regjistruara së fundmi — ushqyerja mund të jetë e papërshtatshme.",
      strongDailyHabits: (params: { count: string }) =>
        `Zakonet ditore u plotësuan ${params.count} nga 7 ditët e fundit — rutinë e fortë.`,
      lowHydrationToday: "Uji sot është i ulët — hidratimi mund të kufizojë performancën.",
      goodHydration: "Hidratim i mirë së fundmi mbështet këtë seancë.",
      veryYoungAge: (params: { age: string }) =>
        `Mosha ${params.age} — toleranca ndaj ngarkesës është ende në zhvillim.`,
      youngAge: (params: { age: string }) =>
        `Mosha ${params.age} — ruaj formën dhe mos e shty deri në fund të gjithë.`,
      olderAge: (params: { age: string }) =>
        `Mosha ${params.age} — rikuperimi më i gjatë mund ta bëjë më të vështirë.`,
      seniorAge: (params: { age: string }) =>
        `Mosha ${params.age} — prioritizo sigurinë dhe konsidero uljen e volumit.`,
      lowEnergy: "Energji e ulët në anketë e bën seancën më të vështirë.",
      highEnergy: "Nivele të larta energjie të japin më shumë hapësirë për të shtyrë.",
      poorSleep: "Më pak se 6 orë gjumë rrit lodhjen dhe rëndon setet.",
      goodSleep: "Zakone të mira gjumi mbështesin rikuperimin për këtë seancë.",
      highStress: "Stresi i lartë nga profili yt mund të ulë performancën.",
      smoking: "Duhani ditor mund të ulë qëndrueshmërinë.",
      alcohol: "Alkooli i shpeshtë mund të ulë rikuperimin dhe energjinë.",
      lowSteps: "Lëvizje e pakët gjatë ditës e bën stërvitjen më të rëndë.",
      activeLifestyle: (params: { activities: string }) =>
        `Stil jetese aktiv (${params.activities}) mbështet kapacitetin tënd.`,
      manyExercises: (params: { count: string }) =>
        `${params.count} ushtrime janë shumë volum në një seancë.`,
      manySets: (params: { count: string }) => `${params.count} seri gjithsej e rrisin intensitetin.`,
      longDuration: (params: { minutes: string }) =>
        `~${params.minutes} min të vlerësuara — seancë e gjatë.`,
      shortSession: "Seancë më e shkurtër me më pak elementë — më e menaxhueshme.",
      incompleteProfile:
        "Plotëso anketën e shëndetit dhe stilit të jetës për një vlerësim më të saktë.",
    },
    difficulty: {
      easy: { label: "E lehtë", tagline: "Punë e lehtë. Dil dhe lëviz." },
      moderate: { label: "Mesatare", tagline: "Seancë e vërtetë. Qëndro i fokusuar." },
      hard: { label: "E vështirë", tagline: "Ditë e rëndë. Merre dushun me meritë." },
      brutal: { label: "Brutale", tagline: "Modalitet bishë. Pa justifikime." },
      legend: { label: "E pamundur", tagline: "Nivel legjende. Dërgo ndihmë." },
    },
    timeRemaining: (duration: string) => `~${duration} mbeten`,
    finishSummaryTitle: "Përmbledhje seance",
    setsLogged: (done: number, total: number) => `${done}/${total} seri të regjistruara`,
    noExercisesTitle: "Nuk u ngarkuan ushtrime",
    noExercisesHint:
      "Kjo ditë stërvitjeje nuk ka ende ushtrime. Shtoni një më poshtë ose kthehuni dhe redaktoni programin.",
    exerciseName: "Emri i ushtrimit",
    exercisePlaceholder: "p.sh. Fluturime me kavo",
    noteOptional: "Shënim (opsional)",
    notePlaceholder:
      "p.sh. Ndihesha i fortë sot, rrita peshën në bench press…",
    finishNote:
      "Shtoni një shënim opsional për seancën — ose kaloni dhe ruani.",
    saveWithNote: "Ruaj me shënim",
    finishWorkout: "Përfundo stërvitjen",
    finishWithoutNote: "Përfundo pa shënim",
    lastSets: (parts: string) => `Herën e fundit: ${parts}`,
    scheduledWorkout: "Stërvitje e planifikuar",
    completedSuffix: "· e përfunduar",
    completeBy: (deadline: string) => `· përfundo deri në ${deadline}`,
    workoutPlan: "Plani i stërvitjes",
    workoutResults: "Rezultatet e stërvitjes",
    musclesTargetedToday: "Muskujt e synuar sot",
    muscleMapFront: "Para",
    muscleMapBack: "Prapa",
    noResultsLogged: "Nuk u regjistruan seri për këtë stërvitje.",
    foldersMeta: (folders: number, programs: number) =>
      `${folders} dosje · ${programs} program${programs === 1 ? "" : "e"}`,
    flowFolder: "Dosja",
    flowProgram: "Programi",
    flowSchedule: "Orari",
    allTile: "Të gjitha",
    exercisesTile: "Ushtrimet",
    aiPlanTile: "Plani AI",
    folderTile: "Dosje",
    foldersNav: "Dosjet",
    programsCount: (n: number) => `${n} program${n === 1 ? "" : "e"}`,
    daysBadge: (n: number) => `${n} ditë`,
    exBadge: (n: number) => `${n} ushtr.`,
    scheduledBadge: (n: number) => `${n} të planifikuara`,
    whenToStart: "Kur të fillojë",
    workoutDay: "Dita e stërvitjes",
    repeatDays: "Përsërit në këto ditë",
    repeatWeeks: "Përsërit për sa javë?",
    startNow: "Fillo tani",
    startNextMonday: "Javën tjetër (e hëna)",
    saveDaysFirst: "Ruani të paktën një ditë stërvitjeje para planifikimit.",
    upcomingSessions: (n: number) =>
      `${n} seancë${n === 1 ? "" : " seanca"} të planifikuara. Ndryshimet zëvendësojnë vetëm seancat e ardhshme.`,
    scheduleUpdated: "Orari u përditësua.",
    scheduleSaved: (n: number) => `U planifikuan ${n} seancë${n === 1 ? "" : " seanca"}.`,
    sessionsRemoved: "Seancat e ardhshme u hoqën.",
    saveSchedule: "Ruaj orarin",
    workout: "stërvitje",
    workouts: "stërvitje",
  },
  cardio: {
    title: "Kardio",
    addCardio: "Shto kardio",
    emptyTitle: "Ende nuk keni kardio të ruajtur",
    emptyHint:
      "Zgjidhni një lloj kardio më poshtë ose shtoni një seancë të personalizuar, pastaj planifikojeni në kalendar.",
    openYoutube: "Hape në YouTube",
    schedule: "Planifiko",
    browseTitle: "Llojet e kardios",
    mySessions: "Seancat e mia",
    myCardio: "Kardioja ime",
    addScheduleCardio: "Shto dhe planifiko kardion",
    locationGym: "Palestër",
    locationOutdoor: "Jashtë",
    locationEverywhere: "Kudo",
    types: {
      treadmill: "Treadmill",
      incline_walk: "Ecje me pjerrësi",
      elliptical: "Eliptik",
      stationary_bike: "Biçikletë statike",
      spin_bike: "Spin bike",
      rowing_machine: "Vozitje",
      stair_climber: "Shkallë",
      assault_bike: "Assault bike",
      ski_erg: "Ski erg",
      arc_trainer: "Arc trainer",
      battle_ropes: "Litarë lufte",
      sled_push: "Shtytje sanë",
      running: "Vrapim",
      trail_running: "Vrapim në natyrë",
      outdoor_cycling: "Biçikletë jashtë",
      hiking: "Ecje malore",
      brisk_walking: "Ecje e shpejtë",
      swimming: "Not",
      open_water_swim: "Not në natyrë",
      rollerblading: "Patinazh",
      kayaking: "Kajak",
      rock_climbing: "Alpinizëm",
      cross_country_ski: "Ski cross-country",
      soccer: "Futboll",
      basketball: "Basketboll",
      tennis: "Tenis",
      walking: "Ecje",
      jump_rope: "Kordë",
      hiit: "HIIT",
      dancing: "Vallëzim",
      jumping_jacks: "Jumping jacks",
      burpees: "Burpees",
      shadow_boxing: "Boks pa doreza",
      stair_climbing: "Ngjitje shkallësh",
      mountain_climbers: "Mountain climbers",
      high_knees: "High knees",
      bodyweight_circuit: "Qark bodyweight",
      boxing: "Boks",
      aerobics: "Aerobik",
      yoga_flow: "Yoga flow",
      pilates: "Pilates",
    },
  },
  habits: {
    title: "Zakonet ditore",
    suggestedFromProfile: "Sugjeruar nga profili juaj shëndetësor",
    inProgressSection: "Në progres",
    completedSection: "Të përfunduara",
    done: "Kryer",
  },
  weight: {
    title: "Pesha trupore",
    subtitle: "Ndiqni peshën tuaj me kalimin e kohës",
    loggedForDate: (value: string, date: string) => `${value} të regjistruara për ${date}`,
    weightForDate: (date: string, unit: string) => `Pesha për ${date} (${unit})`,
    placeholder: "p.sh. 75.5",
    logWeight: "Regjistro peshën",
    invalidWeight: "Vendosni një peshë të vlefshme",
  },
  photos: {
    title: "Fotot e progresit",
    monthComplete: "Muaji i plotësuar",
    readMeButton: "Lexomë",
    readMeTitle: "Para se të bësh fotot e progresit",
    readMeBody: [
      "Bëni foto përpara, prapa dhe anash çdo muaj me kamerën. Nuk lejohen foto nga galeria — bëni ato live për progres të sinqertë.",
      "Përdorni vetëm foto të veta — që nga kontrolli i parë. Alex mban mend kush shfaqet në fotot e progresit dhe e kontrollon me gjininë në profil.",
      "Gjinia e gabuar ose një person tjetër më vonë refuzohet.",
      "E përdorët gabimisht dikë tjetër në foton e parë? Kontaktoni suportin për ta rivendosur.",
    ],
    readMeGotIt: "E kuptova",
    readMeAgreeLabel: "E kam lexuar dhe pajtohem",
    readMeRequiredHint: "Lexo dhe prano para se të bësh foto",
    readMeSupportHint: "Person i gabuar në foton e parë? Kontaktoni suportin.",
    uploading: "Duke ngarkuar…",
    addPhoto: "Bëj foto",
    addPosePhoto: (pose: string) => `Shto foto ${pose}`,
    takePosePhoto: (pose: string) => `Bëj foto ${pose}`,
    replace: "Zëvendëso",
    retake: "Ribëj",
    deletePhoto: "Fshi",
    editPhoto: (pose: string) => `Ndrysho foton ${pose}`,
    previousMonths: "Muajt e mëparshëm",
    nextCheckIn: "Kontrolli i ardhshëm",
    noPhoto: "Pa foto",
    compressHint: "Fotot kompresohen para ngarkimit për të kursyer hapësirë.",
    removeFailed: "Fotoja nuk u hoq",
    uploadFailed: "Ngarkimi dështoi",
    analyzing: "Alex po kontrollon foton…",
    alexWrongPhotoTitle: "Foto e gabuar",
    retakePhoto: "Ribëj foton",
    alexAcceptedTitle: "Foto e pranuar",
  },
  trainer: {
    customWorkout: "Plan stërvitjeje personal",
    customNutrition: "Plan ushqimi personal",
    byTrainer: (name: string) => `nga ${name}`,
    oneTime: "një herë",
    ready: "Gati",
    pdfReady: "PDF gati",
    yourPreferences: "Preferencat tuaja",
    preferencesPlaceholder:
      "Qëllimet, niveli i përvojës, orari, lëndimet, preferencat ushqimore…",
    close: "Mbyll",
    done: "Kryer",
    continuePayment: "Le të ndërtojmë planin tim",
    implementing: "Duke zbatuar…",
    implementIt: "Zbato planin",
    implemented: "I zbatuar",
    viewPlan: "Shiko planin",
    implementedConfirmed: "I zbatuar dhe konfirmuar",
    onCalendar: "Në kalendarin tuaj",
    nutritionImplemented:
      "Plani i ri i ushqimit është në kalendar. Vaktet e mëparshme u zëvendësuan me orarin e trajnerit.",
    workoutImplemented:
      "Plani i ri i stërvitjes është aktiv. Zëvendësoi planin e mëparshëm të trajnerit.",
    receivePdf: "Merrni planin si PDF në aplikacion",
    implementWhenReady: "Zbatojeni në kalendar kur të jeni gati",
    requestInProgress: "Kërkesa në proces.",
    proposalRejected:
      "Propozimi juaj nuk u pranua. Pagesa do të rimbursohet.",
    awaitingApproval: "Në pritje të miratimit nga trajneri.",
    trainerBuilding: "Trajneri po përgatit planin tuaj.",
    planDelivered: "Plani juaj është gati për shqyrtim.",
    planImplemented: "Plani është në kalendarin tuaj.",
  },
  ai: {
    askAlex: "Pyet Alex-in",
    aiCoach: "Coach AI",
    aiInsight: "Vëzhgim AI",
    upgrade: "Përmirëso planin",
    proteinGap: (g: number) => `Mungesë proteine sot: ~${g}g të mbetura`,
    starterPrompts: [
      "Si jam sot?",
      "Trego raportin tim javor",
      "Çfarë të ha për darkë?",
      "Trego trendin e peshës",
      "Më ndërto një plan stërvitjeje për këtë javë",
    ],
    thinking: "Duke menduar…",
    searching: "Duke kërkuar dhe menduar…",
    placeholder: "Pyet për stërvitje, ushqim, rikuperim…",
    imageOnlyPrompt: "Çfarë mund të më thuash për këtë foto?",
    medicalDisclaimer:
      "Nuk jap këshilla mjekësore. Për ato, konsultohu me mjekun, jo me mua.",
    readMeButton: "Lexomë",
    readMeTitle: "Para se të bisedosh me mua",
    readMeBody: [
      "Jam sarkastik dhe i drejtpërdrejtë. Do t'i godas shpëtimin, zakonet e dobëta dhe do të të shtyj fort — kjo është ideja.",
      "Mund të përdor gjuhë të fortë ose betejera kur jam i nxitur. Është energjia ime si coach, jo sulm personal.",
      "Nuk jam mjek. Për lëndime, dhimbje, medikamente ose çdo gjë mjekësore, jap vetëm sugjerime të përgjithshme për stërvitje dhe ushqim — gjithmonë konfirmo me mjekun.",
      "Pa diagnoza, pa receta, pa garanci mjekësore nga unë. Kur ke dyshime, flit me një profesionist, jo me këtë chat.",
    ],
    readMeGotIt: "E kuptova — le të bisedojmë",
    readMeAgreeLabel: "E kam lexuar dhe pajtohem",
    readMeRequiredPlaceholder: "Lexo dhe prano para se të bisedosh…",
    chatUnreachable: "Nuk u arrit Coach AI",
    noStream: "Nuk ka përgjigje nga serveri",
    requestFailed: "Kërkesa AI dështoi",
    sources: (n: number) => `${n} burim${n === 1 ? "" : "e"}`,
    buildPlan: "Ndërto planin tënd",
    flowProfile: "Profili",
    flowAiBuilds: "AI ndërton",
    flowApply: "Zbato",
    startChatting: "Fillo bisedën",
    today: "Sot",
    weeklyScores: "Rezultatet javore",
    logMealsAi: "Regjistro vakte me AI",
    flowPhoto: "Foto / tekst",
    flowEstimate: "AI vlerëson",
    flowConfirm: "Konfirmo",
    goDashboard: "Shko te paneli",
    fullReport: "Raporti i plotë →",
    logMealsForRings: "Regjistro vakte për të parë unazhat e makronutrientëve",
    workoutsThisWeek: "Stërvitje këtë javë",
    daysTracked: "Ditë të ndjekura",
    training: "Stërvitje",
    nutrition: "Ushqim",
    consistency: "Konsistencë",
    cal: "Kal",
    protein: "Proteinë",
    carbs: "Karboh.",
    fat: "Yndyrë",
    askCoach: "Pyet coach-in",
    mealIdeas: "Ide vaktesh",
    tips: "Këshilla",
    progress: "Progres",
    logMealsGuidance: "Regjistro vakte për udhëzime të personalizuara.",
  },
  aiUpgrade: {
    unlockFeature: "Përmirëso në AI Pro për të hapur këtë funksion",
    viewAiPlan: "Shiko planin AI Pro",
    aiWorkoutPlan: "Plan stërvitjeje me AI",
    aiNutritionPlan: "Plan ushqimi me AI",
    photoLog: "Regjistrim me foto",
    textLog: "Regjistrim me tekst",
    aiChat: "Chat fitnesi AI",
  },
  eliteUpgrade: {
    unlockFeature: "Përmirëso në Elite për klasa live, sfida dhe komunitet",
    viewElitePlan: "Shiko planin Elite",
    liveClasses: "Klasa live",
    challenges: "Sfida",
    community: "Komuniteti",
    exclusive: "Përmbajtje ekskluzive",
  },
  checkoutFlow: {
    title: "Le të fillojmë",
    back: "Ende nuk je gati?",
    steps: ["Plani yt", "Pothuajse brenda", "Bëje zyrtare"],
    total: "Angazhimi yt",
    summaryTitle: "Çfarë po merr",
    summarySubtitle:
      "Alex e përgatiti këtë — shiko shpejt para se të angazhohesh.",
    finalizeTitle: "Hapi i fundit",
    finalizeSubtitle: "Siguro vendin tënd. Pastaj stërvitemi seriozisht.",
    planLabel: "Plan",
    priceLabel: "Investimi",
    billingMonthly: "Mujore",
    billingAnnual: "Vjetore",
    includes: "Po hap",
    secureBadge: "I sigurt & i mbyllur",
    cardsBadge: "Kartë ose wallet — si të duash",
    preparing: "Po përgatisim vendin tënd…",
    primaryCta: "Jam brenda — le të fillojmë",
    pokPaySubmitLabel: "Nisim Transformimin",
    checkoutErrorTitle: "Hmm. Nuk shkoi.",
    tryAgain: "Provo përsëri",
    processorNote: "Përpunohet në mënyrë të sigurt nga PokPay.",
    completePurchase: "Gati për stërvitje serioze?",
    orderLabel: "Kërkesa jote",
    whatNextTitle: "Çfarë ndodh më pas",
    whatNext1: "Konfirmimi vjen menjëherë pasi ta bësh zyrtare.",
    whatNext2: "Kërkesa shfaqet në panelin tënd.",
    customSuccessTitle: "Kërkesa u regjistrua",
    customSuccessWait: (trainer: string) =>
      `Po presim që ${trainer} ta miratojë propozimin. Nëse nuk kalon, je i mbuluar.`,
    backToWorkout: "Kthehu te stërvitja",
    backToNutrition: "Kthehu te ushqimi",
  },
  mealPlan: {
    noMealsScheduled: "Nuk ka vakte të planifikuara për këtë ditë.",
    noMealDetails: "Ende nuk janë shtuar detaje për këtë vakt.",
    option: (n: number) => `Opsioni ${n}`,
    ingredients: "Përbërësit",
    howToCook: "Si të përgatitet",
  },
  groceryList: {
    title: "Lista e blerjeve",
    subtitle: "Përbërësit për një javë sipas planit të vakteve",
    empty: "Shto përbërës te vaktet për të krijuar listën e blerjeve.",
    progress: (bought: number, total: number) => `${bought} nga ${total} në shportë`,
    checkItem: (name: string) => `Shëno ${name} si të blerë`,
    uncheckItem: (name: string) => `Shëno ${name} si të pa blerë`,
  },
  calendar: {
    fullCalendar: "Kalendari i plotë",
  },
  pricing: {
    step: "Hapi 3 — Zgjidh paketën",
    choosePlan: "Zgjidh planin tënd",
    onboardingBlurb:
      "Fillo me ndjekje të strukturuar ose zhblloko coach-in AI — abonohu tani ose eksploro fillimisht.",
    upgradeBlurb:
      "Tre nivele që rriten me ty — nga ndjekja e strukturuar te coach AI dhe komuniteti Elite.",
    monthly: "Mujore",
    annual: "Vjetore",
    perMonth: "muaj",
    perYear: "vit",
    currentPlan: "Plani aktual",
    switchPlan: "Ndrysho planin",
    subscribe: "Le të fillojmë",
    savePerYear: (amount: string) => `Kurseni ${amount}/vit`,
    includesFrom: (planName: string) => `Gjithçka në ${planName}, plus:`,
  },
  checkout: {
    paymentFailed: "Nuk shkoi. Provo përsëri — Alex nuk ikën askund.",
    missingOrder: "Diçka mungon nga ana jonë. Kontakto mbështetjen nëse ngec.",
    paymentUnconfirmed:
      "Nuk mundëm të konfirmojmë që je brenda. Nëse u debituat, kontakto mbështetjen.",
    continueToPayment: "Jam brenda — le të fillojmë",
    confirming: "Po përgatisim llogarinë tënde…",
    successTitle: "Je brenda. Tani punojmë.",
    successBody:
      "Aksesi i plotë u hap. Regjistro stërvitje, vakte, zakone — Alex po të shikon.",
    errorTitle: "Pothuajse",
    goDashboard: "Shko te paneli",
    backPricing: "Zgjidh një plan tjetër",
  },
  bmi: {
    title: "BMI",
    whatIsBmi: "Çfarë është BMI?",
    bodyMassIndex: "Indeksi i masës trupore (BMI)",
    helpText:
      "Një vlerësim i përafërt i yndyrës nga lartësia dhe pesha. Nuk merr parasysh masën muskulore ose përbërjen e trupit.",
    addHeightWeight: "Shtoni lartësinë dhe peshën për të parë BMI-në.",
    addHeight: "Shtoni lartësinë në profil për të llogaritur BMI-në.",
    logWeight: "Regjistroni peshën për të llogaritur BMI-në.",
    updateProfile: "Përditëso profilin",
    underweight: "Nën peshë",
    normal: "Normal",
    overweight: "Mbipeshë",
    obese: "Obezitet",
  },
  mealLog: {
    logMeal: "Regjistro vaktin",
    logAMeal: "Regjistro një vakt",
    newMeal: "Vakt i ri",
    fromLibrary: "Libri i recetave",
    typeMeal: "Shkruaj vaktin",
    photoLog: "Regjistro me foto",
    typeIt: "Shkruaje",
    typeItDesc: "Përshkruani çfarë keni ngrënë — AI vlerëson makrot",
    photoDesc: "Bëni një foto — AI plotëson detajet",
    fromLibraryDesc: "Shfletoni 13k receta ose zgjidhni një vakt të ruajtur",
    nameRequired: "Emri i vaktit është i detyrueshëm",
    goBack: "Kthehu",
    chooseImage: "Zgjidhni një skedar fotoje",
    processFailed: "Fotoja nuk u përpunua. Provoni një tjetër.",
    takePhotoFirst: "Bëni ose zgjidhni një foto fillimisht",
    readFailed: "Fotoja nuk u lexua",
    uploadTooLarge:
      "Ngarkimi dështoi — fotoja mund të jetë shumë e madhe. Provoni përsëri ose përdorni një më të vogël.",
    mealPreview: "Parapamje e vaktit",
    takePhoto: "Bëj foto",
    addMealPhoto: "Shto foto vakti",
    changePhoto: "Ndrysho foton",
    mealName: "Emri i vaktit",
    doneAdjusting: "Përshtatja u krye",
    adjustDetails: "Përshtat detajet e vaktit",
    retakePhoto: "Ribëj foton",
    descriptionNotes: "Përshkrim ose shënime",
    removeIngredient: "Hiq përbërësin",
    whatToEatToday: "Çfarë të hash sot",
    photoSavedHint: "Fotoja ruhet për 30 ditë me këtë vakt.",
  },
  mealPhotos: {
    title: "Fotot e vakteve",
    subtitle: "Fotot nga vaktet që ke regjistruar me kamerë.",
    retentionHint: (days: number) =>
      `Fotot mbahen ${days} ditë, pastaj fshihen. Vaktet mbeten në regjistrin tënd pa foto.`,
    emptyTitle: "Ende pa foto vaktesh",
    emptyBody: "Regjistro një vakt me Photo log për të ruajtur një foto të kompresuar këtu.",
    viewPhotos: "Fotot",
  },
  subscriptionPlans: {
    basic: {
      name: "RUTINA Basic",
      tagline:
        "Ideale për përdoruesit që duan stërvitje të strukturuara, plane ushqimi dhe ndjekje progresi.",
      features: [
        "Plane stërvitjeje të personalizuara",
        "Plane ushqimi",
        "Regjistrim manual vaktesh",
        "Ndjekje peshe",
        "Matje trupi",
        "Foto progresi",
        "Historiku i stërvitjeve",
        "Statistika progresi",
        "Ndjekje serie ditore",
        "Arritje bazike",
        "Bibliotekë ushtrimesh",
        "Regjistrim i pakufizuar stërvitjesh",
      ],
    },
    aiPro: {
      name: "RUTINA AI Pro",
      tagline:
        "Gjithçka në Basic, plus coach-i yt AI i fitnesit që përshtatet me progresin tënd.",
      badge: "Më i popullarizuari",
      includesFrom: "RUTINA Basic",
      features: [
        "Coach Fitnesi AI",
        "Coach Ushqimi AI",
        "Gjenerator Stërvitjesh AI",
        "Sugjerime Vaktesh AI",
        "Raporte Progresi AI",
        "Motivim Ditor AI",
        "Chat Fitnesi AI",
        "Rekomandime të personalizuara",
        "Përshtatje automatike stërvitjesh",
        "Rekomandime automatike kalorish dhe makronutrientesh",
        "Analiza rikuperimi dhe performancë AI",
      ],
    },
    elite: {
      name: "RUTINA Elite",
      tagline:
        "Përvoja e plotë e fitnesit me coaching, komunitet dhe evente live.",
      includesFrom: "RUTINA AI Pro",
      features: [
        "Klasa trajnimi live",
        "Sfidat e komunitetit",
        "Sfidat mujore transformimi",
        "Gara me çmime në para (fondi varet nga pjesëmarrja)",
        "Thirrje javore coaching në grup",
        "Tabela renditjeje",
        "Stërvitje ekskluzive",
        "Përmbajtje edukative ekskluzive",
        "Akses i hershëm në veçori të reja",
        "Mbështetje prioritare",
        "Akses në komunitetin Elite",
      ],
    },
  },
  classes: {
    comingSoon: "Së shpejti.",
    upgradeDescription:
      "Përmirëso në Elite për klasa trajnimi live, sfida komuniteti dhe coaching në grup.",
    upgradeDescriptionShort:
      "Përmirëso në Elite për klasa live, sfida dhe akses në komunitet.",
  },
  challenges: {
    leagueTagMen: "Liga e burrave",
    leagueTagWomen: "Liga e grave",
    rulesTitle: "Rregullat e sfidës",
    rulesButton: "Rregullat e sfidës",
    rulesAndInstructionsButton: "Rregullat dhe udhëzimet",
    share: {
      button: "Ndaj",
      copied: "Lidhja u kopjua!",
      message: "Bashkohu sfidës {title} në RUTINA!",
      fallbackPrompt: "Kopjo këtë lidhje sfide:",
    },
    rulesAndInstructionsTitle: "Rregullat dhe udhëzimet",
    rulesTab: "Rregullat",
    instructionsTab: "Udhëzimet",
    backToChallenge: "Kthehu te sfida",
    rulesClose: "Kthehu te sfida",
    rulesIntro:
      "Turne transformimi {count}-mujor. Kërkohet anëtarësi Elite. Regjistrimi është falas — fondi i çmimit është vetëm për shfaqje dhe paguhet manualisht kampionit.",
    rules: [
      "Kërkohet anëtarësi Elite për regjistrim. Hyrja në sfidë është falas mbi abonimin.",
      "Fondi i çmimit rritet me çdo pjesëmarrës (€X × pjesëmarrës). Vetëm shfaqje — pa pagesë në app. Organizatori paguan kampionin manualisht.",
      "Regjistro stërvitjet, vaktet, peshën dhe zakonet me ndershmëri gjatë turneut. Rezultati yt i përgjithshëm në platformë llogaritet 30% të çdo vendimi për fituesin.",
      "Formula e fituesit në çdo eliminim Zoom dhe finalen e kampionit: 30% rezultat platforme, 30% votë e pjesëmarrësve në thirrje, 40% votë e organizatorit.",
      "Mos mashtro platformën (regjistrime false). Pjesëmarrësit e pandershëm mund të përjashtohen.",
      "Zoom Raundi 1 — grupe ~{groupSize}, një thirrje në orë. Elimino 5, avancon 5 për grup me formulën e ponderuar.",
      "Zoom Raundi 2 — të mbijetuarit rib grupohen në grupe {groupSize}. Një fitues për grup avancon me të njëjtën formulë.",
      "Finalja e kampionit — të gjithë fituesit e grupeve në një thirrje Zoom. E njëjta formulë 30/30/40 zgjedh kampionin.",
      "Zoom verifikon realitetin — para kamerës shihet ndryshimi i vërtetë, jo vetëm numrat në app.",
      "Kampioni merr të gjithë fondin e shfaqur, paguar manualisht nga organizatori (pa cashout në app).",
    ],
    instructionsIntro:
      "Udhëzues hap pas hapi për turneun {count}-mujor — çfarë të bësh para, gjatë dhe pas çdo eliminimi në Zoom.",
    instructions: [
      "Regjistrohu në faqen e sfidës (kërkohet anëtarësi Elite). Hyrja është falas — fondi i çmimit është vetëm për shfaqje.",
      "Gjatë turneut, regjistro stërvitjet, vaktet, peshën dhe zakonet në app çdo ditë. Rezultati yt i përgjithshëm në platformë vlen 30% të çdo vendimi për fituesin.",
      "Para çdo Zoom, shiko rezultatin tënd në platformë te faqja e sfidës — është një e treta e mënyrës se si zgjidhen fituesit.",
      "Para çdo dite eliminimi, hap faqen e sfidës për numrin e grupit dhe orën e Zoom (një grup në orë).",
      "Zoom Raundi 1: hyr para kamerës me grupin ~{groupSize}. Trego transformimin. Pesë avancojnë, pesë eliminohen me 30% rezultat platforme, 30% votë pjesëmarrësish, 40% votë organizatori.",
      "Nëse kalon në Raundin 2, vendosesh në grup të ri ~{groupSize}. Një fitues për grup shkon në finalen e kampionit me të njëjtën formulë të ponderuar.",
      "Finalja e kampionit: të gjithë fituesit e grupeve në një thirrje Zoom. Pjesëmarrësit votojnë (30%), rezultatet e platformës llogariten (30%), organizatori jep votën vendimtare 40%.",
      "Kampioni merr fondin e shfaqur, paguar manualisht nga organizatori — pa cashout në app.",
    ],
    tournamentTitle: "Turne eliminimi {count}-mujor",
    tournamentIntro:
      "Zgjat deri në {count} muaj me tri ditë eliminimi në Zoom: R1 10→5, R2 një fitues për grup, pastaj finalja e kampionit.",
    tournamentDuration: "Turne {count}-mujor",
    tournamentMonthlyRound: "Tri ditë eliminimi Zoom gjatë turneut",
    phase1Title: "Raundi 1 · Semi-eliminim",
    phase1Body:
      "Grupe {groupSize} në thirrje Zoom çdo orë. Elimino 5, avancon 5 (~gjysma e fushës).",
    phase2Title: "Raundi 2 · Finale grupi",
    phase2Body:
      "Të mbijetuarit rib grupohen në grupe {groupSize}. Një fitues për grup shkon në finalen.",
    phase3Title: "Finalja e kampionit",
    phase3Body:
      "Të gjithë fituesit e grupeve në një thirrje Zoom. Kampioni zgjidhet me 30% rezultat platforme, 30% votë pjesëmarrësish, 40% votë organizatori.",
    judgingFormulaTitle: "Formula e votimit për fituesin",
    judgingFormulaIntro:
      "Në çdo eliminim Zoom dhe finalen e kampionit, fituesi zgjidhet duke kombinuar tre inpute të ponderuara.",
    selectionPlatformTitle: "Rezultati i përgjithshëm në platformë",
    selectionPlatformWeight: "30%",
    selectionPlatformBody:
      "Rezultati yt i përgjithshëm nga stërvitjet, vaktet, pesha, zakonet dhe raportet javore me AI gjatë turneut.",
    selectionZoomTitle: "Vota e pjesëmarrësve në Zoom",
    selectionZoomWeight: "30%",
    selectionZoomBody:
      "Të gjithë në thirrjen Zoom votojnë për kush tregoi transformimin më të mirë para kamerës atë raund.",
    selectionAdminTitle: "Vota e organizatorit",
    selectionAdminWeight: "40%",
    selectionAdminBody:
      "Organizatori i sfidës jep votën finale të ponderuar bazuar në performancën e përgjithshme dhe prezantimin live.",
    bracketTitle: "Grafiku i turneut",
    leaderboardTitle: "Tabela e pikëve",
    leaderboardEmpty: "Ende pa pjesëmarrës — anëtarët Elite regjistrohen nga faqja e sfidës.",
    leaderboardIntro:
      "Renditur sipas pikëve ditore (50% ushqim · 30% stërvitje · 20% zakone + ujë) — më i larti i pari.",
    leaderboardMaxPoints: "Maksimumi i mundshëm: {max} pikë (100 për ditë të regjistruar).",
    leaderboardEndedNoChampion:
      "Kjo sfidë ka përfunduar. Kampioni shfaqet pasi të përfundojë dita e gjykimit.",
    pointsUnit: "pikë",
    championLabel: "Kampion",
    championPrizeHint: "Çmimi paguhet manualisht nga organizatori — pa pagesë në aplikacion.",
    judgmentDayInviteLabel: "I ftuar në ditën e gjykimit",
    judgmentZoomTitle: "Zoom — dita e gjykimit",
    judgmentZoomIntro:
      "Je ftuar për shkak të pikëve. Bashkohu live para kamerës — organizatori zgjedh fituesin pas thirrjes.",
    judgmentZoomJoin: "Bashkohu në Zoom",
    judgmentZoomLinkPending: "Linku i Zoom vjen së shpejti",
    judgmentZoomPendingHint:
      "Je i regjistruar. Vazhdo të regjistrosh çdo ditë për të ngjitur në tabelë — më të lartët ftohen në Zoom të ditës së gjykimit.",
    bracketEmpty: "Ende pa pjesëmarrës — anëtarët Elite regjistrohen nga faqja e sfidës.",
    bracketGroupsPending:
      "Duke pritur grupet prej {groupSize} — do të vizatohen para ditës së eliminimit.",
    rankedByScore:
      "Renditur sipas pikëve (50% ushqim · 30% stërvitje · 20% zakone + ujë) — më i larti i pari.",
    bracketIntro:
      "R1: {groupSize} për grup, 5 avancojnë · R2: rib grupo, 1 fitues për grup · Finalja: një kampion.",
    zoomRound1Intro:
      "Raundi 1 — deri {groupSize} persona. Live: elimino 5, avancon 5. Formula: 30% rezultat platforme, 30% votë pjesëmarrësish, 40% votë organizatori.",
    zoomRound2Intro:
      "Raundi 2 — deri {groupSize} persona. Zgjidh një fitues grupi me të njëjtën formulë 30/30/40.",
    zoomFinalIntro:
      "Finalja e kampionit — fituesi zgjidhet me 30% rezultat platforme, 30% votë pjesëmarrësish në Zoom, 40% votë organizatori.",
    zoomRegisterHint:
      "Regjistrohu (Elite) për linkun e grupit kur vizatohen bracket-et.",
    zoomPendingHint:
      "Je i regjistruar. Grupi dhe ora e Zoom shfaqen kur përcaktohen bracket-et.",
    diagramFlowTitle: "Si funksionon turneu {count}-mujor",
    diagramAdvanceCount: "{count} avancojnë",
    diagramOneWinner: "1 fitues",
    diagramPerGroup: "për grup {groupSize}",
    diagramChampionWins: "Një kampion · fondi i plotë",
    diagramFunnelTitle: "Fusha ngushtohet çdo raund",
    diagramFunnelSubtitle: "Shembull me 100 pjesëmarrës",
    diagramFunnelStart: "{count} pjesëmarrës",
    diagramFunnelR1: "{count} pas Raundit 1",
    diagramFunnelR2: "{count} finalistë",
    diagramFunnelChampion: "1 kampion",
    diagramFunnelNote:
      "Çdo grup R1 prej {groupSize} eliminon gjysmën (~{half} avancojnë). R2 zgjedh një fitues për grup.",
    diagramPrepOnly: "30% e vendimit për fituesin",
    diagramDecisive: "30% e vendimit për fituesin",
    diagramAdminWeight: "40% e vendimit për fituesin",
    diagramPlatformBullets: [
      "Stërvitje, vakte, peshë & zakone",
      "Rezultatet e raportit javor AI",
      "Renditur në grafikun e sfidës",
    ],
    diagramZoomBullets: [
      "Transformim live para kamerës",
      "Të gjithë në thirrje votojnë",
      "Një votë për pjesëmarrës në Zoom",
    ],
    diagramAdminBullets: [
      "Vota finale e ponderuar e organizatorit",
      "Vlerëson performancën e përgjithshme",
      "Pjesa më e madhe e formulës",
    ],
    diagramRulesEliteTitle: "Elite + hyrje falas",
    diagramRulesEliteBody: "Kërkohet Elite. Regjistrimi shton në fondin e shfaqur vetëm.",
    diagramRulesPrizeTitle: "Fondi i çmimit",
    diagramRulesPrizeBody: "Rritet me çdo pjesëmarrës (vetëm shfaqje). Kampioni paguhet manualisht.",
    diagramRulesZoomTitle: "Zoom verifikon",
    diagramRulesZoomBody: "Tri ditë eliminimi gjatë {count} muajve. Logimet ndihmojnë; Zoom konfirmon kush avancon.",
    detailStatStart: "Data e fillimit",
    detailStatDuration: "Kohëzgjatja",
    detailStatGroupSize: "Madhësia e grupit",
    detailStatScoring: "Pikëzimi",
    detailStatScoringValue: "Pikë ditore",
    detailStatRegistered: "Të regjistruar",
    detailPhaseTitle: "Kronologjia e turneut",
    detailPhaseRegistration: "Regjistrimi & logimi",
    detailPhaseRound1: "Raundi 1 · Gjysem-eliminim",
    detailPhaseRound2: "Raundi 2 · Finale grupi",
    detailPhaseFinal: "Finalja e kampionit",
    detailPhaseComplete: "Kampioni shpallur",
    detailPhaseCurrent: "Aktual",
    detailPhaseDateTbd: "Data së shpejti",
    diagramFunnelSubtitleDynamic: "Bazuar në {count} pjesëmarrës aktualë",
    detailFullRulesHint: "Rregullat e plota, udhëzues hap pas hapi dhe diagramet e detajuara",
    detailFieldTitle: "Pamje e fushës",
    detailFieldRegistered: "{count} të regjistruar",
    detailFieldGroups: "~{count} grupe R1 prej {groupSize}",
    detailFieldEmpty: "Ende pa pjesëmarrës — regjistrohu i pari",
    detailFieldProjectionTitle: "Madhësitë e parashikuara të bracket-it",
    detailFieldProjectionNote: "Nëse bracket-et vizatohen sot",
    detailZoomScheduleTitle: "Datat e eliminimit në Zoom",
    detailZoomRound1Short: "Raundi 1",
    detailZoomRound2Short: "Raundi 2",
    detailZoomFinalShort: "Finalja e kampionit",
    announcementsTitle: "Njoftimet",
    announcementsFromAdmin: "Nga {name} (admin)",
    announcementsLiveBadge: "Përditësim live",
    announcementsEmpty: "Ende pa njoftime — kthehu për përditësime nga organizatori.",
    prizePool: {
      grandPrize: "Fondi i çmimit të madh",
      winUpTo: "Fitoni deri në {pool}",
      maxPrizeLabel: "Fitoni deri në",
      cardMaxPoolHint:
        "Mund të fitosh deri në {pool} nëse të gjithë {max} pjesëmarrësit bashkohen në sfidë.",
      catalogWinUpToLine: "{pool} nëse mbushen të {max} vendet",
      compactWinUpTo: "Deri në {pool}",
      compactMaxPoolHint: "Deri në {pool} nëse bashkohen {max}",
      championTakesAll: "Kampioni merr të gjithë fondin — paguar manualisht nga organizatori.",
      perEntry: "Për pjesëmarrës",
      perParticipant: "+{amount} × {count} pjesëmarrës · muaji {month} i fondit",
      participants: "{count} të regjistruar",
      growsWithSignups: "Rritet me çdo regjistrim",
      monthlyPoolGrowth: "+€10 për pjesëmarrës shtohet në fond çdo muaj",
      monthlyPoolGrowthActive:
        "Muaji {month} · +{amount} × {count} pjesëmarrës në fond",
      doublesMonthly: "+€10 për pjesëmarrës shtohet në fond çdo muaj",
      doublesMonthlyActive:
        "Muaji {month} · +{amount} × {count} pjesëmarrës në fond",
      flashPoolNote: "€5 për pjesëmarrës në fond",
      flashCatch: "Deri në {pool}",
      flashCatchWindow: "në 24 orë",
      entryFee: "Tarifa e hyrjes",
      compactPool: "{pool} fond çmimi",
    },
    flash: {
      intro:
        "Sprint i shpejtë — 24 orë pasi bashkohen 10 persona. Filmo në Zoom, organizatori regjistron rezultatin, më i larti fiton fondin.",
      steps: [
        "10 të parët rezervojnë vend falas. Organizatori nis dritaren 24-orëshe kur të paktën 10 janë regjistruar.",
        "Të gjithë në grupin e parë paguajnë €10 për ta konfirmuar vendin kur grupi mbushet.",
        "Pas 10 të parëve, të rinjtë paguajnë €10 menjëherë kur bashkohen (deri në 50 total).",
        "Pjesëmarrësit ndahen në grupe Zoom deri 10 (maks. 5 grupe) kur fillon sfida.",
        "Pas Zoom të çdo grupi, organizatori fut rekordin e fituesit (kohë, rep, etj.).",
        "Midis fituesve të grupeve, rekordi më i lartë fiton fondin e plotë.",
      ],
      windowLabel: "Afati",
      entryLabel: "Tarifa e hyrjes",
      poolLabel: "Fondi i çmimit",
      participantsLabel: "Pjesëmarrësit",
      startsNotice: "Kjo sfidë fillon më {datetime}.",
      zoomCallTitle: "Thirrja Zoom",
      zoomFromAnnouncement: "Orari nga njoftimi i organizatorit më sipër.",
      zoomPending: "Detajet e thirrjes Zoom do të postohen në njoftimin më sipër.",
      joinZoomButton: "Bashkohu thirrjes Zoom",
      zoomLinkPending: "Lidhja Zoom së shpejti",
      zoomGroupsTitle: "Grupet e pjesëmarrësve",
      zoomGroupsSection: "Zoom · {count} grupe × ~{groupSize}",
      zoomGroupLabel: "Zoom",
      zoomGroupsEmpty: "Ende pa pjesëmarrës — regjistrohu për një grup Zoom.",
      zoomGroupsPending:
        "Duke pritur grupet prej {groupSize} — ndahen sipas rendit të bashkimit kur organizatori nis sfidën.",
      joinOrderHint: "Renditur sipas bashkimit — #1 regjistrohet i pari.",
      fillingNotice: "Duhen edhe {count} regjistrime para se organizatori të mund ta nisë.",
      waitingToStart: "10+ të regjistruar — duke pritur organizatorin të nisë dritaren 24-orëshe.",
      fillingReady: "Sfida është live — dritarja 24-orëshe po vazhdon.",
      performanceLabel: "Rekord",
      winnerLabel: "Fituesi",
    },
    flashAlex: {
      intro:
        "Duel i shpejtë — 24 orë pasi bashkohen 10 persona. Filmoje në Zoom, Alex regjistron kush u paraqit vërtet. Rekordi më i lartë fiton fondin.",
      steps: [
        "10 të parët rezervojnë vend falas. Organizatori nis orën 24-orëshe kur ka të paktën 10.",
        "Të gjithë në grupin e parë paguajnë €10 për të konfirmuar kur grupi mbushet.",
        "Pas 10 të parëve, të rinjët paguajnë €10 menjëherë (deri në 50 total).",
        "Ndahen në grupe Zoom deri në 10 kur nis sfida.",
        "Pas çdo Zoom grupi, organizatori regjistron rekordin e fituesit.",
        "Rekordi më i lartë midis fituesve të grupeve merr fondin e plotë.",
      ],
      windowLabel: "Dritarja",
      entryLabel: "Tarifa e hyrjes",
      poolLabel: "Fondi i çmimit",
      participantsLabel: "Pjesëmarrësit",
      startsNotice: "Kjo sfidë nis më {datetime}.",
      zoomCallTitle: "Thirrja Zoom",
      zoomFromAnnouncement: "Orari nga njoftimi i organizatorit më sipër.",
      zoomPending: "Detajet e Zoom do të postohen në njoftimin më sipër.",
      joinZoomButton: "Bashkohu Zoom",
      zoomLinkPending: "Lidhja Zoom së shpejti",
      zoomGroupsTitle: "Grupet e pjesëmarrësve",
      zoomGroupsSection: "Zoom · {count} grupe × ~{groupSize}",
      zoomGroupLabel: "Zoom",
      zoomGroupsEmpty: "Ende pa pjesëmarrës — regjistrohu për një grup Zoom.",
      zoomGroupsPending:
        "Duke pritur grupet prej {groupSize} — ndahen sipas rendit të bashkimit kur organizatori nis sfidën.",
      joinOrderHint: "Renditur sipas bashkimit — #1 regjistrohet i pari.",
      fillingNotice: "Duhen edhe {count} regjistrime para se organizatori të mund ta nisë.",
      waitingToStart: "10+ të regjistruar — duke pritur organizatorin të nisë dritaren 24-orëshe.",
      fillingReady: "Sfida është live — dritarja 24-orëshe po vazhdon.",
      performanceLabel: "Rekord",
      winnerLabel: "Fituesi",
    },
    longMen: {},
    longWomen: {
      rulesIntro:
        "Turneu juaj i transformimit {count}-mujor. Vetëm anëtarët Elite — regjistrimi është falas dhe çdo pjesëmarrës rrit fondin e çmimit.",
      tournamentIntro:
        "Deri në {count} muaj me tre ditë eliminimi Zoom: Raundi 1 ngushton fushën, Raundi 2 zgjedh fituesit e grupeve, pastaj finalja e kampionit.",
    },
    catalog: {
      longTag: "Gjata",
      longTitle: "Sfidat e gjata",
      longSubtitle:
        "30 ditë deri 12 muaj — 100 vende secila, listë pritjeje kur plot, +€10 për pjesëmarrës në fond çdo muaj.",
      longSubtitleMen:
        "30 ditë deri 12 muaj — Liga e burrave. 100 vende, listë pritjeje kur plot, +€10 për person në fond çdo muaj.",
      longSubtitleWomen:
        "30 ditë deri 12 muaj — Liga e grave. 100 vende, listë pritjeje kur plot, +€10 për pjesëmarrës rrit fondin çdo muaj.",
      flashTag: "Flash",
      flashTitle: "Sfidat flash",
      flashSubtitle:
        "Deri në €250 në 24 orë — tarifa e hyrjes, max 50 vende.",
      flashSubtitleAlex:
        "Deri në €250 në 24 orë — paraqitu në Zoom, mposht fushën, max 50 vende.",
      viewChallenge: "Shiko sfidën",
    },
    join: {
      registerFree: "Regjistrohu (Elite · falas)",
      registerWithFee: "Bashkohu · hyrje {fee}",
      joinWaitlist: "Bashkohu listës së pritjes (Elite · falas)",
      switchToThis: "Kalo te ky sfidë",
      joining: "Duke u regjistruar…",
      leaving: "Duke u larguar…",
      leaveChallenge: "Largohu nga sfida",
      leaveWaitlist: "Largohu nga lista e pritjes",
      leavingWaitlist: "Duke u larguar nga lista…",
      registeredHere: "Je i regjistruar për këtë sfidë.",
      waitlistJoined: "Je në listën e pritjes — do të shtohesh kur hapet një vend.",
      successRegistered: "U regjistruar!",
      challengeFull: "Të 100 vendet janë zënë — bashkohu listës së pritjes.",
      flashChallengeFull: "Të 50 vendet janë zënë — bashkohu listës së pritjes.",
      spotsRemaining: "{remaining} nga {max} vende të lira",
      waitlistPosition: "Pozicioni #{position} në listë — i pari merr vendin e ardhshëm.",
      switchNotice:
        "Je në {title}. Duke u bashkuar këtu do të largohesh nga ajo sfidë (ose lista e pritjes nëse është plot).",
      activeLongChallengeBlocksJoin:
        "Je në {title}. Largohu nga ajo sfidë ose prit derisa të përfundojë para se të bashkohesh në një sfidë tjetër të gjatë.",
      reserveFreeSeat: "Rezervo vendin ( të {count} të parët falas)",
      payEntryFee: "Paguaj tarifën {fee}",
      flashFirstGroupPayNotice:
        "Grupi i parë me {count} persona u mbush — paguaj {fee} për të konfirmuar vendin.",
      flashFillingNotice: "Duhen edhe {count} regjistrime para se organizatori të mund ta nisë.",
      flashWaitingToStart: "10+ të regjistruar — duke pritur organizatorin të nisë dritaren 24-orëshe.",
      flashSeatReserved:
        "Vendi u rezervua. {count} të parët falas — paguan tarifën kur grupi mbushet.",
      flashCheckoutTitle: "Hyrje në sfidë flash",
      flashCheckoutSummary: "Tarifa e hyrjes për këtë sfidë flash.",
      flashCheckoutNote: "Përfundo pagesën për {title} për të siguruar vendin.",
      flashPaymentSuccessTitle: "Tarifa u pagua",
      flashPaymentSuccessBody: "Vendi yt në sfidën flash u konfirmua.",
      flashPaymentSuccessCta: "Kthehu te sfida",
      viewCurrent: "Shiko sfidën aktuale",
      registrationOpensAt: "Regjistrimi hapet më {date}.",
      registrationJoinWhenLive: "Mund të bashkohesh kur sfida fillon më {date}.",
      registrationClosedAt: "Regjistrimi është mbyllur për këtë sfidë.",
      registrationClosedRegistered: "Je i regjistruar. Nuk lejohet largimi më.",
      leaveLockedTournamentStarted:
        "Turneu ka filluar — nuk mund të largohesh më nga kjo sfidë.",
      successLeft: "U largove nga sfida.",
    },
  },
  platformScore: {
    hoverTitle: "Ndarja e pikëve të platformës",
    hoverIntro: "Peshuar nga ushqimi, stërvitjet dhe zakone + ujë.",
    clickForDetails: "Kliko për detaje të plota",
    dialogTitle: "Pikët e platformës",
    dialogDescription: "Gjithsej {score}/100 bazuar në përdorimin e aplikacionit.",
    dialogIntro:
      "Kryesisht ushqimi, pastaj stërvitjet, pastaj zakonet dhe uji. Pikët janë 0–100 për zonë.",
    nutrition: "Ushqimi",
    workout: "Stërvitjet",
    lifestyle: "Zakone + ujë",
    habits: "Zakonet",
    water: "Uji",
    overall: "Pikë totale",
    lifestyleDetailTitle: "Ndarja e stilit të jetesës",
    openDetails: "Hap detajet e pikëve ({score}/100)",
  },
  aiPages: {
    goalProgress: "Progresi i qëllimit",
    predictionsTitle: "Parashikime progresi me AI",
    mealSuggestionsTitle: "Sugjerime vaktesh me AI",
    reportsTitle: "Raporte javore me AI",
    trainMoreOften: "Stërvitu më shpesh",
    trainMoreOftenBody:
      "Keni regjistruar më pak stërvitje se zakonisht. Synoni të paktën 3 këtë javë.",
    solidTrainingWeek: "Javë e mirë stërvitjeje",
    solidTrainingWeekBody:
      "Volum i mirë — mbajeni ngarkesën progresive në mend.",
    boostProtein: "Rrit proteinat",
    boostProteinBody:
      "Mesatarja e proteinave është nën objektiv. Shtoni burim proteine në çdo vakt.",
    trackMoreDays: "Ndiq më shumë ditë",
    trackMoreDaysBody:
      "Regjistroni vakte dhe stërvitje më rregullisht për analiza më të mira.",
    dailyHabits: "Zakone ditore",
    dailyHabitsBody: "Fitoret e vogla ditore ndërtojnë konsistencë afatgjatë.",
    greatWeek: "Javë e shkëlqyer!",
    greatWeekBody: "Mbajeni proteinën të qëndrueshme dhe orarin e stërvitjes.",
    workouts: "Stërvitje",
    mealsTracked: "Vakte të ndjekura",
    avgProtein: "Proteinë mes.",
  },
} as const;
