import type { CheckoutLocale } from "@/lib/checkout-i18n";

const platformCopyEn = {
  nav: {
    home: "Home",
    programs: "Programs",
    aiCoach: "AI Coach",
    liveCoaching: "Live coaching",
    live: "Live",
    profile: "Profile",
    welcome: (name: string) => `Welcome, ${name}`,
    theme: "Theme",
  },
  trainTabs: {
    workout: "Workout",
    nutrition: "Nutrition",
  },
  profile: {
    title: "Profile",
    subtitle: "Account · subscription · health profile",
    healthProfile: "Health profile",
    complete: "Complete",
    inProgress: "In progress",
    incomplete: "Incomplete",
    account: "Account",
    plan: "Plan",
    manageAccount: "Manage your account and preferences",
    personalInfo: "Personal info",
    appearance: "Appearance",
    password: "Password",
  },
  subscription: {
    title: "Subscription & plans",
    active: "Active",
    accessUntil: (date: string) => `Access until ${date}, then back to free preview`,
    renewsExpires: (date: string) => `Renews / expires ${date}`,
  },
  settings: {
    fullName: "Full name",
    email: "Email",
    phone: "Phone number",
    fitnessGoal: "Fitness goal",
    language: "Language",
    units: "Units",
    metric: "EU / Metric (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    theme: "Theme",
    accentColor: "Accent color",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Profile updated",
    updatePassword: "Update password",
    updating: "Updating...",
    passwordUpdated: "Password updated",
  },
  goals: {
    none: "No goal set",
    lose_weight: "Lose weight",
    build_muscle: "Build muscle",
    stay_fit: "Stay fit",
    improve_endurance: "Improve endurance",
    general_health: "General health",
  },
  dashboard: {
    nutrition: "Nutrition",
    todaysWorkout: "Today's Workout",
    tomorrowsWorkout: "Tomorrow's Workout",
    workoutOnDay: (day: string) => `${day}'s Workout`,
    todaysCardio: "Today's Cardio",
    tomorrowsCardio: "Tomorrow's Cardio",
    cardioOnDay: (day: string) => `${day}'s Cardio`,
    todaysMealPlan: "Today's meal plan",
    mealPlanOnDay: (date: string) => `Meal plan · ${date}`,
    toDoOnDay: (day: string) => `${day}'s To Do`,
    toDoToday: "Today's To Do",
    toDoTomorrow: "Tomorrow's To Do",
  },
} as const;

const platformCopyAl = {
  nav: {
    home: "Kryefaqja",
    programs: "Programet",
    aiCoach: "Coach AI",
    liveCoaching: "Trajnim live",
    live: "Live",
    profile: "Profili",
    welcome: (name: string) => `Mirë se vini, ${name}`,
    theme: "Tema",
  },
  trainTabs: {
    workout: "Stërvitje",
    nutrition: "Ushqimi",
  },
  profile: {
    title: "Profili",
    subtitle: "Llogaria · abonimi · profili shëndetësor",
    healthProfile: "Profili shëndetësor",
    complete: "I plotë",
    inProgress: "Në progres",
    incomplete: "I paplotë",
    account: "Llogaria",
    plan: "Plani",
    manageAccount: "Menaxhoni llogarinë dhe preferencat",
    personalInfo: "Të dhënat personale",
    appearance: "Pamja",
    password: "Fjalëkalimi",
  },
  subscription: {
    title: "Abonimi dhe planet",
    active: "Aktiv",
    accessUntil: (date: string) => `Akses deri më ${date}, pastaj kthehet në modalitetin falas`,
    renewsExpires: (date: string) => `Rinovohet / skadon ${date}`,
  },
  settings: {
    fullName: "Emri i plotë",
    email: "Email",
    phone: "Numri i telefonit",
    fitnessGoal: "Qëllimi i fitnesit",
    language: "Gjuha",
    units: "Njësitë",
    metric: "EU / Metrik (kg, cm)",
    imperial: "US / Imperial (lb, ft/in)",
    theme: "Tema",
    accentColor: "Ngjyra e theksit",
    newPassword: "Fjalëkalimi i ri",
    confirmPassword: "Konfirmo fjalëkalimin",
    saveChanges: "Ruaj ndryshimet",
    saving: "Duke ruajtur...",
    profileUpdated: "Profili u përditësua",
    updatePassword: "Përditëso fjalëkalimin",
    updating: "Duke përditësuar...",
    passwordUpdated: "Fjalëkalimi u përditësua",
  },
  goals: {
    none: "Pa qëllim",
    lose_weight: "Humb peshe",
    build_muscle: "Ndërto muskuj",
    stay_fit: "Qëndro në formë",
    improve_endurance: "Përmirëso qëndrueshmërinë",
    general_health: "Shëndet i përgjithshëm",
  },
  dashboard: {
    nutrition: "Ushqimi",
    todaysWorkout: "Stërvitja e sotme",
    tomorrowsWorkout: "Stërvitja e nesërme",
    workoutOnDay: (day: string) => `Stërvitja e ${day}`,
    todaysCardio: "Kardio e sotme",
    tomorrowsCardio: "Kardio e nesërme",
    cardioOnDay: (day: string) => `Kardio e ${day}`,
    todaysMealPlan: "Menuja e sotme",
    mealPlanOnDay: (date: string) => `Menu · ${date}`,
    toDoOnDay: (day: string) => `Detyrat e ${day}`,
    toDoToday: "Detyrat e sotme",
    toDoTomorrow: "Detyrat e nesërme",
  },
} as const;

export type PlatformCopy = typeof platformCopyEn | typeof platformCopyAl;

export function getPlatformCopy(locale: CheckoutLocale): PlatformCopy {
  return locale === "en" ? platformCopyEn : platformCopyAl;
}

export function getHtmlLang(locale: CheckoutLocale): string {
  return locale === "en" ? "en" : "sq";
}
