/** Albanian display names for catalog foods (also matched as aliases). */
export const FOOD_NAMES_SQ: Record<string, string> = {
  chicken_breast: "gjoks pule",
  chicken_thigh: "kofshë pule",
  turkey_breast: "gjoks gjeldeti",
  turkey_mince: "mish gjeldeti i grirë",
  lean_beef: "mish viçi pa dhjamë",
  beef_mince: "mish viçi i grirë",
  lamb: "mish qengji",
  pork_loin: "fileto derri",
  salmon: "salmon",
  trout: "troftë",
  white_fish: "peshk i bardhë",
  tuna: "ton në ujë",
  sardines: "sardele",
  shrimp: "karkaleca",
  eggs: "vezë",
  egg_whites: "të bardha veze",
  greek_yogurt: "kos grek",
  yogurt: "kos",
  cottage_cheese: "gjizë",
  milk: "qumësht",
  cheese: "kaçkavall",
  feta: "djathë i bardhë",
  mozzarella: "mocarela",
  tofu: "tofu",
  tempeh: "tempeh",
  edamame: "edamame",
  lentils: "thjerrëza",
  chickpeas: "qiqra",
  black_beans: "fasule të zeza",
  kidney_beans: "fasule të kuqe",
  white_rice: "oriz",
  brown_rice: "oriz integral",
  oats: "tërshërë",
  potatoes: "patate",
  sweet_potato: "patate e ëmbël",
  quinoa: "kinoa",
  pasta: "makarona",
  wholewheat_pasta: "makarona integrale",
  bulgur: "bulgur",
  couscous: "kuskus",
  wholegrain_bread: "bukë integrale",
  white_bread: "bukë e bardhë",
  gf_bread: "bukë pa gluten",
  wholewheat_wrap: "tortilja integrale",
  corn_tortilla: "tortilja misri",
  rice_cakes: "galeta orizi",
  buckwheat: "hikërr",
  corn: "misër i ëmbël",
  rice_noodles: "fide orizi",
  muesli: "musli",
  banana: "banane",
  apple: "mollë",
  orange: "portokall",
  pear: "dardhë",
  berries: "fruta pylli",
  kiwi: "kivi",
  grapes: "rrush",
  mango: "mango",
  peach: "pjeshkë",
  pineapple: "ananas",
  watermelon: "shalqi",
  dates: "hurma",
  raisins: "rrush i thatë",
  plum: "kumbulla",
  orange_juice: "lëng portokalli",
  mixed_vegetables: "perime të përziera",
  salad: "sallatë jeshile",
  broccoli: "brokoli",
  spinach: "spinaq",
  bell_pepper: "spec",
  tomato: "domate",
  cucumber: "kastravec",
  carrot: "karota",
  zucchini: "kungulleshë",
  green_beans: "fasule jeshile",
  green_peas: "bizele",
  cauliflower: "lulelakër",
  mushrooms: "kërpudha",
  onion: "qepë",
  asparagus: "shparg",
  cabbage: "lakër",
  kale: "lakër kale",
  eggplant: "patëllxhan",
  beetroot: "panxhar",
  tomato_sauce: "salcë domateje",
  olive_oil: "vaj ulliri",
  vegetable_oil: "vaj vegjetal",
  butter: "gjalpë",
  avocado: "avokado",
  olives: "ullinj",
  almonds: "bajame",
  walnuts: "arra",
  nuts_mixed: "fruta të thata të përziera",
  cashews: "shqeme",
  peanuts: "kikirikë",
  peanut_butter: "gjalpë kikiriku",
  almond_butter: "gjalpë bajameje",
  sunflower_seed_butter: "gjalpë fare luledielli",
  tahini: "tahini",
  chia_seeds: "fara chia",
  flaxseed: "fara liri të bluara",
  pumpkin_seeds: "fara kungulli",
  sunflower_seeds: "fara luledielli",
  hummus: "humus",
  dark_chocolate: "çokollatë e zezë",
  soy_milk: "qumësht soje",
  coconut_milk: "qumësht kokosi",
  oat_milk: "qumësht tërshëre",
  almond_milk: "qumësht bajameje",
  soy_yogurt: "kos soje",
  coconut_yogurt: "kos kokosi",
  seasoning: "kripë e piper",
  garlic: "hudhër",
  lemon: "lëng limoni",
  vinegar: "uthull",
  soy_sauce: "salcë soje",
  mustard: "mustardë",
  salsa: "salsa",
  honey: "mjaltë",
  maple_syrup: "shurup panje",
  ketchup: "ketchup",
  mayonnaise: "majonezë",
  water: "ujë",
  coffee: "kafe",
  tea: "çaj",
  ham: "proshutë",
  turkey_slices: "fileto gjeldeti",
  bacon: "pançetë",
  sausage: "salsiçe",
  salami: "sallam",
  protein_powder: "pluhur proteine whey",
  plant_protein_powder: "pluhur proteine bimore",
  protein_bar: "bar proteinik",
  sugary_cereal: "drithëra me sheqer",
  granola: "granola",
  chips: "patatina",
  popcorn: "kokoshka",
  cookies: "biskota",
  cake: "kek",
  candy: "karamele",
  ice_cream: "akullore",
  soda: "pije e gazuar",
  fast_food: "burger",
  instant_noodles: "noodle të menjëhershme",
  ready_meal: "gatim i gatshëm",
  margarine: "margarinë",
  flavored_yogurt: "kos me fruta",
};
